### ISSUE TITLE
Cannot read property 'text' of undefined in HelpCompletionFeature

### ISSUE THREAD

**Issue by aeschli** [PowerShell/vscode-powershell#1043]
powershell extension 1.4.3

editing on the empty line below (line 5) and doing code assist resulted in an error in the console
```
#region
Write-host '1 unicorn Dead!'
Write-host '2 unicorns Dead!'
Write-host '3 unicorns Dead!'

#endregion
```

shell.ts:454 [ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (/home/aeschli/.vscode-insiders/extensions/ms-vscode.powershell-1.4.3/out/src/features/HelpCompletion.js:34:100)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57853)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:59575)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:362895)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:444633)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290278)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:289305
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:291224
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:58570

**Comment by aeschli** [comment]
Oh, that's on Linux ;-) The status line shows that there is a problem with starting the language server:

10/5/2017 9:41:47 AM [NORMAL] - Language server starting --
10/5/2017 9:41:47 AM [NORMAL] -     exe: /usr/bin/powershell
10/5/2017 9:41:47 AM [NORMAL] -     args: /home/aeschli/.vscode-insiders/extensions/ms-vscode.powershell-1.4.3/scripts/Start-EditorServices.ps1 -EditorServicesVersion '1.4.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.4.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/home/aeschli/.vscode-insiders/extensions/ms-vscode.powershell-1.4.3/modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath '/home/aeschli/.vscode-insiders/extensions/ms-vscode.powershell-1.4.3/logs/1507189307-3e096b94-3e42-42e4-8559-e6ee716a7e901507189304951/EditorServices.log' -SessionDetailsPath '/home/aeschli/.vscode-insiders/extensions/ms-vscode.powershell-1.4.3/sessions/PSES-VSCode-15324-687857' -FeatureFlags @()
10/5/2017 9:41:48 AM [NORMAL] - powershell.exe started, pid: 18670
10/5/2017 9:41:48 AM [NORMAL] - powershell.exe terminated or terminal UI was closed

**Comment by Artur2** [comment]
Same thing on Latest Version of VS Code and Powershell Addon.
`[ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (C:\Users\Arthur\.vscode\extensions\ms-vscode.powershell-1.5.0\out\src\features\HelpCompletion.js:34:100)
	at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59575)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:362973)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:444706)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290666)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290356)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:289383
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:291302
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:58570`

While editing or saving file, On Mac there is not autocompletion absolutely.

**Comment by SydneyhSmith** [comment]
we recently published an update to our extension which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue?
