### ISSUE TITLE
Invalid Argument warning appearing when pressing tab.

### ISSUE THREAD

**Issue by weinand** [PowerShell/vscode-powershell#1118]
_From @james-woodbridge on December 6, 2017 15:2_

- VSCode Version: 1.18.1
- OS Version: Windows 10 Pro Build 15063.726

Steps to Reproduce:

1. Attempt to autocomplete a parameter name when writing up a cmdlet call in a Powershell script by pressing tab. This was after a restart.

Screenshot of workspace attached, errors from console below.

```
ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (C:\Users\james.woodbridge.SFS\.vscode\extensions\ms-vscode.powershell-1.5.1\out\src\features\HelpCompletion.js:34:100)
	at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427735)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:85128
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 [ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (C:\Users\james.woodbridge.SFS\.vscode\extensions\ms-vscode.powershell-1.5.1\out\src\features\HelpCompletion.js:34:100)
	at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427735)
	at e.$acceptModelSaved (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427518)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 [ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (C:\Users\james.woodbridge.SFS\.vscode\extensions\ms-vscode.powershell-1.5.1\out\src\features\HelpCompletion.js:34:100)
	at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427735)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:85128
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 [ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (C:\Users\james.woodbridge.SFS\.vscode\extensions\ms-vscode.powershell-1.5.1\out\src\features\HelpCompletion.js:34:100)
	at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427735)
	at e.$acceptModelSaved (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427518)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 [ms-vscode.PowerShell] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
	at HelpCompletionFeature.onEvent (C:\Users\james.woodbridge.SFS\.vscode\extensions\ms-vscode.powershell-1.5.1\out\src\features\HelpCompletion.js:34:100)
	at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427735)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:85128
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property '_placeholderDecorations' of undefined: TypeError: Cannot read property '_placeholderDecorations' of undefined
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1012928
    at t._changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951992)
    at t.changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951213)
    at t.changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1308339)
    at e.merge (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1012782)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1016800
    at e.pushEditOperation (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:426645)
    at t._pushEditOperations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:963461)
    at t.pushEditOperations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:962458)
    at e.merge (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1016691)
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1011239
    at t._changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951992)
    at t.changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951213)
    at e.move (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1011003)
    at e._move (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1017225)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1016877
    at e.pushEditOperation (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:426645)
    at t._pushEditOperations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:963461)
    at t.pushEditOperations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:962458)
    at e.merge (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1016691)
```

![image](https://user-images.githubusercontent.com/7914837/33668040-7c5efb38-da96-11e7-9a6e-7327ce1e2b7d.png)

_Copied from original issue: Microsoft/vscode#39800_

**Comment by james-woodbridge** [comment]
Further details - the `-POST` part after the cmdlet was not the source of the error, the VSCode editor highlights the parameter related to the warning when this bug happens, and so the `-Method` became `-POST`

**Comment by james-woodbridge** [comment]
This issue occurred again, when using tab to autocomplete an argument for a powershell cmdlet. I began byu typing the first two letters of the argument to make sure it was the correct one, then pressed tab to autocomplete. There stack trace is:

```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1011239
    at t._changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951992)
    at t.changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951213)
    at e.move (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1011003)
    at e._move (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1017225)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1016877
    at e.pushEditOperation (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:426645)
    at t._pushEditOperations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:963461)
    at t.pushEditOperations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:962458)
    at e.merge (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1016691)
```

Screenshot attached
![image](https://user-images.githubusercontent.com/7914837/33710003-1e03589e-db37-11e7-9a54-6b8dbadb7c9a.png)

**Comment by james-woodbridge** [comment]
It is worth checking issue #39594, as this may be related. The issue does seem to occur when using nested snippets

**Comment by SydneyhSmith** [comment]
@weinand we recently published an update to our extension which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue?
