### ISSUE TITLE
Powershell Integrated Terminal crashes as soon as file is opened

### ISSUE THREAD

**Issue by bugili** [PowerShell/vscode-powershell#1203]
### System Details

donjayamanne.githistory@0.4.0
dracula-theme.theme-dracula@2.8.1
ms-mssql.mssql@1.3.0
ms-python.python@2018.1.0
ms-vscode.csharp@1.14.0
ms-vscode.PowerShell@1.5.1
ms-vsts.team@1.122.0

Name                                       Value
----                                          -----
PSVersion                                 5.1.15063.786
PSEdition                                  Desktop
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0...}
BuildVersion                             10.0.15063.786
CLRVersion                               4.0.30319.42000
WSManStackVersion                 3.0
PSRemotingProtocolVersion      2.3
SerializationVersion                   1.1.0.1

### Issue Description

After opening folder and selecting file for editing, powershell integrated console crashes immediately. 
If the same file is opened directly (without opening entire folder) everything works as expected. 

### Attached Logs

2/20/2018 2:45:00 PM [ERROR] - Method "OnListenTaskCompleted" at line 391 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs

    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.ScriptRegion.Create(IScriptExtent scriptExtent)
       at Microsoft.PowerShell.EditorServices.ScriptFileMarker.FromParseError(ParseError parseError)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ParseFileContents()
       at Microsoft.PowerShell.EditorServices.LanguageService.<FindReferencesOfSymbol>d__18.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<ResolveCodeLensAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.<HandleCodeLensResolveRequest>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.ScriptRegion.Create(IScriptExtent scriptExtent)
       at Microsoft.PowerShell.EditorServices.ScriptFileMarker.FromParseError(ParseError parseError)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ParseFileContents()
       at Microsoft.PowerShell.EditorServices.LanguageService.<FindReferencesOfSymbol>d__18.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<ResolveCodeLensAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.<HandleCodeLensResolveRequest>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()<---
    

2/20/2018 2:45:00 PM [ERROR] - Method "ProtocolEndpoint_UnhandledException" at line 418 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.

**Comment by rkeithhill** [comment]
Any chance you could provide a copy of the script?  It seems there is a parse error in the script that is tickling a bug in one of the CodeLens implementations.

**Comment by bugili** [comment]
There's a lot of them, and really think that it's somehow folder related but sure:

```
function Add-RegistryAccessRule
{
    [Cmdletbinding()]
    param (
        [ValidateScript({ test-path $_})]
        [string] $Key,
        [string] $Identity,        
        [System.Security.AccessControl.RegistryRights[]] $Permission,
        [System.Security.AccessControl.AccessControlType] $Access,
        [switch] $PassThru,
        [switch] $Merge 
    )
    $acl = (gi $Key).GetAccessControl()
    $rule = New-Object System.Security.AccessControl.RegistryAccessRule($Identity, $Permission, $Access)
    
    try
    {
        if ($Merge)
        {
            $acl.AddAccessRule($rule)
        }
        else 
        {
            $acl.SetAccessRule($rule)
        }        
        Set-Acl -Path $key -AclObject $acl -ea Stop
    }
    catch
    {
        Write-Verbose 'Failed'
        throw $_.Exception
    }
    Write-Verbose 'Done'
    if ($PassThru)
    {
        Get-Acl -Path $key
    }
    
}
```

They all work when I open them separately as single files.

**Comment by rkeithhill** [comment]
Yeah, that script alone isn't enough to trigger the crash.  :-(

**Comment by tylerl0706** [comment]
I think this might have been fixed and we need some more repro information. I'm going to close this for now, if you still see the issue please comment and I'm happy to reopen this.
