### ISSUE TITLE
powershell.exe terminated or terminal UI was closed

### ISSUE THREAD

**Issue by yoke88** [PowerShell/vscode-powershell#1211]
### System Details

- Operating system name and version: deepin linux 15.5
- VS Code version: 1.19.0-1513245498
- PowerShell extension version: 6.0.1
- Output from `$PSVersionTable`:                                                                      

```
PS /> code -v                                                                                               
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
x64
PS /> $pseditor.EditorServicesVersion                                                                       
PS /> code --list-extensions --show-versions                                                                
ms-vscode.PowerShell@1.6.0
PS /> $PSVersionTable                                                                                       

Name                           Value                                                                       
----                           -----                                                                       
PSVersion                      6.0.1                                                                       
PSEdition                      Core                                                                        
GitCommitId                    v6.0.1                                                                      
OS                             Linux 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)      
Platform                       Unix                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                     
PSRemotingProtocolVersion      2.3                                                                         
SerializationVersion           1.1.0.1                                                                     
WSManStackVersion              3.0                                                                         

```

### Issue Description

when i open a script , script content is below: there will be a prompt ask for 'The powershell session has terminated due to an error,would you like to restart it ,if i click yes ,after a few minutes ,the prompt appear again.

```powershell
function get-key{
    [cmdletbinding(ConfirmImpact="medium",
    SupportsShouldProcess=$true
    )]
    [outputtype( )]
    param(
        [Parameter(ParameterSetName="ps1",Mandatory=$true,Position=1,ValueFromPipeline=$true)]
        [ValidateSet("AA","BB")]
        [string]
        $set
    )
    begin{

    }
    process{
        if($PSCmdlet.ShouldProcess("ouput value of `$set =$set","output")){
            Write-Output $set
        }
    }
    end{

    }
}

"AA","BB" |get-key 

```

### Attached Logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/1751622/EditorServices.log)

**Comment by rkeithhill** [comment]
The interesting bits of the log are:
```
2018-02-23 20:23:14 [WARNING] - Method "GetVersionDetails" at line 153 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellVersionDetails.cs

    Failed to look up PowerShell version, defaulting to version 5.
    
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<>c__56`1.<ExecuteScriptAndGetItem>b__56_0(PSObject pso)
       at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
       at System.Linq.Enumerable.<OfTypeIterator>d__32`1.MoveNext()
       at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteScriptAndGetItem[TResult](String scriptToExecute, Runspace runspace, TResult defaultValue)
       at Microsoft.PowerShell.EditorServices.Session.PowerShellVersionDetails.GetVersionDetails(Runspace runspace, ILogger logger)

2018-02-23 20:23:14 [NORMAL] - Method "Initialize" at line 220 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    PowerShell runtime version: 6.0.1, edition: Core
```
I've seen this `"failure to look upPower Shell version, defaulting to version 5"` several times now.  It needs to be looked into.

**Comment by tylerl0706** [comment]
Yeah I can look into this since I repro it consistently.
