### ISSUE TITLE
Console hangs when running a code selection in remote session file.

### ISSUE THREAD

**Issue by jeremytbrun** [PowerShell/vscode-powershell#1275]
## Issue Description ##

I am experiencing a 

The console hanging when running a code selection in remote session file.

Steps to reproduce.
Enter-PSSession
Open-EditorFile <file>
Select a line from opened file and _Run Selection_.

The console then hangs.

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.15063 |
| VSCode | 1.22.2|
| PowerShell Extension Version | 1.6.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.15063.966|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.15063.966|
|BuildVersion|10.0.15063.966|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|gitlens|eamodio|8.2.1|
|gremlins|nhoizey|0.7.0|
|PowerShell|ms-vscode|1.6.0|
|python|ms-python|2018.3.1|
|tslint|eg2|1.0.28|
|vscode-icons|robertohuertasm|7.22.0|;

</details>

**Comment by tylerl0706** [comment]
Thanks for the info! This looks related to #1262...

Can you please attach the logs? The instructions can be found here:
https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by tylerl0706** [comment]
Thanks! Taking some notes for myself..

tons of `$/cancelRequest` messages. Could be unrelated to the issue.

Also saw this warning:

```
2018-04-18 09:17:15 [WARNING] - Method "GetAliases" at line 703 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Language\LanguageService.cs

    Caught PSNotSupportedException while attempting to get aliases from remote session:
    
    System.Management.Automation.PSNotSupportedException: Specified method is not supported.
       at System.Management.Automation.RemoteSessionStateProxy.get_InvokeCommand()
       at Microsoft.PowerShell.EditorServices.LanguageService.<GetAliases>d__25.MoveNext()

```

which could cause something funny to happen. I need to look at #1262 to see the logs in that one.

**Comment by tylerl0706** [comment]
It looks like they might be related. I'm going to dupe that to this one.

**Comment by jeremytbrun** [comment]
Great! Should this be labled as a bug like the previous issue?

**Comment by tylerl0706** [comment]
Indeed 👍 couldn't get to this in the release today but will try to get to it for the next one!
