### ISSUE TITLE
Error: write after end 

### ISSUE THREAD

**Issue by jrieken** [PowerShell/vscode-powershell#145]
Our error telemetry shows these

```
Error: write after end 
at writeAfterEnd (_stream_writable.js:159:12) 
at Socket.Writable.write (_stream_writable.js:204:5) 
at Socket.write (net.js:618:40) 
at MessageWriter.write (\ms-vscode.PowerShell\node_modules\vscode-jsonrpc\lib\messageWriter.js:21:23) 
at \ms-vscode.PowerShell\node_modules\vscode-jsonrpc\lib\main.js:184:32 
at Object.connection.sendRequest (\ms-vscode.PowerShell\node_modules\vscode-jsonrpc\lib\main.js:175:20) 
at Object.result.sendRequest (\ms-vscode.PowerShell\node_modules\vscode-languageclient\lib\main.js:38:66) 
at Object._providers.push.vscode_1.languages.registerSignatureHelpProvider.apply.provideSignatureHelp (\ms-vscode.PowerShell\node_modules\vscode-languageclient\lib\main.js:596:39) 
at \out\vs\workbench\node\pluginHostProcess.js:20:11498 
at \out\vs\workbench\node\pluginHostProcess.js:7:31756 
```

**Comment by daviwil** [comment]
This is pretty difficult to diagnose without more context.  Is there any other information about what the user might have been doing at the time?  How often does it show up in the telemetry?

This could also just be from me killing my language server process when I'm developing features for the extension.

**Comment by jrieken** [comment]
Sorry, for further information. Tho this might be an issue with @dbaumer's lib

**Comment by tylerl0706** [comment]
Hey @jrieken, have seen this issue recently?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
