### ISSUE TITLE
Error: Message header must separate key and value using : 

### ISSUE THREAD

**Issue by jrieken** [PowerShell/vscode-powershell#146]
```
Error: Message header must separate key and value using : 
at \ms-vscode.PowerShell-0.5.0\node_modules\vscode-jsonrpc\lib\messageReader.js:54:23 
at Array.forEach (native) 
at MessageBuffer.tryReadHeaders (\ms-vscode.PowerShell-0.5.0\node_modules\vscode-jsonrpc\lib\messageReader.js:51:17) 
at StreamMessageReader.onData (\ms-vscode.PowerShell-0.5.0\node_modules\vscode-jsonrpc\lib\messageReader.js:102:43) 
at Socket.<anonymous> (\ms-vscode.PowerShell-0.5.0\node_modules\vscode-jsonrpc\lib\messageReader.js:95:19) 
at emitOne (events.js:77:13) 
at Socket.emit (events.js:169:7) 
at readableAddChunk (_stream_readable.js:146:16) 
at Socket.Readable.push (_stream_readable.js:110:10) 
at Pipe.onread (net.js:523:20) 
```

**Comment by daviwil** [comment]
How frequent is this?  Do we have any information like what string it was trying to parse at the time?

**Comment by tylerl0706** [comment]
Hey @jrieken, have seen this issue recently?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
