### ISSUE TITLE
Format Document: Changes Tabs for Spaces

### ISSUE THREAD

**Issue by Midacts** [PowerShell/vscode-powershell#1466]
### System Details

- Operating system name and version: Windows 10.0.15063
- VS Code version: 1.25.1 1dfc5e557209371715f655691b1235b6b26a06be x64
- PowerShell extension version: 1.8.2
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.1155
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1155
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

```
PS C:\> code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64

PS C:\> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      2      0


PS C:\> code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.19.0
donjayamanne.githistory@0.4.2
eamodio.gitlens@8.5.4
mauve.terraform@1.3.4
ms-vscode.PowerShell@1.8.2
robertohuertasm.vscode-icons@7.25.0
shd101wyy.markdown-preview-enhanced@0.3.5
Tyriar.sort-lines@1.7.0
ApplicationInsights:Sender [ { Error: self signed certificate in certificate chain
      at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:188:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } ]

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.1155
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1155
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am using PowerShell.

I have lines of code link this which are key value pairs
After running Right click -> Format document, it replaces the tabs with spaces for the white spaces between the key and the "=" sign
My settings:
"editor.insertSpaces": false,
"editor.tabSize": 4,
"files.encoding": "utf8",
"files.eol": "\r\n",

Example
"key"	= "test"
changes to
"key" = "test"

Does this issue occur when all extensions are disabled?: No, because there isnt an option to Format document when --disable-extension used.

**Comment by rjmholt** [comment]
Hi @Midacts, can you execute the following command to see if you get the same result:
```powershell
> Invoke-Formatter (Get-Content -Raw ./path/to/your/script.ps1) > output.ps1
```
If `output.ps1` here also has the converted tabs/spaces, then the problem is occurring in [PSScriptAnalyzer](https://github.com/powershell/psscriptanalyzer)'s `Invoke-Formatter` command. Otherwise, it is likely a problem in [EditorServices](https://github.com/PowerShell/PowerShellEditorServices).

**Comment by Midacts** [comment]
Running the above command turned all tabs into spaces and saved the file as UTF-16 LE.

I did notice, in examples like PSCustomObjects, it didnt replaces all spaces with tabs, maybe 1+ of the tabs stayed a tab and all the rest were changed to spaces.

## Question
What would next steps be?

**Comment by Midacts** [comment]
Thanks for the great lead.

Running `Invoke-Formatter` with '-Verbose' shows that it is using a 'Settings\CodeFormatting.psd1' file in the PSScriptAnalyzer module.

I made my own codeformatting.psd1 file and it did use tabs EXCEPT in the case of key/value pairs. It converted to spaces between the key and the equal sign.

[PSScriptAnalyzer issue opened](https://github.com/PowerShell/PSScriptAnalyzer/issues/1055)

**Comment by tylerl0706** [comment]
Thanks for doing that! I'll close this now since it's a Script Analyzer issue. Let me know if you feel otherwise! 👍
