### ISSUE TITLE
Remote debugging macOS -> Windows not working properly (incorrect path)

### ISSUE THREAD

**Issue by oivindoh** [PowerShell/vscode-powershell#1515]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
code -v
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64

$pseditor.EditorServicesVersion:
Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      4      0

code --list-extensions --show-versions
akamud.vscode-theme-onedark@2.1.0
DavidAnson.vscode-markdownlint@0.20.0
eamodio.gitlens@8.5.6
EFanZh.graphviz-preview@1.2.0
Equinusocio.vsc-material-theme@2.4.2
felipe.nasc-touchbar@1.11.0
IBM.XMLLanguageSupport@0.0.1
JayFiDev.markdown-touchbar@1.0.3
jebbs.plantuml@2.8.6
mauve.terraform@1.3.4
ms-azuretools.vscode-azureterraform@0.2.2
ms-python.python@2018.7.1
ms-vscode.azure-account@0.4.3
ms-vscode.cpptools@0.18.1
ms-vscode.csharp@1.15.2
ms-vscode.Go@0.6.89
ms-vscode.PowerShell@1.8.4
nachocab.highlight-dodgy-characters@1.0.0
nestalk.preview-control-characters@0.0.1
PeterJausovec.vscode-docker@0.1.0
qhoekman.language-plantuml@0.0.3
robertohuertasm.vscode-icons@7.25.0
Stephanvs.dot@0.0.1
zhuangtongfa.Material-theme@2.15.4

$PSVersionTable (macos client)
Name                           Value
----                           -----
PSVersion                      6.0.3
PSEdition                      Core
GitCommitId                    v6.0.3
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$PSVersionTable (connected windows session)
Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with [remote debugging](https://github.com/PowerShell/vscode-powershell/blob/master/docs/remoting.md). Following the example I'm assuming the correct debugging configuration (missing from example) would be "PowerShell Launch Current File".

When I fire off the debugging session after entering the remote pssesssion via `enter-pssession -hostname tdtrhoptimsa001` and running `Open-EditorFile C:\Users\oho\Documents\test.ps1` on the desired file `C:\Users\oho\Documents\test.ps1`, I get the following in EditorServices.log:

```
2018-09-03 14:54:30.053 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs: In method 'HandleSetBreakpointsRequest', line 509: Failed to set breakpoint on file: /var/folders/_z/c_wmy7ys06s3zzhyxyg9wz4sbxjbkl/t/pses-964/remotefiles/966056463/tdtrhoptimsa001/c:/users/oho/documents/test.ps1
    System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/folders/_z/c_wmy7ys06s3zzhyxyg9wz4sbxjbkl/t/pses-964/remotefiles/966056463/tdtrhoptimsa001/c:/users/oho/documents/test.ps1'.
       at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
       at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<HandleSetBreakpointsRequest>d__29.MoveNext()
```

It appears the remote debugging service on the windows node is is attempting to read part of the ephemeral path this remote file has locally on macOS?

Breakpoints appear verified in the vscode GUI.

`test.ps1` content:

```
write-host 'remote file'

$Variable = [system.environment]::GetEnvironmentVariable('TEMP')
$FileToWrite = ('{0}\Documents\{1}.file' -f $env:USERPROFILE, (get-date).ToString('mmss'))

new-item -ItemType File -Path $FileToWrite

write-host ('wrote it.. {0}' -f $Variable)
```

And each debug run results in a new file getting successfully written on the remote server. Breakpoint is placed on the $FileToWrite line.

If I run the same script locally, the debugger successfully hits the breakpoint I set on the $FileToWrite line.

I'd expect the debugger to be able to hit the remote breakpoint too.

### Attached Logs

[Archive.zip](https://github.com/PowerShell/vscode-powershell/files/2345668/Archive.zip)

**Comment by andschwa** [comment]
Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by andschwa** [comment]
Going to assume it's no longer an issue, thanks!
