### ISSUE TITLE
Function reference counter more than 0 makes the extension crashing

### ISSUE THREAD

**Issue by JackBauer78** [PowerShell/vscode-powershell#1605]
When I create a simple function with or without parameters, the reference counter at the top of it says "0 reference".
As soon as I call it right under, the extension crashes : "The Powershell extension has terminated due to an error, would you like to restart it?"
I restart it and it crashes right after.
I relaunched VS Code and reinstalled the extension without any success.

Here's an example without the crash :
```
0 reference
function Test {

}
```

With a crash right after :
```

function Test {

}

Test
```

### Visual Studio Code
Name | Version
-- | --
Operating System | MacOS Mojave 10.14.1
VSCode | 1.28.2
PowerShell Extension Version | 1.9.0

### Powershell Information
Name | Value
-- | --
PSVersion | 6.0.1
PSEdition | Core
GitCommitId | v6.0.1
OS | Darwin 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
Platform | Unix
PSCompatibleVersions | 1.0 2.0 3.0 4.0...
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1
WSManStackVersion | 3.0

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/powershell/vscode-powershell#reporting-problems) here so we can get a better idea of what's going on?

**Comment by JackBauer78** [comment]
Here they are :
[Logs_vscode_powershell.zip](https://github.com/PowerShell/vscode-powershell/files/2567496/Logs_vscode_powershell.zip)

**Comment by rjmholt** [comment]
Looks like the relevant section is:
```
2018-11-09 21:59:44.061 [VERBOSE] C:\PowerShellEditorServices\src\PowerShellEditorServices\Workspace\Workspace.cs: In method 'ResolveFilePath', line 382:
    Resolved path: /Volumes/Mes_fichiers/Vidéos/Test.ps1

2018-11-09 21:59:44.103 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Length cannot be less than zero.
    Parameter name: length) ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
    Parameter name: length
       at System.String.Substring(Int32 startIndex, Int32 length)
       at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
       at System.Uri.CreateHostString()
       at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
       at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
       at System.Uri.GetComponents(UriComponents components, UriFormat format)
       at System.Uri.get_AbsoluteUri()
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<ResolveCodeLensAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.<HandleCodeLensResolveRequest>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Length cannot be less than zero.
    Parameter name: length
       at System.String.Substring(Int32 startIndex, Int32 length)
       at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
       at System.Uri.CreateHostString()
       at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
       at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
       at System.Uri.GetComponents(UriComponents components, UriFormat format)
       at System.Uri.get_AbsoluteUri()
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<ResolveCodeLensAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.<HandleCodeLensResolveRequest>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
    

2018-11-09 21:59:44.103 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: In method 'ProtocolEndpoint_UnhandledException', line 435:
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.
```

@JackBauer78, if you do the same thing under the `/Volumes/Mes_fichiers/Test.ps1`, does this bug still occur? I'm thinking it has something to do with the `é` in `Vidéo` -- this is another URI/path encoding bug. (@rkeithhill on the money as usual)

**Comment by rjmholt** [comment]
Also, @JackBauer78 it may be worth updating to PowerShell 6.1.0.

**Comment by JackBauer78** [comment]
I upgraded Powershell to 6.1.0 with the same path with the `é` and it worked like a charm !
I don't know why I didn't install the last version before...
Thank you very much ! :)

**Comment by JackBauer78** [comment]
One thing I want to add which is completely different, I had to search why I couldn't run any script within VS Code and it was because the launch was now `pwsh -ExecutionPolicy Bypass -File ` instead of `powershell -ExecutionPolicy Bypass -File `.
Could you adapt this to the version of Powershell installed in the settings or something ?

**Comment by JackBauer78** [comment]
My bad, it's in the "Code runner" extension, forget what I said.

**Comment by TylerLeonhardt** [comment]
Glad to hear you're unblocked!

Is there anything else related to this issue or is it alright if we close it?
