### ISSUE TITLE
Debug adapter process has terminated unexpectedly, when Wait-Process completes

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#168]
Again, sorry guys, I do not know if this is a VSCode bug or the PowerShell Extension bug, so I will start here:

The Codes is relativity simple:
```
$proc = Start-Process $PathToExe -ArgumentList $ArgList
Wait-Process $proc.Id
```

When you run this in the Debugger, when the `$proc` process finished, the Debugger terminates unexpectedly.

**Comment by rkeithhill** [comment]
Thanks.  I was able to repro it.  The exception info is;
```
5/8/2016 11:15:49 PM [ERROR] - Method "CurrentDomain_UnhandledException" at line 125 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    FATAL UNHANDLED EXCEPTION:
    
    System.Management.Automation.ExtendedTypeSystemException: The following exception occurred while retrieving the string: "Process has exited, so the requested information is not available." ---> System.InvalidOperationException: Process has exited, so the requested information is not available.
       at System.Diagnostics.Process.EnsureState(State state)
       at System.Diagnostics.Process.get_ProcessName()
       at System.Diagnostics.Process.ToString()
       at System.Management.Automation.PSObject.ToString(ExecutionContext context, Object obj, String separator, String format, IFormatProvider formatProvider, Boolean recurse, Boolean unravelEnumeratorOnRecurse)
       --- End of inner exception stack trace ---
       at System.Management.Automation.PSObject.ToString(ExecutionContext context, Object obj, String separator, String format, IFormatProvider formatProvider, Boolean recurse, Boolean unravelEnumeratorOnRecurse)
       at System.Management.Automation.PSObject.ToString()
       at Microsoft.PowerShell.EditorServices.VariableDetails.GetValueString(Object value, Boolean isExpandable)
       at Microsoft.PowerShell.EditorServices.VariableDetails..ctor(String name, Object value)
       at Microsoft.PowerShell.EditorServices.DebugService.<FetchVariableContainer>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.DebugService.<FetchGlobalAndScriptVariables>d__24.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.DebugService.<FetchStackFramesAndVariables>d__23.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.DebugService.<OnDebuggerStop>d__35.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by daviwil** [comment]
Hmmm, I can't get Start-Process to return anything other than null so Wait-Process doesn't work for me.  How did you repro this @rkeithhill?  Just trying to verify that it works on my side before I close the bug.

**Comment by rkeithhill** [comment]
The repro code is (inserted into DebugTest.ps1:
```powershell
$pathToExe = 'Notepad.exe'
$proc = Start-Process $PathToExe -PassThru
Wait-Process -Id $proc.Id

Do-Work 50 # breakpoint set here
```
When this works, you will see this variable value in the variables view when the breakpoint is hit:
![pses-is168](https://cloud.githubusercontent.com/assets/5177512/15166369/533595f8-16db-11e6-9a0e-f6f7284e9966.png)

**Comment by daviwil** [comment]
Thanks!  `-PassThru` is what I was missing.  I've verified that this has been fixed after Keith's fix in PowerShellEditorServices today.  I'll close this bug once 0.6.0 has been released.

**Comment by swinster** [comment]
Have you added the -passthrough parameter?

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, May 10, 2016 at 4:48 PM -0700, "David Wilson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm, I can't get Start-Process to return anything other than null so Wait-Process doesn't work for me. How did you repro this @rkeithhill<https://github.com/rkeithhill>? Just trying to verify that it works on my side before I close the bug.

**Comment by daviwil** [comment]
0.6.0 is now released!  Let us know if you run into any further trouble.
