### ISSUE TITLE
Request textDocument/definition failed.

### ISSUE THREAD

**Issue by ebmarquez** [PowerShell/vscode-powershell#1705]
Issue Type: <b>Bug</b>

Open new file, don't save the file.
This will have a title of Untitled-1
set the file type as PowerShell.

edit the file and powershell will crash over a period of time. 
Log files attached to the bug.
[1547841607-ef284c55-1318-424a-ac65-a2122836f0041547841601125.zip](https://github.com/PowerShell/vscode-powershell/files/2774446/1547841607-ef284c55-1318-424a-ac65-a2122836f0041547841601125.zip)

Extension version: 1.10.2
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

Powershell Editor Services log
`
[Error - 12:21:20 PM] Connection to server got closed. Server will not be restarted.
[Error - 12:21:20 PM] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-languageclient\lib\client.js:2150:42)
	at LanguageClient.handleConnectionClosed (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-languageclient\lib\main.js:150:15)
	at closeHandler (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-languageclient\lib\client.js:2137:18)
	at CallbackList.invoke (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageWriter.fireClose (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\messageWriter.js:39:27)
	at Socket.AbstractMessageWriter.constructor.encoding.writable.on (C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\node_modules\vscode-jsonrpc\lib\messageWriter.js:58:46)
	at emitOne (events.js:121:20)
	at Socket.emit (events.js:211:7)
	at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12)
`

PowerShell Extension Log
`
1/18/2019 12:00:07 PM [NORMAL] - Visual Studio Code v1.30.2 64-bit
1/18/2019 12:00:07 PM [NORMAL] - PowerShell Extension v1.10.2
1/18/2019 12:00:07 PM [NORMAL] - Operating System: Windows 64-bit
1/18/2019 12:00:07 PM [NORMAL] - Language server starting --
1/18/2019 12:00:07 PM [NORMAL] -     exe: C:\WINDOWS\SysWow64\WindowsPowerShell\v1.0\powershell.exe
1/18/2019 12:00:07 PM [NORMAL] -     args: C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\logs\1547841607-ef284c55-1318-424a-ac65-a2122836f0041547841601125\EditorServices.log' -SessionDetailsPath 'C:\Users\emarq\.vscode\extensions\ms-vscode.powershell-1.10.2\sessions\PSES-VSCode-8188-226591' -FeatureFlags @()
1/18/2019 12:00:09 PM [NORMAL] - powershell.exe started, pid: 12888
1/18/2019 12:00:15 PM [NORMAL] - Language server started.
1/18/2019 12:00:15 PM [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_4wsmm4vz.rfk","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_ymutdxps.sca"}
1/18/2019 12:00:15 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_4wsmm4vz.rfk...
1/18/2019 12:00:15 PM [NORMAL] - Language service connected.
1/18/2019 12:21:23 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
`

**Comment by SydneyhSmith** [comment]
Hi @ebmarquez  thanks for reporting! This seems like a dup of #1649 which should be fixed in the update coming out very soon! I am going to close this issue for now but we will re-open if the update doesn't fix it!
