### ISSUE TITLE
go to reference error

### ISSUE THREAD

**Issue by andre-capri-iag** [PowerShell/vscode-powershell#1720]
Issue Type: <b>Bug</b>

When clicking on the "#no. references" link above CmdLets, the terminal crashes with an error about json,
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readSessionFile (c:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.10.2\out\src\utils.js:73:17)
    at startDebugging (c:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.10.2\out\src\debugAdapter.js:25:34)
    at waitForSessionFile (c:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.10.2\out\src\debugAdapter.js:73:13)
    at Object.<anonymous> (c:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.10.2\out\src\debugAdapter.js:93:1)
    at Object.<anonymous> (c:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.10.2\out\src\debugAdapter.js:95:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

Extension version: 1.10.2
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.41GB (7.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
Can you update to the latest version (1.11.0) and try again? Thanks!

**Comment by andre-capri-iag** [comment]
Ah sure I'll update and see if it happens still

**Comment by andre-capri-iag** [comment]
I have hit this error again, some more logs this time:
- Log (Window)
```
[2019-01-25 12:42:56.256] [renderer1] [error] resource is not available: Error: resource is not available
    at t.createReferencedObject (file:///C:/Users/si560869/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4740:744)
    at file:///C:/Users/si560869/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4740:853
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-01-25 12:43:52.414] [renderer1] [error] Cannot read property 'callback' of undefined: TypeError: Cannot read property 'callback' of undefined
	at __dirname.showSessionMenu.vscode.window.showQuickPick.then (C:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.11.0\out\src\session.js:555:52)
	at <anonymous>
[2019-01-25 12:43:57.216] [renderer1] [error] Cannot read property 'callback' of undefined: TypeError: Cannot read property 'callback' of undefined
	at __dirname.showSessionMenu.vscode.window.showQuickPick.then (C:\Users\si560869\.vscode\extensions\ms-vscode.powershell-1.11.0\out\src\session.js:555:52)
	at **<anonymous>**
```

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by SydneyhSmith** [comment]
Going to close this issue as inactive, will re-open with more information!
