### ISSUE TITLE
ms-vscode.PowerShell Extension fails to load at all

### ISSUE THREAD

**Issue by eguch-occ** [PowerShell/vscode-powershell#1844]
### System Details

System Details Output
```
### VSCode version: 1.28.2 7f3ce96ff4729c91352ae6def877e59c561f4850 x64

### VSCode extensions:
ms-vscode.powershell@1.12.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The ms-vscode.PowerShell extension will not load and creates an error stack in the Developer Tools console.

#### Expected Behaviour

When opening a PowerShell file, the extension loads and allows me to edit and run code in an integrated powershell terminal

#### Actual Behaviour

Nothing

### Attached Logs

The extension never actually loads, so it does not create any logs. 
```
-===-[Extension Host] Activating extension 'ms-vscode.powershell' failed: Cannot read property 'packageJSON' of undefined.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 
-===-[Extension Host] Activating extension `ms-vscode.powershell` failed:  Cannot read property 'packageJSON' of undefined
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
extensionService.ts:1009 
-===-Activating extension 'ms-vscode.powershell' failed: Cannot read property 'packageJSON' of undefined.
E._logMessageInConsole @ extensionService.ts:1009
E._logOrShowMessage @ extensionService.ts:1023
e.$localShowMessage @ mainThreadExtensionService.ts:32
t._doInvokeHandler @ rpcProtocol.ts:442
t._invokeHandler @ rpcProtocol.ts:427
t._receiveRequest @ rpcProtocol.ts:344
t._receiveOneMessage @ rpcProtocol.ts:274
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
console.ts:136 
-===-[Extension Host] Here is the error stack:  TypeError: Cannot read property 'packageJSON' of undefined
	at Object.<anonymous> (C:\Users\eguch01\.vscode\extensions\ms-vscode.powershell-1.12.0\out\src\features\GenerateBugReport.js:10:69)
	at Object.<anonymous> (C:\Users\eguch01\.vscode\extensions\ms-vscode.powershell-1.12.0\out\src\features\GenerateBugReport.js:106:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:268)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:563)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (C:\Users\eguch01\.vscode\extensions\ms-vscode.powershell-1.12.0\out\src\main.js:20:29)
	at Object.<anonymous> (C:\Users\eguch01\.vscode\extensions\ms-vscode.powershell-1.12.0\out\src\main.js:164:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:268)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:563)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:31:146)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:625:58
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:625:170)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:623:929)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:621:760)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:293:359)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:292:936
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:292:911)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:293:85
	at n.Class.define.cancel.then (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:517)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:293:59)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:291:125)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:622:139)
	at t.$activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:626:646)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by rjmholt** [comment]
That crash looks like it's coming from here:

https://github.com/PowerShell/vscode-powershell/blob/5a16fe01836182b995c1cd6004e2cd5d75881315/src/features/GenerateBugReport.ts#L13

If it's just the casing of the variable, it should be easy to fix.

Is this consistently happening @eguch-occ?

The strange part is that if the problem is as suggested above, we'd expect everyone to hit it. It may lie downstream of another issue perhaps.

**Comment by eguch-occ** [comment]
This started happening to me 4/1. 
I am unable to load the extension, at all. 
I also just installed the extension on a new machine via the VSIX file downloaded form the marketplace. This machine has never had any version of the extension installed until today and in this method. It is experiencing the same behavior. 
Extension never loads and i get the same errors in the console logs.

**Comment by rjmholt** [comment]
One thing you might be able to try quickly:

- Open `~\.vscode\extensions\ms-vscode.powershell-1.12.0\out\src\features\GenerateBugReport.js` in a text editor (VSCode works, but notepad should also be fine).
- Change line 9 from `const extensionId = "ms-vscode.PowerShell";` to `const extensionId = "ms-vscode.powershell";`
- Restart VSCode, try loading the PowerShell extension

**Comment by rkeithhill** [comment]
This - `1.28.2` is also an older version of VSCode.  Can you update VSCode to 1.32.3 and see if the extension behaves better?

**Comment by rjmholt** [comment]
> This - 1.28.2 is also an older version of VSCode. Can you update VSCode to 1.32.3 and see if the extension behaves better?

Ah! Yes, try this first. We can only support the current and previous version of VSCode.

**Comment by eguch-occ** [comment]
I am assuming the extension will operate properly on latest version. 
I will try the updating of VSCode, if and when i can.
However, we are frozen on this version because of existing security requirements :-1: 

In the meantime, I will test the changes recommended above.

**Comment by eguch-occ** [comment]
Based on my restrictions and the change in the extension breaking on my version, I will look to install an older version of the plugin. That way, this won't be a problem, unless you are me :)

**Comment by eguch-occ** [comment]
going back to version 1.11.0 installed from .vsix file resolved my issue. Thank you.
