### ISSUE TITLE
Parameter name: Position 72:44 is outside of the column range of 1 to 24.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1926]
### System Details

System Details Output
```
### VSCode version: 1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64

### VSCode extensions:
aaron-bond.better-comments@2.0.3
aeschli.vscode-css-formatter@1.0.1
alefragnani.project-manager@10.5.1
atomiks.moonlight@0.8.3
CoenraadS.bracket-pair-colorizer-2@0.0.28
donjayamanne.githistory@0.4.6
eamodio.gitlens@9.6.3
ecmel.vscode-html-css@0.2.0
emmanuelbeziat.vscode-great-icons@2.1.47
esbenp.prettier-vscode@1.9.0
GitHub.vscode-pull-request-github@0.6.0
GlenBuktenica.unicode-substitutions@2.0.1
hdg.live-html-previewer@0.3.0
HookyQR.beautify@1.4.11
ironmansoftware.powershellprotools@4.5.1
jasonlhy.vscode-browser-sync@1.3.1
johnpapa.read-time@0.2.0
johnpapa.vscode-peacock@2.1.1
Kelvin.vscode-sshfs@1.16.2
liximomo.remotefs@0.0.15
mechatroner.rainbow-csv@1.0.0
monokai.theme-monokai-pro-vscode@1.1.13
ms-vscode.powershell@1.12.1
ms-vscode.powershell-preview@2.0.2
ms-vsts.team@1.149.2
PKief.material-icon-theme@3.7.0
sdras.night-owl@1.1.3
Shan.code-settings-sync@3.2.9
shd101wyy.markdown-preview-enhanced@0.3.13
softwaredotcom.swdc-vscode@0.15.1
WakaTime.vscode-wakatime@2.0.7
yzhang.markdown-all-in-one@2.2.0
Zignd.html-css-class-completion@1.18.0


### PSES version: 1.12.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

I am experiencing a problem with... crashing.

```
#-- Waiting for EditorServicesHost to complete execution ---------------------
VERBOSE: ERRORS caught while waiting for EditorServicesHost to complete execution
VERBOSE: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
VERBOSE: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.
VERBOSE: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.

Specified argument was out of the range of valid values.
Parameter name: Position 72:44 is outside of the column range of 1 to 24.
   at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
   at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
   at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
   at System.Threading.Tasks.Task.Execute()
PS>$global:?
```

#### Expected Behaviour

Not crashing.

#### Actual Behaviour

Crashes.

### Attached Logs

[1556358610-46643668-d597-4dca-893b-c5afaecd497f1556358580575.zip](https://github.com/PowerShell/vscode-powershell/files/3123741/1556358610-46643668-d597-4dca-893b-c5afaecd497f1556358580575.zip)

Related:

https://github.com/PowerShell/vscode-powershell/issues/1561
https://github.com/PowerShell/vscode-powershell/issues/1191

**Comment by SydneyhSmith** [comment]
@PrzemyslawKlys thanks for reporting this as always! We are going to track this issue in #1561 since it is the same issue
