### ISSUE TITLE
PowerShell Editor Services is terminating due to an unhandled exception

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/vscode-powershell#1933]
### System Details
System Details Output
```
### VSCode version: 1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64

### VSCode extensions:
eamodio.gitlens@9.6.3
mauve.terraform@1.3.9
ms-azuretools.vscode-azureterraform@0.2.3
ms-vscode.azure-account@0.8.2
ms-vscode.azurecli@0.4.5
ms-vscode.powershell@1.12.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.15063.1689
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1689
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The integrated PS editor fails to start. In the Code window, buttom right, is the message:
`Starting PowerShell...`

If I try and run a script via F5, or Debug > Start Debugging, the error is:
```
Cannot debug or run a PowerShell script until the PowerShell session has started. Wait for the PowerShell session to finish starting and try again.
```
![image](https://user-images.githubusercontent.com/26305145/56898991-452b2f80-6a8a-11e9-9dc9-b60c65581dd5.png)

The script is `Get-Process` which works fine in the PS terminal.

I have waiting 2+ hours, uninstalled Code and deleted %UserProfile%\.vscode, reinstalled.

#### Expected Behaviour

It starts in a timely manner.
Tell me the full path and source of what file it is looking for on D:.

#### Actual Behaviour

The logs seem to suggest Code is looking for something in D:. My PC does not have a D:, which, I guess, is what is making it throw its toys out the pram:

```
2019-04-29 14:36:25.534 [ERROR] tid:10 in 'OnListenTaskCompleted' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: line 391
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.Management.Automation.DriveNotFoundException: Cannot find drive. A drive with the name 'd' does not exist.
       at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
       at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
       at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<SetWorkingDirectory>d__65.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
```

Code / PS did work on this machine. I do not have a `$profile` set on this PC. 

### Attached Logs
[VSCodeIssues.zip](https://github.com/PowerShell/vscode-powershell/files/3127568/VSCodeIssues.zip)

**Comment by arcotek-ltd** [comment]
To be honest, whilst collecting the logs, I noticed a reference to D:, that was actually in a `.code-workspace`. Rightly or wrongly, I share my workspaces between computers, via OneDrive / Google Drive, and one PC happens to have a D:. 

Although I have now fixed my issue, I've spent a considerable amount of time trying to work out what the cause was, before submitting this issue and continued to log the issue as it may help others and I hope:

Before you (@Microsoft) close this ticket, perhaps you would consider handling workspaces differently. I believe, at the very minimum, the error message needs to be more meaningful. For instance, if you'd provided the whole path, I would have realised in a heartbeat what the issue was. Further more, something in a workspace should not be able to impact PowerShell extension to such a degree. I would only expect to be aware of a problem when I started to attempt to use files in the folder that was referencing D:. 

Thanks

**Comment by rjmholt** [comment]
Hi @arcotek-ltd, thanks for opening an issue.

Can you share more information on the `.code-workspace` you mentioned? Is this a file?

It looks like this is a bug in the PowerShell extension; a reference to a drive that doesn't exist shouldn't cause a crash.

The problem with the error message is that the PowerShell extension is a client to the PowerShellEditorServices server. In this case the server crashed and the client is left guessing as to why. For other errors we are able to display good error messages, but for unexpected faults like this the logs come into play.

If you can give us a little bit more information about where the reference to the `D:\` path was, we should be able to get it fixed.

**Comment by arcotek-ltd** [comment]
Hi @rjmholt,

Yes. `.code-workspace` relates to the file where VS Code saves its settings in a "workspace", such as the local path to one or more repo's pulled from Git. In my case, I have several .code-workspace files, relating to the customer and / or PC I am using. Hence storing them in OneDrive / GoogleDrive.

The following is the example contents of `contoso.code-workspace`:
```
{
	"folders": [
		{
			"name": "tagging",
			"path": "d:\\Users\\John\\Source\\Repo\\Contoso\\tagging"
		},
		{
			"name": "tf-test",
			"path": "C:\\Users\\someuser\\Source\\Repo\\Contoso\\tf-test"
		},
		{
			"name": "b.itsinfra.demo.azure.vm.small",
			"path": "C:\\Users\\someuser\\Source\\b.itsinfra.demo.azure.vm.small"
		},
		{
			"name": "Contoso.infrastructure.devops",
			"path": "C:\\Users\\someuser\\Source\\Repo\\Contoso\\Contoso.infrastructure.devops"
		},
		{
			"name": "arc.service.os",
			"path": "C:\\Users\\someuser\\Source\\Repo\\Contoso\\arc.service.os"
		}
	],
	"settings": {}
}
```
![image](https://user-images.githubusercontent.com/26305145/56964962-75430300-6b5c-11e9-8e41-f1ecc0b0e290.png)
A partial screen shot of the workspace and the `tagging` folder.

In this case, the folder `tagging` is referencing a folder (repo) on `D:`, which doesn't exist on the machine where I experienced the issue.

I hope this gives you the info you were looking for. If you need more info, please shout.

Many thanks

W.

**Comment by rjmholt** [comment]
Ok, a brief investigation indicates that this happens here:

https://github.com/PowerShell/PowerShellEditorServices/blob/edfeddf9ee36021fe8ab273d5c167d4af1e94805/src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs#L218-L223

The initialisation message sent looks like this:

```
2019-04-29 14:11:34.763 [VERBOSE] tid:22 in 'ReadMessage' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs: line 138
    Received Request 'initialize' with id 0
    
    {
      "jsonrpc": "2.0",
      "id": 0,
      "method": "initialize",
      "params": {
        "processId": 18940,
        "rootPath": "d:\\Users\\john\\Source\\Repos\\JCB\\PowerShellModules\\psgit",
        "rootUri": "file:///d%3A/Users/john/Source/Repos/JCB/PowerShellModules/psgit",
        "capabilities": {
          "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
              "documentChanges": true,
              "resourceOperations": [
                "create",
                "rename",
                "delete"
              ],
              "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
              "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
              "dynamicRegistration": true
            },
            "symbol": {
              "dynamicRegistration": true,
              "symbolKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26
                ]
              }
            },
            "executeCommand": {
              "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
          },
          "textDocument": {
            "publishDiagnostics": {
              "relatedInformation": true
            },
            "synchronization": {
              "dynamicRegistration": true,
              "willSave": true,
              "willSaveWaitUntil": true,
              "didSave": true
            },
            "completion": {
              "dynamicRegistration": true,
              "contextSupport": true,
              "completionItem": {
                "snippetSupport": true,
                "commitCharactersSupport": true,
                "documentationFormat": [
                  "markdown",
                  "plaintext"
                ],
                "deprecatedSupport": true,
                "preselectSupport": true
              },
              "completionItemKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25
                ]
              }
            },
            "hover": {
              "dynamicRegistration": true,
              "contentFormat": [
                "markdown",
                "plaintext"
              ]
            },
            "signatureHelp": {
              "dynamicRegistration": true,
              "signatureInformation": {
                "documentationFormat": [
                  "markdown",
                  "plaintext"
                ]
              }
            },
            "definition": {
              "dynamicRegistration": true
            },
            "references": {
              "dynamicRegistration": true
            },
            "documentHighlight": {
              "dynamicRegistration": true
            },
            "documentSymbol": {
              "dynamicRegistration": true,
              "symbolKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26
                ]
              },
              "hierarchicalDocumentSymbolSupport": true
            },
            "codeAction": {
              "dynamicRegistration": true,
              "codeActionLiteralSupport": {
                "codeActionKind": {
                  "valueSet": [
                    "",
                    "quickfix",
                    "refactor",
                    "refactor.extract",
                    "refactor.inline",
                    "refactor.rewrite",
                    "source",
                    "source.organizeImports"
                  ]
                }
              }
            },
            "codeLens": {
              "dynamicRegistration": true
            },
            "formatting": {
              "dynamicRegistration": true
            },
            "rangeFormatting": {
              "dynamicRegistration": true
            },
            "onTypeFormatting": {
              "dynamicRegistration": true
            },
            "rename": {
              "dynamicRegistration": true,
              "prepareSupport": true
            },
            "documentLink": {
              "dynamicRegistration": true
            },
            "typeDefinition": {
              "dynamicRegistration": true
            },
            "implementation": {
              "dynamicRegistration": true
            },
            "colorProvider": {
              "dynamicRegistration": true
            },
            "foldingRange": {
              "dynamicRegistration": true,
              "rangeLimit": 5000,
              "lineFoldingOnly": true
            }
          }
        },
        "trace": "off",
        "workspaceFolders": [
          {
            "uri": "file:///d%3A/Users/john/Source/Repos/ARCOTEK/PowerShellModules/psgit",
            "name": "psgit"
          },
          {
            "uri": "file:///c%3A/Users/someuser/Source/Repo/Arcotek/tf-test",
            "name": "tf-test"
          },
          {
            "uri": "file:///c%3A/Users/someuser/Source/b.itsinfra.demo.azure.vm.small",
            "name": "b.itsinfra.demo.azure.vm.small"
          },
          {
            "uri": "file:///c%3A/Users/someuser/Source/Repo/Arcotek/arcotek.infrastructure.devops",
            "name": "arcotek.infrastructure.devops"
          },
          {
            "uri": "file:///c%3A/Users/someuser/Source/Repo/Arcotek/arc.service.os",
            "name": "arc.service.os"
          }
        ]
      }
    }
```

Basically VSCode is sending an `initialize` message with the first path in your configuration, so it doesn't really think about a fallback if it doesn't exist.

I've submitted a simple fix that prevents the crash, but because VSCode is sending a path that doesn't exist to the extension on startup, you won't get the same experience as if the path were valid.

My recommendation would be to try reordering the paths you have configured so that a path that exists comes first.

**Comment by arcotek-ltd** [comment]
Hi @rjmholt,

Thanks for working on this.

I agree that having a path that doesn't exist it not ideal and reordering them would be better.

I would expect, trying to access folders from the workspace that don't exist would cause issues, but this is better than PowerShell not loading in VSCode.

I actually create a virtual drive `R:` which points to my repo directory which is create as my `$PSProfile` loads, which solves this issue as all computers have an `R:`. It also get's around Windows problem with long path names. Obviously, the `$PSProfile` has to load and create the `R:` - and in this instance, my `$PSProfile` wasn't set up.

Thanks again.
