### ISSUE TITLE
ERRORS caught while waiting for EditorServicesHost to complete execution

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2101]
Issue Description
=====

I am experiencing a problem with... crashing during debug

```
Hit Line breakpoint on 'C:\Users\przemyslaw.klys\OneDrive - Evotec\Support\GitHub\Testimo\Ignore\Test-DFSR.ps1:36'

[DBG]: PS C:\Users\przemyslaw.klys\OneDrive - Evotec\Support\GitHub\Testimo> VERBOSE: ERRORS caught while waiting for EditorServicesHost to complete execution
VERBOSE: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
VERBOSE: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.

VERBOSE: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.

Unable to cast COM object of type 'System.__ComObject' to interface type 'IDirectorySearch'. This operation failed because the QueryInterface call on the COM 
component for the interface with IID '{109BA8EC-92F0-11D0-A790-00C04FD8D5A8}' failed due to the following error: No such interface supported (Exception from  
HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at System.DirectoryServices.Interop.UnsafeNativeMethods.IDirectorySearch.GetFirstRow(IntPtr hSearchResult)
   at System.DirectoryServices.SearchResultCollection.ResultsEnumerator.MoveNext()
   at Microsoft.PowerShell.EditorServices.VariableDetails.GetChildren(Object obj, ILogger logger)
   at Microsoft.PowerShell.EditorServices.VariableDetails.GetChildren(ILogger logger)
   at Microsoft.PowerShell.EditorServices.DebugService.GetVariables(Int32 variableReferenceId)
   at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<HandleVariablesRequest>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
   at System.Threading.Tasks.Task.Execute()
```

Attached Logs
=====

[1563912556-485022fa-2cc3-4af1-8a8f-82fac007bb4f1563912552740.zip](https://github.com/PowerShell/vscode-powershell/files/3423932/1563912556-485022fa-2cc3-4af1-8a8f-82fac007bb4f1563912552740.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.36.1|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.4.1|
|code-spell-checker|streetsidesoftware|1.7.17|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.1|
|html-css-class-completion|Zignd|1.19.0|
|live-html-previewer|hdg|0.3.0|
|markdown-all-in-one|yzhang|2.4.2|
|markdown-preview-enhanced|shd101wyy|0.4.3|
|markdown-shortcuts|mdickin|0.11.0|
|material-icon-theme|PKief|3.8.1|
|powershell|ms-vscode|2019.5.0|
|project-manager|alefragnani|10.5.2|
|theme-monokai-pro-vscode|monokai|1.1.13|
|vscode-html-css|ecmel|0.2.0|
|vscode-markdownlint|DavidAnson|0.28.0|
|vscode-pull-request-github|GitHub|0.9.1|
|vscode-wakatime|WakaTime|2.2.0|
|vscode-yaml|redhat|0.4.1|
|wordcount|ms-vscode|0.1.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by SydneyhSmith** [comment]
@PrzemyslawKlys thanks for opening this, the stack trace is very helpful...it would be great to know what you were debugging when this crash occurred and if you have a consistent repro of this. Thanks!!

**Comment by PrzemyslawKlys** [comment]
```PowerShell
$currentDomain =(Get-ADDomainController).hostname

$defaultNamingContext = (([ADSI]"LDAP://$currentDomain/rootDSE").defaultNamingContext)
$searcher = New-Object DirectoryServices.DirectorySearcher
$searcher.Filter = "(&(objectClass=computer)(dNSHostName=$currentDomain))"
$searcher.SearchRoot = "LDAP://" + $currentDomain + "/OU=Domain Controllers," + $defaultNamingContext
$dcObjectPath = $searcher.FindAll() | ForEach-Object{$_.Path}

# DFSR
$searchDFSR = New-Object DirectoryServices.DirectorySearcher
$searchDFSR.Filter = "(&(objectClass=msDFSR-Subscription)(name=SYSVOL Subscription))"
$searchDFSR.SearchRoot = $dcObjectPath
$dfsrSubObject = $searchDFSR.FindAll()

if ($dfsrSubObject -ne $null){

    [pscustomobject]@{
        "SYSVOL Replication Mechanism"= "DFSR"
        "Path:"= $dfsrSubObject|ForEach-Object{$_.Properties."msdfsr-rootpath"}
    }

}

# FRS
$searchFRS = New-Object DirectoryServices.DirectorySearcher
$searchFRS.Filter = "(&(objectClass=nTFRSSubscriber)(name=Domain System Volume (SYSVOL share)))"
$searchFRS.SearchRoot = $dcObjectPath
$frsSubObject = $searchFRS.FindAll()

if($frsSubObject -ne $null){

    [pscustomobject]@{
        "SYSVOL Replication Mechanism" = "FRS"
        "Path" = $frsSubObject|ForEach-Object{$_.Properties.frsrootpath}
    }

}
```

Set breakpoints on line 15 and 30. When line 15 hits simply go to debugging tab. Then click on the variable that you stopped on. For me it's dfsrSubObject. It crashes at that moment. I guess when trying to expand it. 

![image](https://user-images.githubusercontent.com/15063294/62004178-e9705100-b121-11e9-9abb-289dc785b0a8.png)

Notice the progress bar on the left next to the variable. When I go thru the list after a crash, more objects get that constant progress bar. Most likely you will need an AD module to reproduce it thou, but maybe without it, it will be possible.

I was trying to debug why `if($frsSubObject -ne $null){` when reverted to `if($null -ne $frsSubObject){` displays `PSCustomObject` where the first version doesn't.

**Comment by rjmholt** [comment]
@adityapatwardhan it looks like this is some kind of COM inheritance problem:

```
Unable to case COM object of type 'System.__ComObject' to interface type 'IDirectorySearch'...
```

Does that look familiar?
