### ISSUE TITLE
Intellisense autocomplete not working with Powershell (module version 0.6.1)

### ISSUE THREAD

**Issue by lc9er** [PowerShell/vscode-powershell#215]
VSCode Version: 1.2.1
Powershell Module Version: 0.6.1
OS Version: Windows 10

Steps to Reproduce:

1. Edit a ps1 file, verify language set as 'Powershell'. 
2. Attempt to autocomplete a cmdlet like 'get-host', by typing 'get-'. No suggestions pop up.
3. Attempt to manually get suggestions by typing Ctrl-Space. VS Code replies "No suggestions"

Occasionally, I will receive Intellisense suggestions for one or two cmdlets, then it will stop working.

**Comment by nerdfactor** [comment]
Same Problem here. Logfile says:

0.06.2016 08:28:43 [ERROR] - Method "CurrentDomain_UnhandledException" at line 178 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    FATAL UNHANDLED EXCEPTION:
    
    System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ArgumentException: "^\s*g++.exe\s+\[" wird analysiert - Geschachtelter Quantifizierer +.
       bei System.Text.RegularExpressions.RegexParser.ScanRegex()
       bei System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
       bei System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
       bei Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.CreateCompletionItem(CompletionDetails completionDetails, BufferRange completionRange, Int32 sortIndex)
       bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       bei Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCompletionRequest>d__22.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       bei System.Threading.Tasks.Task.Execute()
       --- Ende der internen Ausnahmestapelüberwachung ---
       --- Ende der internen Ausnahmestapelüberwachung ---
       bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       bei Microsoft.PowerShell.EditorServices.Host.Program.Main(String[] args)
    ---> (Interne Ausnahme #0) System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ArgumentException: "^\s*g++.exe\s+\[" wird analysiert - Geschachtelter Quantifizierer +.
       bei System.Text.RegularExpressions.RegexParser.ScanRegex()
       bei System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
       bei System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
       bei Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.CreateCompletionItem(CompletionDetails completionDetails, BufferRange completionRange, Int32 sortIndex)
       bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       bei Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCompletionRequest>d__22.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       bei System.Threading.Tasks.Task.Execute()
       --- Ende der internen Ausnahmestapelüberwachung ---
    ---> (Interne Ausnahme #0) System.ArgumentException: "^\s*g++.exe\s+\[" wird analysiert - Geschachtelter Quantifizierer +.
       bei System.Text.RegularExpressions.RegexParser.ScanRegex()
       bei System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
       bei System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
       bei Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.CreateCompletionItem(CompletionDetails completionDetails, BufferRange completionRange, Int32 sortIndex)
       bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       bei Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCompletionRequest>d__22.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       bei System.Threading.Tasks.Task.Execute()<---
    <---

**Comment by rkeithhill** [comment]
Thanks for the stack trace. Looks like a case of not regex encoding the completion item text before throwing it at regex. The + chars in g++.exe are getting interpreted as metacharacters. I thought I had fixed all spots where we did this but I must have missed some.

**Comment by rkeithhill** [comment]
@nerdfactor Are you sure you're using the 0.6.1 version of the extension?  The failure mechanism I believe you are seeing was fixed in early February. The code, that corresponds to the error message is:
```csharp
!Regex.IsMatch(completionDetails.ToolTipText, 
    @"^\s*" + escapedToolTipText + @"\s+\["))
```
The escapedToolTipText for `g++.exe` comes out as `g\+\+\.exe` but error message you see doesn't show the metacharacters as escaped:
```
System.ArgumentException: "^\s*g++.exe\s+\[" 
```
Note the `+` and `.` metacharacters in `g++.exe` are not escaped.  This makes me think VSCode is finding/loading an older version of the extension on your machine.

**Comment by nerdfactor** [comment]
Manifest file states:

<Identity Language="en-US" Id="PowerShell" Version="0.6.1" Publisher="ms-vscode"/>

The logfile starts with:

30.06.2016 11:25:38 [NORMAL] - Method "Main" at line 145 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host v0.6.1.356 starting (pid 1768)...
    
      Host application details:
    
        Name: Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version: 0.6.1

so everything looks like Version 0.6.1.
The error only happens on my Windows 7 Machine at work that has Windows Management Framework 5 installed. On my Windows 10 Machine at home everything works fine. So it may be a Windows 7 related issue.

**Comment by lc9er** [comment]
Here's my log file. Looks like the same error:

```
7/1/2016 9:14:25 AM [NORMAL] - Method "Main" at line 145 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host v0.6.1.356 starting (pid 19372)...
    
      Host application details:
    
        Name: Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version: 0.6.1

7/1/2016 9:14:25 AM [NORMAL] - Method "Initialize" at line 186 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    PowerShell runtime version: 5.0.10240.16384

7/1/2016 9:14:26 AM [NORMAL] - Method "Main" at line 165 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host started!

7/1/2016 9:17:13 AM [ERROR] - Method "CurrentDomain_UnhandledException" at line 178 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    FATAL UNHANDLED EXCEPTION:
    
    System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: parsing "^\s*g++.exe\s+\[" - Nested quantifier +.
       at System.Text.RegularExpressions.RegexParser.ScanRegex()
       at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
       at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
       at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.CreateCompletionItem(CompletionDetails completionDetails, BufferRange completionRange, Int32 sortIndex)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCompletionRequest>d__22.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.WaitForExit()
       at Microsoft.PowerShell.EditorServices.Host.Program.Main(String[] args)
    ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ArgumentException: parsing "^\s*g++.exe\s+\[" - Nested quantifier +.
       at System.Text.RegularExpressions.RegexParser.ScanRegex()
       at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
       at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
       at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.CreateCompletionItem(CompletionDetails completionDetails, BufferRange completionRange, Int32 sortIndex)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCompletionRequest>d__22.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentException: parsing "^\s*g++.exe\s+\[" - Nested quantifier +.
       at System.Text.RegularExpressions.RegexParser.ScanRegex()
       at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
       at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
       at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.CreateCompletionItem(CompletionDetails completionDetails, BufferRange completionRange, Int32 sortIndex)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCompletionRequest>d__22.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
    <---
    
```

**Comment by rkeithhill** [comment]
@nerdfactor and @lc9er thanks for confirming the version.

**Comment by rkeithhill** [comment]
@Ic9er Are you on Windows 7 as well?  Also, what text did you type before trying to get auto-completion?

**Comment by lc9er** [comment]
I am on Windows 10.

I get this when typing, "get-", or "show-". Any cmdlet it seems.

**Comment by rkeithhill** [comment]
@lc9er Where is `g++.exe` installed on your system?  `Get-Command g++.exe | Format-List` should show you the location.

**Comment by lc9er** [comment]
C:\strawberry\c\bin

It was installed as part of the Strawberry Perl Chocolatey package.

**Comment by andreamaruccia** [comment]
I am also having problems with Intellisense and variables autocompletation. Is there another version of the extension you can advise to install? It it possible to install an older version of the extension?

**Comment by daviwil** [comment]
I don't believe an older version of the extension is going to help with this issue.  Did your problem start after the 1.4.0 release of VS Code got installed?  If so, let's continue the discussion over on this issue: https://github.com/PowerShell/vscode-powershell/issues/231

**Comment by rkeithhill** [comment]
Ah it looks like I fixed this back in May but it never made it into a release.  Is that correct @daviwil?  If so, this should be fixed with the 0.6.2. release coming out shortly.

**Comment by daviwil** [comment]
Yep, sorry for the delay on getting that out!  I think at the time I was planning on putting out 0.6.2 but delayed it for some reason and never got back around to it...  New release with the fix will be out today or tomorrow.

**Comment by rkeithhill** [comment]
No problem. I thought I was going crazy for a bit, looking at the stack trace and the code thinking - no way this can be happening.  :-)

**Comment by daviwil** [comment]
Just shipped a new update to the extension with a fix for this issue!

**Comment by lc9er** [comment]
Works! Thanks for the fix.

**Comment by andreamaruccia** [comment]
Works! Nice job!
