### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by fatherofinvention** [PowerShell/vscode-powershell#2222]
Issue Type: <b>Bug</b>

PowerShell Integrated Console does not load. Error in the EditorServices.log:
---------------------------------------------------------------------------

2019-10-02 10:22:10.178 [ERROR] tid:6 in 'ListenForConnection' D:\a\1\s\src\PowerShellEditorServices.Protocol\MessageProtocol\Channel\NamedPipeServerListener.cs: line 155
    Exception: An unhandled exception occurred while listening for a named pipe client connection
    
    System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
    
    File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer, ILogger logger)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerChannel.Initialize(IMessageSerializer messageSerializer)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.ServerListenerBase`1.OnClientConnect(TChannel channel)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.<<ListenForConnection>b__9_0>d.MoveNext()
    

Extension version: 2019.9.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fatherofinvention** [comment]
Reinstalled PowerShell via homebrew. Original version was v6.0.2. New version is: v6.2.3. Issue has been resolved. Closing.
