### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2240]
Issue Description
=====

I am experiencing a problem with... crashing. Basically I was removing some parameter value from a function. During removal extension crashed. 

```
2019-10-12 17:00:49.670 [VERBOSE] tid:27 in 'ResolveFilePath' D:\a\1\s\src\PowerShellEditorServices\Workspace\Workspace.cs: line 505
    Resolved path: c:\Users\przemyslaw.klys\OneDrive - Evotec\Support\GitHub\PSWriteHTML\Public\New-HTMLDiagram.ps1

2019-10-12 17:00:49.671 [ERROR] tid:192 in 'OnListenTaskCompleted' D:\a\1\s\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: line 391
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: Position 6:29 is outside of the column range of 1 to 26.
       at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: Position 6:29 is outside of the column range of 1 to 26.
       at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()<---
    

2019-10-12 17:00:49.672 [ERROR] tid:192 in 'ProtocolEndpoint_UnhandledException' D:\a\1\s\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 448
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.

2019-10-12 17:00:49.848 [ERROR] tid:1 in 'PopRunspace' D:\a\1\s\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 2109
    Caller attempted to pop a runspace when no runspaces are on the stack.

2019-10-12 17:00:49.848 [ERROR] tid:1 in 'PopRunspace' D:\a\1\s\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 2109
    Caller attempted to pop a runspace when no runspaces are on the stack.


```

[1570824023-ed6e92cd-a9a9-4c75-ba9b-5d4041f453a01570823768017.zip](https://github.com/PowerShell/vscode-powershell/files/3720823/1570824023-ed6e92cd-a9a9-4c75-ba9b-5d4041f453a01570823768017.zip)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.39.1|
| PowerShell Extension Version | 2019.9.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.0|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.4.3|
|gitlens|eamodio|10.1.1|
|html-css-class-completion|Zignd|1.19.0|
|live-html-previewer|hdg|0.3.0|
|markdown-all-in-one|yzhang|2.5.0|
|markdown-preview-enhanced|shd101wyy|0.4.3|
|markdown-shortcuts|mdickin|0.11.0|
|material-icon-theme|PKief|3.9.1|
|powershell|ms-vscode|2019.9.0|
|project-manager|alefragnani|10.8.0|
|theme-monokai-pro-vscode|monokai|1.1.14|
|vscode-html-css|ecmel|0.2.3|
|vscode-markdownlint|DavidAnson|0.30.2|
|vscode-wakatime|WakaTime|2.2.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by rjmholt** [comment]
Looks like a bug similar to others in the ScriptFile management backend. Once other work has been done on the omnisharp port, I'll look into this. Time we reviewed the way we handle files behind the scenes perhaps.
