### ISSUE TITLE
Parsing error on DSC configuration is incorrect on OSX

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#263]
I see this error on a DSC configuration of mine, but I can compile MOFs from this config just fine. I'm on OSX. Is this because CIM is not on OSX?  If so, DSC parsing should be disabled altogether.

System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Collection`1 errors)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token configurationToken)

http://www.screencast.com/t/Ce0LkPDhZF

**Comment by MrsMad** [comment]
System.IO.Path is incorrect, use System.I.O.Path

**Comment by adbertram** [comment]
I don't have this reference anywhere in the DSC configuration.

**Comment by daviwil** [comment]
I haven't seen this issue specifically but I've seen others like it related to DSC, see this thread on Twitter:

https://twitter.com/andschwa/status/767799188109221889

It might be worth filing an issue on the [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell/issues) repo to see if there's a bug there.

**Comment by adbertram** [comment]
I don't get this error in the ISE or PowerShell Studio on Windows.

**Comment by daviwil** [comment]
It's definitely caused by the open-source build of PowerShell.  That's why I think it'd make sense to file a bug on PowerShell/PowerShell to see if it's a bug or just a missing dependency.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.

**Comment by rjmholt** [comment]
Looks like this was a bug in the PowerShell parser itself. Hopefully it's been corrected in PowerShell (very likely) but if not, please open an issue in the [PowerShell repo](https://github.com/PowerShell/PowerShell)
