### ISSUE TITLE
Integrated console hangs during formatting

### ISSUE THREAD

**Issue by v2kiran** [PowerShell/vscode-powershell#2666]
### System Details

System Details Output
```
- Operating system name and version : windows 10
- VS Code version: 1.44.2
- PowerShell extension version: v2020.4.0
- psversion
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with the integrated console getting hung

#### Expected Behaviour

Format the powershell file on save without errors

#### Actual Behaviour

displays the following message: 
![error](https://i.ibb.co/YcHYwrs/vscode.png)

### details

example.ps1 is a ps script with about 60 lines of code.
vscode - format on save is turned on.

after the formatting message, intellisense stops and we cannot execute code using F8 anymore. The  workaround is to restart the console but this keeps happening every few minutes now.

**Comment by TylerLeonhardt** [comment]
> intellisense stops and we cannot execute code using F8 anymore

These things wont work until Formatting is done because formatting can change the state of the file you're looking at.

I think the real question is:
* Why is formatting taking so long for a 60 line file... Can you share this file with us potentially?
* or... could formatting be waiting for other things to finish? [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on. Remember to include the payload logs.

**Comment by codykonior** [comment]
I'm getting tonnes of these too on every file I touch and queuing up dozens of the dialog boxes, on both the normal and preview versions of the extension.

The thing is that the dialog has a "configure" option which takes me to a setting box which is disabled under all three categories (user, workspace, powershell). So the setting isn't even being honoured properly.

![2020-04-29_14-36-06](https://user-images.githubusercontent.com/12396330/80571574-6d4bc680-8a2f-11ea-8a5e-937ea3a8443e.png)

**Comment by TylerLeonhardt** [comment]
@codykonior can you also answer my questions above?

Also, do you maybe have a workspace level setting with "format on save" turned on?

**Comment by codykonior** [comment]
No, as I said it’s not enabled in any of the tabs (user, workspace or powershell). 

Can’t provide logs at this stage because it’s work stuff and I’d have to spend ages parsing the logs looking for specific stuff. But it should be possible for someone to work out why that setting isn’t working.

**Comment by TylerLeonhardt** [comment]
If that's the case than the issue on the setting not being honored should go into the https://github.com/Microsoft/vscode repo since the actual product handles when that format is fired.

We'll leave this open for someone to answer my questions above but if format on save is firing when it shouldn't, I can't see that being an issue for the PowerShell extension.

**Comment by v2kiran** [comment]
I was able to turn on Diagnostic logging :
`"powershell.developer.editorServicesLogLevel": "Diagnostic"`

but it seems the below setting is not recognized:
`"powershell editor services.trace.server":"verbose"`

are the instructions for the payload logs still valid?

**Comment by TylerLeonhardt** [comment]
Yeah the setting isn't recognized but it works.

**Comment by v2kiran** [comment]
Logs attached.
I will attach the payload logs when the issue occurs next.
[vscode logs.zip](https://github.com/PowerShell/vscode-powershell/files/4556507/vscode.logs.zip)

**Comment by v2kiran** [comment]
[payload.zip](https://github.com/PowerShell/vscode-powershell/files/4570036/payload.zip)

Note: these days intellisense stops long before i even get the format message.

**Comment by mbergal-idx** [comment]
I have the same problem, here is output tab messages:
```
[Error - 1:09:52 AM] OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter: Failed to handle notification textDocument/signatureHelp - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.CommandHelpers.GetCommandInfoAsync(String commandName, PowerShellContextService powerShellContext) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\Utilities\CommandHelpers.cs:line 105
   at Microsoft.PowerShell.EditorServices.Services.SymbolsService.FindParameterSetsInFileAsync(ScriptFile file, Int32 lineNumber, Int32 columnNumber, PowerShellContextService powerShellContext) in D:\a\1\s\src\PowerShellEditorServices\Services\Symbols\SymbolsService.cs:line 388
   at Microsoft.PowerShell.EditorServices.Handlers.SignatureHelpHandler.Handle(SignatureHelpParams request, CancellationToken cancellationToken) in D:\a\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\SignatureHelpHandler.cs:line 96
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
[Error - 1:09:52 AM] Request textDocument/signatureHelp failed.
  Message: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.CommandHelpers.GetCommandInfoAsync(String commandName, PowerShellContextService powerShellContext) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\Utilities\CommandHelpers.cs:line 105
   at Microsoft.PowerShell.EditorServices.Services.SymbolsService.FindParameterSetsInFileAsync(ScriptFile file, Int32 lineNumber, Int32 columnNumber, PowerShellContextService powerShellContext) in D:\a\1\s\src\PowerShellEditorServices\Services\Symbols\SymbolsService.cs:line 388
   at Microsoft.PowerShell.EditorServices.Handlers.SignatureHelpHandler.Handle(SignatureHelpParams request, CancellationToken cancellationToken) in D:\a\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\SignatureHelpHandler.cs:line 96
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
  Code: -32602 
```

**Comment by SydneyhSmith** [comment]
Thanks everyone, we  are going to dupe this issue to #2627
