### ISSUE TITLE
Unrelated Text in PowerShell PS1 File Being Deleted After Copy and Pasting Text

### ISSUE THREAD

**Issue by DesertBear** [PowerShell/vscode-powershell#2675]
### System Details

System Details Output
```
### VSCode version: 1.44.0 2aae1f26c72891c399f860409176fe435a154b13 x64

### VSCode extensions:       
ms-vscode.powershell@2020.4.0


### PSES version: 2.1.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

Sporadically, when copy and pasting text from one part of a PowerShell PS1 script to another part in the same script, VS Code deletes other unrelated text in the script.  It's pretty bad because if you don't happen to notice what it has done, the file will be saved with those errors.

It's difficult to reliably reproduce this issue, as it happens sporadically.

It's not dependent on any one particular file, it can happen in any PS1 file (I only use PowerShell files in VS Code, so can't comment on other file types).

It happens whether using keyboard shortcut keys (CTRL + C, CTRL + V) or the right-click context menu.

After closing VS Code and re-opening the PS1 file, VS Code starts working OK again – copy and pasting works correctly.

It has only started doing it recently (probably in the last few months of so; definitely in 2020).  I don't use any preview versions, only general availability versions of VS Code, PowerShell 7 and the PowerShell Extension.

#### Expected Behaviour

-- It should just copy and paste the text.

#### Actual Behaviour

-- Sporadically, when copy and pasting text from one part of a PowerShell PS1 script to another part in the same script, VS Code deletes other unrelated text in the script.

In the screenshots below, it's deleting certain letters in two lines.  However when undoing and then re-copying and re-pasting, it may delete different letters in those two lines (for example it may say "Press Enter key to ex" instead).

Screenshot A:
![Screenshot A](https://user-images.githubusercontent.com/27423064/80869773-4513d000-8c9a-11ea-951e-589c495e7eda.png)

Screenshot B:
![Screenshot B](https://user-images.githubusercontent.com/27423064/80869779-4c3ade00-8c9a-11ea-97f8-b311b186f350.png)

Screenshot C:
![Screenshot C](https://user-images.githubusercontent.com/27423064/80869785-5066fb80-8c9a-11ea-8194-822b4bc4b9e8.png)

### VS Code Settings

VS Code Settings file:
[settings.zip](https://github.com/PowerShell/vscode-powershell/files/4568194/settings.zip)

**Comment by TylerLeonhardt** [comment]
I can't repro this behavior. Can you try some things?:

* turn off `formatOnPaste`
* Open a non-PowerShell file to see if it repros
* disable the PowerShell extension temporarily

**Comment by DesertBear** [comment]
I'm not sure whether it's the exact issue that I reported above or just similar, however it's possible to reliably reproduce something similar by using two PS1 files with the same filenames.  In this scenario, it does appear to be related to the "FormatOnPaste" setting that you mentioned in your comment.  

– With "FormatOnPaste" off, copy and paste works correctly.
– With "FormatOnPaste" on, copy and paste works starts doing odd things again.

I also observed similar issues with "FormatOnSave" enabled and saving a file as well.

**Video demonstrating the issue (with "FormatOnPaste" enabled):**
[Video.zip](https://github.com/PowerShell/vscode-powershell/files/4569360/Video.zip)

**Files used in video:**
[Files.zip](https://github.com/PowerShell/vscode-powershell/files/4569362/Files.zip)

**Comment by SydneyhSmith** [comment]
Thanks @DesertBear that is helpful...it would be really helpful if you could also attach the payload logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by DesertBear** [comment]
**Log files attached:**
[Log Files.zip](https://github.com/PowerShell/vscode-powershell/files/4583986/Log.Files.zip)

**Comment by TylerLeonhardt** [comment]
Sadly having a hard time reproducing this one... @DesertBear PSScriptAnalyzer was updated recently which has performance gains in the formatter.

Can you try grabbing the latest release of that and seeing if it helps?

Install-Module PSScriptAnalyzer -Force -AllowClobber

**Comment by DesertBear** [comment]
I'm unsure why you are unable to reproduce the issue.  

I've just tested it by installing VS Code (VSCodeSetup-x64-1.44.0.exe), the PowerShell extension for VS Code (PowerShell-2020.4.0.vsix) and PowerShell 7 (PowerShell-7.0.0-win-x64.msi) in a clean instance of Windows Sandbox.  Everything is using the default out-of-box settings (with the exception of enabling "Format On Paste" in the VS Code settings and setting the VS Code terminal to use PowerShell Core as the default Shell).  By following the same steps in the above video, it fails every time in the exact the same way as it does in the video.

I also tried installing just VS Code and the PowerShell extension for VS Code (I.E. not installing PowerShell 7, just using PowerShell 5.1) in a clean instance of Windows Sandbox and it also failed like in the video.

Installing VS Code, the PowerShell extension for VS Code and PowerShell 7 in a clean instance of Windows Sandbox, and then running `Install-Module PSScriptAnalyzer -Force -AllowClobber`, also failed like in the video.


Windows 10 Pro 1909 (18363.778)

**Comment by SydneyhSmith** [comment]
Thanks @DesertBear we are still investigating this but it looks like a sequencing issue based on the stack trace here: 
```
2020-05-05 22:58:09.890 +01:00 [DBG] Starting: Routing Notification textDocument/didChange
2020-05-05 22:58:09.891 +01:00 [DBG] Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
2020-05-05 22:58:09.891 +01:00 [DBG] Resolved path: file:///c:/Users/ABCDEF/Desktop/Test/Test%20Folder/Test%20Script.ps1
2020-05-05 22:58:09.894 +01:00 [FTL] Failed to handle request textDocument/didChange
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Position 9:3 is outside of the column range of 1 to 1.')
   at Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFile.ValidatePosition(Int32 line, Int32 column) in D:\a\1\s\src\PowerShellEditorServices\Services\TextDocument\ScriptFile.cs:line 323
   at Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFile.ApplyChange(FileChange fileChange) in D:\a\1\s\src\PowerShellEditorServices\Services\TextDocument\ScriptFile.cs:line 366
   at Microsoft.PowerShell.EditorServices.Handlers.TextDocumentHandler.Handle(DidChangeTextDocumentParams notification, CancellationToken token) in D:\a\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\TextDocumentHandler.cs:line 51
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteNotification(TDescriptor descriptor, Notification notification, CancellationToken token)
```
We are still having difficulty reproducing this but will try the exact steps/files from the video again (thanks again for providing this)

**Comment by andschwa** [comment]
Re-opening as I see repro info was provided (the label was just not removed), and the bug seems to be a race condition between the formatter being run on paste and other text edits.
