### ISSUE TITLE
Multiple PowerShell Editor Services in Output

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2909]
Issue Description
=====

I am experiencing a problem with...

![image](https://user-images.githubusercontent.com/15063294/90983427-59901700-e56e-11ea-8c09-c5732303cb3c.png)

The majority of them have:
```
[Error - 20:35:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:74:35)
	at c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:2208:28
[Error - 20:35:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:74:35)
	at c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:2208:28
[Error - 20:35:09] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:74:35)
	at c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:2208:28
[Error - 20:35:09] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:74:35)
	at c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.7.0\node_modules\vscode-languageclient\lib\client.js:2208:28

```

Only the last one has data

[1598194129-afdfd4de-6452-4c44-a771-59ce3569b53b1598107482495.zip](https://github.com/PowerShell/vscode-powershell/files/5114298/1598194129-afdfd4de-6452-4c44-a771-59ce3569b53b1598107482495.zip)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.48.1|
| PowerShell Extension Version | 2020.7.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|errorlens|usernamehw|3.2.0|
|format-selection-as-html|adrianwilczynski|2.3.0|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.2|
|line-endings|steditor|1.0.3|
|markdown-all-in-one|yzhang|3.2.0|
|material-icon-theme|PKief|4.2.0|
|open-in-browser|techer|2.0.0|
|powershell-preview|ms-vscode|2020.7.0|
|project-manager|alefragnani|11.2.0|
|run-in-powershell|tobysmith568|1.1.0|
|vscode-markdownlint|DavidAnson|0.36.3|
|vscode-pull-request-github|GitHub|0.19.0|
|vscode-toggle-quotes|BriteSnow|0.3.3|
|vscode-wakatime|WakaTime|4.0.0|
|vscode-yaml|redhat|0.10.0|
|xml|DotJoshJohnson|2.5.1|

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys two other things that might be useful to help debug this: 
- Open the command pallet and find "Developer: Toggle Developer Tools" and then copy the output from the "console" tab
- Choose the Output pane and then use the drop down to select "Log (Extension Host)" and copy the output

**Comment by PrzemyslawKlys** [comment]
Closing until I replicate it. Unfortunately it happened only once.

**Comment by PrzemyslawKlys** [comment]
[consoletab.txt](https://github.com/PowerShell/vscode-powershell/files/5314581/consoletab.txt)

Found it again, this time two sessions

**Comment by SydneyhSmith** [comment]
Thanks again @PrzemyslawKlys we will give this another look...outside of the cosmetic issue of having multiple EditorServices I am curious how this impacts the functionality of the extension (we are trying to understand the severity of the issue)?

**Comment by PrzemyslawKlys** [comment]
Zero impact. Just thinking it may have unexpected consequences. I am not able to tell whether it matters or not.

**Comment by corbob** [comment]
Is it possible that the PowerShell extension updated after it started and so you restarted it possibly resulting in a second entry?

**Comment by PrzemyslawKlys** [comment]
@corbob no. I've not updated for a while. But if you take a look at logs you will see added instances have only this in their logs:
```
[Error - 22:06:25] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.9.0\node_modules\vscode-jsonrpc\lib\common\connection.js:1009:27)
	at Object.dispose (c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.9.0\node_modules\vscode-languageclient\lib\common\client.js:71:35)
	at c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2020.9.0\node_modules\vscode-languageclient\lib\common\client.js:2211:28
```

So most likely some error that just pushes second entry or more entries (I once had 9 of them). I restart PowerShell instance a lot because of IntelliSense dying on me every X minutes so most likely related to that in some way. I would say I restart 10+ times over short amount of time, but it doesn't happen on every restart.

**Comment by andschwa** [comment]
I've actually seen this issue and it seems to happen in my experience whenever the PowerShell session is restarted. Re-opening because since I've seen it then I can repro it.
