### ISSUE TITLE
PowerShell Integrated Console unable to import certain modules

### ISSUE THREAD

**Issue by marek-stancik** [PowerShell/vscode-powershell#2975]
Issue Description
=====

I am experiencing a problem with powershell integrated console. When I'm trying to import module Centrify.DirectControl.PowerShell I receive an error, however when I open a new powershell terminal with ps5.1 or ps7 import works fine. 

Attached Logs
=====

```
=====> PowerShell Integrated Console v2020.6.0 <=====

PS C:\Users\user\Desktop> Import-Module Centrify.DirectControl.PowerShell

Import-Module : Could not load file or assembly 'util, Version=5.7.0.168, Culture=neutral, PublicKeyToken=1f9cb67793557b0b' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-Module Centrify.DirectControl.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\user\Desktop> Import-Module Centrify.DirectControl.PowerShell
PS C:\Users\user\Desktop> 
```

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.   

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\user\Desktop> Import-Module Centrify.DirectControl.PowerShell
PS C:\Users\user\Desktop> 
```

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.49.2|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.752|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.752|
|BuildVersion|10.0.18362.752|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csv-editor|estivo|0.2.2|
|powershell|ms-vscode|2020.6.0|
|saltstack|korekontrol|0.0.8|
|shell-format|foxundermoon|7.0.1|
|shell-launcher|Tyriar|0.4.1|

**Comment by corbob** [comment]
The error indicates that it can't find the file. Could you provide the output from:

```powershell
$env:PSModulePath -split ';'
Get-Module Centrify.DirectControl.PowerShell -ListAvailable
```

From both the Integrated Console, and the terminal where the import is working correctly? What I'm suspecting is that the module is stored somewhere that's not on the PSModulePath that PSIC uses, but for some reason is for other PowerShell instances (which unless you're setting the path in your profile, seems like it might be a PSES issue).

**Comment by marek-stancik** [comment]
hello

output from integrated console:

PS C:\> $env:PSModulePath -split ';'

C:\Users\user\Documents\WindowsPowerShell\Modules
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files\Boldon James\Power Classifier for Files\
C:\Program Files\One Identity\Active Roles\7.3\ConfigCenter\
C:\Program Files\One Identity\Active Roles\7.3\Shell\
C:\Program Files\Centrify\PowerShell\
c:\Users\user\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules
PS C:\> Get-Module Centrify.DirectControl.PowerShell -ListAvailable



    Directory: C:\Program Files\Centrify\PowerShell


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   5.7.0.168  Centrify.DirectControl.PowerShell

output from working terminal:

PS C:\> $env:PSModulePath -split ';'
C:\Users\user\Documents\PowerShell\Modules                 
C:\Program Files\PowerShell\Modules
c:\program files\powershell\7\Modules
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files\Boldon James\Power Classifier for Files\   
C:\Program Files\One Identity\Active Roles\7.3\ConfigCenter\
C:\Program Files\One Identity\Active Roles\7.3\Shell\       
C:\Program Files\Centrify\PowerShell\
PS C:\> Get-Module Centrify.DirectControl.PowerShell -ListAvailable


    Directory: C:\Program Files\Centrify\PowerShell

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   5.7.0.168             Centrify.DirectControl.PowerShell   Desk


from my point of view both terminals can see this module.

**Comment by rjmholt** [comment]
Can you please provide:

- The expanded error from `Import-Module`, using `$error[0] | fl * -force` and possibly `$error[0].Exception | fl * -force`
- The output of `$env:PROCESSOR_ARCHITECTURE`

**Comment by marek-stancik** [comment]
hello

expanded error :
PS C:\> Import-Module Centrify.DirectControl.PowerShell

Import-Module : Could not load file or assembly 'util, Version=5.7.0.168, Culture=neutral, PublicKeyToken=1f9cb67793557b0b' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-Module Centrify.DirectControl.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
PS C:\> $error[0] | fl * -force



PSMessageDetails      :
Exception             : System.IO.FileNotFoundException: Could not load file or assembly 'util, Version=5.7.0.168, Culture=neutral, PublicKeyToken=1f9cb67793557b0b' or one of its dependencies. The system cannot find the 
                        file specified.
                        File name: 'util, Version=5.7.0.168, Culture=neutral, PublicKeyToken=1f9cb67793557b0b'
                           at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
                           at System.Reflection.RuntimeAssembly.GetExportedTypes()
                           at System.Reflection.Assembly.get_ExportedTypes()
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean        
                        isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String helpFile, Type& randomCmdletToCheckLinkDemand, Type& randomProviderToCheckLinkDemand)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad,
                        Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
                           at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String 
                        moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String
                        shortModuleName, Boolean disableFormatUpdates)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss,
                        ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,
                        ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath,        
                        String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found,     
                        String shortModuleName, Nullable`1 manifestLanguageMode)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData,
                        ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean&        
                        containedErrors)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(ExternalScriptInfo scriptInfo, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version
                        maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,
                        ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix,        
                        SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions
                        options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags   
                        manifestProcessingFlags, PSModuleInfo& module)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()

                        WRN: Assembly binding logging is turned OFF.
                        To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                        Note: There is some performance penalty associated with assembly bind failure logging.
                        To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

TargetObject          :
CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

expanded error excepton:
PS C:\> $error[0].Exception | fl * -force



Message        : Could not load file or assembly 'util, Version=5.7.0.168, Culture=neutral, PublicKeyToken=1f9cb67793557b0b' or one of its dependencies. The system cannot find the file specified.
FileName       : util, Version=5.7.0.168, Culture=neutral, PublicKeyToken=1f9cb67793557b0b
FusionLog      : WRN: Assembly binding logging is turned OFF.
                 To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                 Note: There is some performance penalty associated with assembly bind failure logging.
                 To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Data           : {}
InnerException : 
TargetSite     : Void GetExportedTypes(System.Reflection.RuntimeAssembly, System.Runtime.CompilerServices.ObjectHandleOnStack)
StackTrace     :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
                    at System.Reflection.RuntimeAssembly.GetExportedTypes()
                    at System.Reflection.Assembly.get_ExportedTypes()
                    at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
                    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad,    
                 Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String helpFile, Type& randomCmdletToCheckLinkDemand, Type& randomProviderToCheckLinkDemand)
                    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2&  
                 cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
                    at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase,       
                 SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean
                 disableFormatUpdates)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, 
                 ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions&       
                 options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String        
                 prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String 
                 shortModuleName, Nullable`1 manifestLanguageMode)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags    
                 manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(ExternalScriptInfo scriptInfo, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion,       
                 Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions&       
                 options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState  
                 ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options,       
                 ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags
                 manifestProcessingFlags, PSModuleInfo& module)
                    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
                    at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink       :
Source         : mscorlib
HResult        : -2147024894

and processor architecture:
PS C:\> $env:PROCESSOR_ARCHITECTURE

x86

**Comment by rjmholt** [comment]
What does `$env:PROCESSOR_ARCHITECTURE` output in the PowerShell console where you're able to load this module?

**Comment by marek-stancik** [comment]
hey
from working terminal it is

PS C:\> $env:PROCESSOR_ARCHITECTURE
AMD64

real processor is core i5 - x86-64, so it looks like integrated console get this wrong

**Comment by rjmholt** [comment]
Yeah, that's what I suspected.

You're running the x86 PowerShell in the Integrated Console. In the bottom right hand corner, click on the PowerShell logo/version and you'll get a dropdown to select PowerShells installed on the system. You want to select one that doesn't say `(x86)`

**Comment by rjmholt** [comment]
Also, your module path as you have it configured currently mixes Windows PowerShell, PowerShell 7, x86 and x64 module directories, which is a recipe for bad things like this to happen. You should try to make sure the module path is appropriate for the PowerShell you're working with.

**Comment by rjmholt** [comment]
Here's a GIF of changing which PowerShell the Integrated Console uses

![change_ps_version](https://user-images.githubusercontent.com/7009879/94464492-63132d00-0173-11eb-966d-7f6c8c28fa57.gif)

**Comment by marek-stancik** [comment]
Hey Robert
Thanks for this. Now I feel bit stupid that I was not able to deal with this. I'm a still bit new with vscode though.

Thanks again

**Comment by rjmholt** [comment]
>  Thanks for this. Now I feel bit stupid that I was not able to deal with this. I'm a still bit new with vscode though.

No worries, getting the right PowerShell is actually complicated, and given that we share a UI with the rest of VSCode and the extensions, it can be tricky to navigate it all.

It seems we could improve documentation here I think.
