### ISSUE TITLE
Entering a statement with a syntax error in the Terminal causes the session to hang

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#3015]
### System Details

System Details Output
```
### VSCode version: 1.50.1 d2e414d9e4239a252d1ab117bd7067f125afd80a x64

### VSCode extensions:
af4jm.vscode-m3u@1.0.0
akamud.vscode-javascript-snippet-pack@0.1.6
alefragnani.Bookmarks@11.4.0
Angular.ng-template@0.1001.0
anseki.vscode-color@0.4.5
anweber.vscode-tidyhtml@1.10.0
chenxsan.vscode-standardjs@1.3.0
christian-kohler.npm-intellisense@1.3.1
christian-kohler.path-intellisense@2.3.0
CoenraadS.bracket-pair-colorizer@1.0.61
Damien.autoit@1.0.5
DavidAnson.vscode-markdownlint@0.37.1
ecmel.vscode-html-css@0.2.3
eg2.vscode-npm-script@0.3.13
esbenp.prettier-vscode@5.7.1
formulahendry.platformio@0.3.0
GrapeCity.gc-excelviewer@3.0.40
Gruntfuggly.todo-tree@0.0.183
hdg.live-html-previewer@0.3.0
HookyQR.beautify@1.5.0
humao.rest-client@0.24.3
infinity1207.angular2-switcher@0.3.3
ionutvmi.reg@1.0.1
jasonnutter.github-pr@1.0.0
leighlondon.eml@0.4.0
mechatroner.rainbow-csv@1.7.1
Mikael.Angular-BeastCode@10.0.3
ms-azure-devops.azure-pipelines@1.174.2
ms-dotnettools.csharp@1.23.3
ms-mssql.mssql@1.9.0
ms-python.python@2020.9.114305
ms-vscode-remote.remote-wsl@0.50.1
ms-vscode.azure-account@0.9.3
ms-vscode.cpptools@1.0.1
ms-vscode.powershell@2020.6.0
ms-vscode.powershell-preview@2020.9.0
ms-vscode.vscode-typescript-tslint-plugin@1.2.3
msjsdiag.debugger-for-chrome@4.12.11
natewallace.angular2-inline@0.0.17
nobuhito.printcode@3.0.0
nrwl.angular-console@14.0.1
oderwat.indent-rainbow@7.4.0
platformio.platformio-ide@2.1.3
quicktype.quicktype@12.0.46
redhat.java@0.69.0
twxs.cmake@0.0.17
Tyriar.lorem-ipsum@1.2.0
VisualStudioExptTeam.vscodeintellicode@1.2.10
vitaliymaz.vscode-svg-previewer@0.6.0
vscjava.vscode-java-debug@0.29.0
vscjava.vscode-java-dependency@0.13.0
vscjava.vscode-java-pack@0.10.0
vscjava.vscode-java-test@0.24.2
vscjava.vscode-maven@0.24.2
yzane.markdown-pdf@1.4.4
yzhang.markdown-all-in-one@3.3.0
Zignd.html-css-class-completion@1.19.0


### PSES version: 2.2.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.1
PSEdition                      Core
GitCommitId                    7.1.0-rc.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Issue Description

Entering this at the Terminal hangs if the PowerShell Integrated Console is running:

````
$s = @(1,2,3,4)
$s[1..]
````

This _might_ be related to #2713 

#### Expected Behaviour

The correct behavior is what one gets when the PowerShell Integrated Console is *not* running:

![image](https://user-images.githubusercontent.com/12860484/96361659-e4812e00-1127-11eb-8e62-c29d6d420c18.png)

#### Actual Behaviour

The session hangs. `Ctrl+C` does nothing, so one has to exit VScode.

### Attached Logs

[1603006845-1bd91a45-767c-47fc-8fb4-60a06f3138781603006751243.zip](https://github.com/PowerShell/vscode-powershell/files/5397188/1603006845-1bd91a45-767c-47fc-8fb4-60a06f3138781603006751243.zip)

**Comment by SydneyhSmith** [comment]
Thanks for reporting @sba923 I am having trouble reproducing this, however, we have seen this stack trace in another issue which I am struggling to find at the moment--we will need to investigate this further
```
System.Management.Automation.CommandNotFoundException: The term 'Out-Default' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 927
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 927
2020-10-18 09:42:14.830 +02:00 [VRB] Attempting to execute command(s):
````

**Comment by andschwa** [comment]
I know the bot closed this automatically after I updated its actions, but for what it's worth, this bug is not reproducing for me with v2021.8.1-preview and PowerShell 7:

```
=====> PowerShell Preview Integrated Console v2021.8.1 <=====

@andys-mac-mini ~/src/vscode-powershell release ≡
> $s = @(1,2,3,4)

@andys-mac-mini ~/src/vscode-powershell release ≡
> $s[1..]

ParserError: 
Line |
   1 |  $s[1..]
     |        ~
     | You must provide a value expression following the '..' operator.

@andys-mac-mini ~/src/vscode-powershell release ≡
> 
```
