### ISSUE TITLE
Exception showing on Scope variables

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#3020]
Issue Type: <b>Bug</b>

Begin debugging session for Pester tests.
Added misspelled expression to Watch panel
Hit F10 a few times and F11
Renamed expression
Tried to add a second one, the plus sign grayed out and not able to add anymore.

Extension version: 2020.9.0
VS Code version: Code - Insiders 1.51.0-insider (6c8c6008ef9d86e46b086a00f273b1fee5bd8c51, 2020-10-21T05:39:35.557Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (14.19GB free)|
|Process Argv|--crash-reporter-id c13a5331-9871-4944-a4d0-0f26ca06b445|
|Screen Reader|no|
|VM|33%|
</details>

**Comment by wsmelton** [comment]
For the most part a lot of these are being written:
```System.Management.Automation.CmdletInvocationException: The scope number '7' exceeds the number of active scopes.
Parameter name: scopeID
Actual value was 7. ---> System.Management.Automation.PSArgumentOutOfRangeException: The scope number '7' exceeds the number of active scopes.
Parameter name: scopeID
Actual value was 7.
   at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
   at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
   at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
   at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
   at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.InvokeWithDebugger(IEnumerable`1 input, IList`1 output, PSInvocationSettings settings, Boolean invokeMustRun)
   at System.Management.Automation.ScriptDebugger.ProcessCommand(PSCommand command, PSDataCollection`1 output)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.PowerShell5Operations.ExecuteCommandInDebugger[TResult](PowerShellContextService powerShellContext, Runspace currentRunspace, PSCommand psCommand, Boolean sendOutputToHost, Nullable`1& debuggerResumeAction)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandInDebugger[TResult](PSCommand psCommand, Boolean sendOutputToHost)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.<ExecuteCommandAsync>d__89`1.MoveNext() | 
[Error - 7:28:53 AM] Microsoft.PowerShell.EditorServices.Services.PowerShellContextService: Execution of the following command(s) completed with errors:

    Get-Variable -Scope 7```

**Comment by SydneyhSmith** [comment]
Thanks @wsmelton looks like this area of the code could be more robust with better errors. 
It would be helpful to know more context around what you were doing when you hit this issue-- for example what modules you were debugging, or anything particular about your set up

**Comment by wsmelton** [comment]
I don't know if anything that was specific. I'm using Pester 5.1 (beta release) with the PS preview extension, confirmed issue does not exist in the stable release.

I have a module workspace in VS Code opened:
![image](https://user-images.githubusercontent.com/11204251/96946721-c9efe180-14a6-11eb-9064-c941f80afd2c.png)

Then I'm debugging the File Integrity script which I've shared in this Gist on Twitter as well: https://gist.github.com/wsmelton/24bad5e8fbe4ca8f47b9bdb7f25e556d

You can simply:

1. add one or two breakpoints
1. hit F5 (I'm using interactive config)
1. Call `Invoke-Pester .\tests\Module.FileIntegrity.Tests.ps1`
1. Go through hitting F10 and F11 a few times (debugger will jump into the `Pester.psm1` file)
1. Add an expression and it greyes out that plus sign and the UI won't let you add the expression

I am on VS Code Insiders and received the past few updates that have been pushed and this still happens.

**Comment by wsmelton** [comment]
Ok. Scratch that I can replicate this with the stable version of the extension as well.

I add a breakpoint to the test. Then start debugging and after it hits that breakpoint go to add expressions. On the 3rd expression, I add it and not able to add the text for the 3rd expression and the error starts showing up in the output log for the PSE.

![image](https://user-images.githubusercontent.com/11204251/97085330-81d5d980-15e2-11eb-9696-a08c229d1ed8.png)

More than happy to do a Live Share with someone on the team if needed, not sure this can be "seen" from that or not.

**Comment by SydneyhSmith** [comment]
Thanks @wsmelton when you go to add the expression is the breakpoint stopped inside your test file or inside Pester.psm1?

**Comment by SydneyhSmith** [comment]
Thanks @wsmelton for all the information--this looks similar to a bug our intern experienced with debugging scripts running in GitHub actions...this will be a good example for us to work off of to investigate this.
