### ISSUE TITLE
PowerShell Preview Integrated Console v2020.9.0 fails to start after 1.52.0 update 

### ISSUE THREAD

**Issue by hypeitnow** [PowerShell/vscode-powershell#3054]
Issue Description
=====

I am experiencing a problem with starting of powershell preview extension 

Attached Logs
=====
vscode-powershell.log
```
11/8/2020 10:38:10 PM [NORMAL] - Language server starting --
11/8/2020 10:38:10 PM [NORMAL] -     PowerShell executable: /usr/bin/pwsh
11/8/2020 10:38:10 PM [NORMAL] -     PowerShell args: -Login -NoProfile -NonInteractive -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBoAG8AbQBlAC8AaAB5AHAAZQBpAHQALwAuAHYAcwBjAG8AZABlAC0AcwBlAHIAdgBlAHIALQBpAG4AcwBpAGQAZQByAHMALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AcAByAGUAdgBpAGUAdwAtADIAMAAyADAALgA5AC4AMAAvAG0AbwBkAHUAbABlAHMALwBQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AcABzAGQAMQAnADsAIABTAHQAYQByAHQALQBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMAIAAtAEgAbwBzAHQATgBhAG0AZQAgACcAVgBpAHMAdQBhAGwAIABTAHQAdQBkAGkAbwAgAEMAbwBkAGUAIABIAG8AcwB0ACcAIAAtAEgAbwBzAHQAUAByAG8AZgBpAGwAZQBJAGQAIAAnAE0AaQBjAHIAbwBzAG8AZgB0AC4AVgBTAEMAbwBkAGUAJwAgAC0ASABvAHMAdABWAGUAcgBzAGkAbwBuACAAJwAyADAAMgAwAC4AOQAuADAAJwAgAC0AQQBkAGQAaQB0AGkAbwBuAGEAbABNAG8AZAB1AGwAZQBzACAAQAAoACcAUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBWAFMAQwBvAGQAZQAnACkAIAAtAEIAdQBuAGQAbABlAGQATQBvAGQAdQBsAGUAcwBQAGEAdABoACAAJwAvAGgAbwBtAGUALwBoAHkAcABlAGkAdAAvAC4AdgBzAGMAbwBkAGUALQBzAGUAcgB2AGUAcgAtAGkAbgBzAGkAZABlAHIAcwAvAGUAeAB0AGUAbgBzAGkAbwBuAHMALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQBwAHIAZQB2AGkAZQB3AC0AMgAwADIAMAAuADkALgAwAC8AbQBvAGQAdQBsAGUAcwAnACAALQBFAG4AYQBiAGwAZQBDAG8AbgBzAG8AbABlAFIAZQBwAGwAIAAtAFMAdABhAHIAdAB1AHAAQgBhAG4AbgBlAHIAIAAnAD0APQA9AD0APQA+ACAAUABvAHcAZQByAFMAaABlAGwAbAAgAFAAcgBlAHYAaQBlAHcAIABJAG4AdABlAGcAcgBhAHQAZQBkACAAQwBvAG4AcwBvAGwAZQAgAHYAMgAwADIAMAAuADkALgAwACAAPAA9AD0APQA9AD0ACgAnACAALQBMAG8AZwBMAGUAdgBlAGwAIAAnAE4AbwByAG0AYQBsACcAIAAtAEwAbwBnAFAAYQB0AGgAIAAnAC8AaABvAG0AZQAvAGgAeQBwAGUAaQB0AC8ALgB2AHMAYwBvAGQAZQAtAHMAZQByAHYAZQByAC0AaQBuAHMAaQBkAGUAcgBzAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtAHAAcgBlAHYAaQBlAHcALQAyADAAMgAwAC4AOQAuADAALwBsAG8AZwBzAC8AMQA2ADAANAA4ADcAMQA0ADkAMAAtAGYAMgA5AGEAMgA3AGIANwAtADQAZAA5ADMALQA0AGQAMQBjAC0AYgA2ADgAMgAtADAAZQAyADIAMAA5AGYAOQAyADkAOAA2ADEANgAwADQAOAA3ADAANwAzADMAMgA5ADQALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBoAG8AbQBlAC8AaAB5AHAAZQBpAHQALwAuAHYAcwBjAG8AZABlAC0AcwBlAHIAdgBlAHIALQBpAG4AcwBpAGQAZQByAHMALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AcAByAGUAdgBpAGUAdwAtADIAMAAyADAALgA5AC4AMAAvAHMAZQBzAHMAaQBvAG4AcwAvAFAAUwBFAFMALQBWAFMAQwBvAGQAZQAtAHUAbgBkAGUAZgBpAG4AZQBkAC0AOQA2ADMANwAxADUAJwAgAC0ARgBlAGEAdAB1AHIAZQBGAGwAYQBnAHMAIABAACgAKQAgAA==
11/8/2020 10:38:10 PM [NORMAL] -     PowerShell Editor Services args: Import-Module '/home/hypeit/.vscode-server-insiders/extensions/ms-vscode.powershell-preview-2020.9.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/home/hypeit/.vscode-server-insiders/extensions/ms-vscode.powershell-preview-2020.9.0/modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Preview Integrated Console v2020.9.0 <=====
' -LogLevel 'Normal' -LogPath '/home/hypeit/.vscode-server-insiders/extensions/ms-vscode.powershell-preview-2020.9.0/logs/1604871490-f29a27b7-4d93-4d1c-b682-0e2209f929861604870733294/EditorServices.log' -SessionDetailsPath '/home/hypeit/.vscode-server-insiders/extensions/ms-vscode.powershell-preview-2020.9.0/sessions/PSES-VSCode-undefined-963715' -FeatureFlags @() 
11/8/2020 10:38:10 PM [NORMAL] - pwsh started.
11/8/2020 10:38:10 PM [NORMAL] - Waiting for session file
11/8/2020 10:38:12 PM [NORMAL] - Session file found
11/8/2020 10:38:12 PM [NORMAL] - Registering terminal close callback
11/8/2020 10:38:12 PM [NORMAL] - Registering terminal PID log callback
11/8/2020 10:38:12 PM [NORMAL] - pwsh PID: 14907
11/8/2020 10:38:12 PM [NORMAL] - Language server started.
11/8/2020 10:38:12 PM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"/tmp/CoreFxPipe_PSES_uh3zxuzz.tqx","debugServiceTransport":"NamedPipe","debugServicePipeName":"/tmp/CoreFxPipe_PSES_h0rjkab5.rfn"}
11/8/2020 10:38:12 PM [NORMAL] - Connecting to language service on pipe /tmp/CoreFxPipe_PSES_uh3zxuzz.tqx...
11/8/2020 10:38:12 PM [NORMAL] - Language service connected.
```

Visual Studio Code Powershell-preview log from terminal

```
: 30: [[: not found
```
=====> PowerShell Preview Integrated Console v2020.9.0 <=====

```
Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 248 in EndProcessing:
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Pipelines, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.IO.Pipelines, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1.WithInput(Stream input)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>b__14_0(LanguageServerOptions options) in D:\a\1\s\src\PowerShellEditorServices\Server\PsesLanguageServer.cs:line 63
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction, CancellationToken token)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.StartAsync() in D:\a\1\s\src\PowerShellEditorServices\Server\PsesLanguageServer.cs:line 61
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.CreateEditorServicesAndRunUntilShutdown() in D:\a\1\s\src\PowerShellEditorServices.Hosting\Internal\EditorServicesRunner.cs:line 130
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing() in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs:line 243

== Press any key to close terminal ==

```

After pressing any key I got the info that the process 14907 was terminated and the server will not be restarted.

```
The terminal process "/usr/bin/pwsh '-Login', '-NoProfile', '-NonInteractive', '-EncodedCommand', 'SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBoAG8AbQBlAC8AaAB5AHAAZQBpAHQALwAuAHYAcwBjAG8AZABlAC0AcwBlAHIAdgBlAHIALQBpAG4AcwBpAGQAZQByAHMALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AcAByAGUAdgBpAGUAdwAtADIAMAAyADAALgA5AC4AMAAvAG0AbwBkAHUAbABlAHMALwBQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AcABzAGQAMQAnADsAIABTAHQAYQByAHQALQBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMAIAAtAEgAbwBzAHQATgBhAG0AZQAgACcAVgBpAHMAdQBhAGwAIABTAHQAdQBkAGkAbwAgAEMAbwBkAGUAIABIAG8AcwB0ACcAIAAtAEgAbwBzAHQAUAByAG8AZgBpAGwAZQBJAGQAIAAnAE0AaQBjAHIAbwBzAG8AZgB0AC4AVgBTAEMAbwBkAGUAJwAgAC0ASABvAHMAdABWAGUAcgBzAGkAbwBuACAAJwAyADAAMgAwAC4AOQAuADAAJwAgAC0AQQBkAGQAaQB0AGkAbwBuAGEAbABNAG8AZAB1AGwAZQBzACAAQAAoACcAUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBWAFMAQwBvAGQAZQAnACkAIAAtAEIAdQBuAGQAbABlAGQATQBvAGQAdQBsAGUAcwBQAGEAdABoACAAJwAvAGgAbwBtAGUALwBoAHkAcABlAGkAdAAvAC4AdgBzAGMAbwBkAGUALQBzAGUAcgB2AGUAcgAtAGkAbgBzAGkAZABlAHIAcwAvAGUAeAB0AGUAbgBzAGkAbwBuAHMALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQBwAHIAZQB2AGkAZQB3AC0AMgAwADIAMAAuADkALgAwAC8AbQBvAGQAdQBsAGUAcwAnACAALQBFAG4AYQBiAGwAZQBDAG8AbgBzAG8AbABlAFIAZQBwAGwAIAAtAFMAdABhAHIAdAB1AHAAQgBhAG4AbgBlAHIAIAAnAD0APQA9AD0APQA+ACAAUABvAHcAZQByAFMAaABlAGwAbAAgAFAAcgBlAHYAaQBlAHcAIABJAG4AdABlAGcAcgBhAHQAZQBkACAAQwBvAG4AcwBvAGwAZQAgAHYAMgAwADIAMAAuADkALgAwACAAPAA9AD0APQA9AD0ACgAnACAALQBMAG8AZwBMAGUAdgBlAGwAIAAnAE4AbwByAG0AYQBsACcAIAAtAEwAbwBnAFAAYQB0AGgAIAAnAC8AaABvAG0AZQAvAGgAeQBwAGUAaQB0AC8ALgB2AHMAYwBvAGQAZQAtAHMAZQByAHYAZQByAC0AaQBuAHMAaQBkAGUAcgBzAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtAHAAcgBlAHYAaQBlAHcALQAyADAAMgAwAC4AOQAuADAALwBsAG8AZwBzAC8AMQA2ADAANAA4ADcAMwA3ADcANAAtADMAYQA0AGIAOABjAGUAYwAtAGEAMwBjAGUALQA0ADYAZQBhAC0AOAA4AGMANQAtADUAYwA4ADEAZAA3ADYANQBkADMANwAyADEANgAwADQAOAA3ADMANgAzADcAMAAzADcALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBoAG8AbQBlAC8AaAB5AHAAZQBpAHQALwAuAHYAcwBjAG8AZABlAC0AcwBlAHIAdgBlAHIALQBpAG4AcwBpAGQAZQByAHMALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AcAByAGUAdgBpAGUAdwAtADIAMAAyADAALgA5AC4AMAAvAHMAZQBzAHMAaQBvAG4AcwAvAFAAUwBFAFMALQBWAFMAQwBvAGQAZQAtAHUAbgBkAGUAZgBpAG4AZQBkAC0AOQAzADcAMgAzADQAJwAgAC0ARgBlAGEAdAB1AHIAZQBGAGwAYQBnAHMAIABAACgAKQAgAA=='" terminated with exit code: 1.
```

Environment Information
=====

-----

| Name | Version |
| --- | --- |
| Operating System | Linux x64 4.19.128-microsoft-standard |
| VSCode | 1.52.0-insider|
| PowerShell Extension Version | 2020.9.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0-rc.2|
|PSEdition|Core|
|GitCommitId|7.1.0-rc.2|
|OS|Linux 4.19.128-microsoft-standard %231 SMP Tue Jun 23 12:58:10 UTC 2020|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0-rc.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.3|
|azure-pipelines|ms-azure-devops|1.177.0|
|azurecli|ms-vscode|0.5.0|
|azurerm-vscode-tools|msazurermtools|0.13.0|
|bash-beautify|shakram02|0.1.1|
|bash-debug|rogalmic|0.3.9|
|bash-ide-vscode|mads-hartmann|1.11.0|
|csharp|ms-dotnettools|1.23.5|
|gitlens|eamodio|10.2.3|
|kite|kiteco|0.134.0|
|MagicPython|magicstack|1.1.0|
|powershell-preview|ms-vscode|2020.9.0|
|python|ms-python|2020.10.332292344|
|python|tht13|0.2.3|
|python-extension-pack|donjayamanne|1.6.0|
|shebang-snippets|rpinski|0.1.4|
|shell-format|foxundermoon|7.0.1|
|shellcheck|timonwong|0.12.1|
|vscode-azureappservice|ms-azuretools|0.19.0|
|vscode-azurefunctions|ms-azuretools|1.0.0|
|vscode-azureresourcegroups|ms-azuretools|0.2.0|
|vscode-azurestorage|ms-azuretools|0.11.0|
|vscode-cosmosdb|ms-azuretools|0.15.0|
|vscode-django|batisteo|1.0.0|
|vscode-docker|ms-azuretools|1.7.0|
|vscode-dotnet-runtime|ms-dotnettools|0.2.0|
|vscode-node-azure-pack|ms-vscode|0.0.11|
|vscode-pull-request-github|GitHub|0.21.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|vsliveshare|ms-vsliveshare|1.0.3121|

**Comment by rjmholt** [comment]
> after 1.52.0 update 

Did the extension previously work before this? i.e. did 2020.9.0 work with 1.51.0? I ask because the version of VSCode has nothing to do with the extension version, and it shouldn't have any effect.

**Comment by SydneyhSmith** [comment]
Thanks @hypeitnow could you please also try uninstalling and reinstalling the extension and let us know if that helps?

**Comment by rjmholt** [comment]
It looks like there's an assembly missing for some reason though? What's the output of this:

```
gci -recurse '/home/hypeit/.vscode-server-insiders/extensions/ms-vscode.powershell-preview-2020.9.0/modules/PowerShellEditorServices/'
```

**Comment by hypeitnow** [comment]
> Thanks @hypeitnow could you please also try uninstalling and reinstalling the extension and let us know if that helps? 

Unfortunately reinstallation did not help, eventually I decided to uninstall powershell from my WSL and that resolved the issue
