### ISSUE TITLE
Cannot Debug Pester Tests

### ISSUE THREAD

**Issue by GityupSS** [PowerShell/vscode-powershell#3199]
Issue Type: <b>Bug</b>

problem started after January 2021 update
currently using powershell 7.1.2 and pester 4.10.1. 
Used to work with Powershell 2020.6.0 extension... I even tried with Powershell 2020.9.0 preview, with the same result.

When using "run tests", works OK.
When using "Debug tests" without BreakPoints, work like "run tests"
When using "Debug tests" with BreakPoints, Debug side window opens, 

Then either nothing happens (last time I let it run for 20 minutes) Shift-F5 to Stop
Either tests runs without stopping on breakpoints and stalls after this output in terminal:
################################
                                                           WARNING: Breakpoint Command breakpoint on '' will not be hit

Hit Command breakpoint on ''

[DBG]: PS C:\WorkSpace\Scripts\>

Hit Command breakpoint on ''
################################
As well as, ps1 file open
C:\Users\ *username*\AppData\Local\Temp\PSES-18484\ [*HOSTNAME*] Script Listing.ps1
with only "0" in its content.

Extension version: 2020.6.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (7.61GB free)|
|Process Argv|--crash-reporter-id 4eac389b-80c0-4b6e-a084-accb1ae224fc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by GityupSS** [comment]
I Also get this error when I Stop the debugger in a stalled state 
![2021-02-23 09_19_08-Window](https://user-images.githubusercontent.com/76173404/108858976-c1c1c300-75ba-11eb-8d3c-6eb78c28c123.jpg)

**Comment by GityupSS** [comment]
I've installed VSCODE 1.52.1 and it seems a little better.
it does the same thing: tests the code with pester, then halts, but when I SHIFT-F5 to stop, another  *Hit Command breakpoint on ''* shows up. I need to click Stop for every breakpoint and then debugger stops correctly.

Also, at the very end, [*HOSTNAME] script Listing.ps1 is populated with : 

$global:__psEditorServices_CallStack = Get-PSCallStack; $global:__psEditorServices_CallStack

instead of 0.

**Comment by SydneyhSmith** [comment]
Thanks @GityupSS it would be really helpful if you could also attach the logs--instructions for how to do that are [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by GityupSS** [comment]
Enabling diagnostics makes VSCODE crash! This is getting weirder!!!
![2021-02-24 08_57_46-Window](https://user-images.githubusercontent.com/76173404/109011156-9bfdf200-767e-11eb-8832-2001bbef4f22.jpg)

**Comment by GityupSS** [comment]
restarted VSCODE and powershell does not load
![2021-02-24 09_27_49-Window](https://user-images.githubusercontent.com/76173404/109015059-be920a00-7682-11eb-9814-b7361ceb7634.jpg)

**Comment by GityupSS** [comment]
here are the logs
[logs-posh-vscode.zip](https://github.com/PowerShell/vscode-powershell/files/6036835/logs-posh-vscode.zip)

**Comment by SydneyhSmith** [comment]
Thanks for providing the logs they are helpful, it looks like this is causing the issue: 
```
2021-02-24 09:33:10.920 -05:00 [WRN] Runtime exception occurred while executing command:

System.Management.Automation.RuntimeException: An error occurred while creating the pipeline.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 927
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 927
2021-02-24 09:33:10.920 -05:00 [ERR] ReleaseRunspaceHandle was called when the main thread was not busy.
```

In other words, it looks like the runspace is getting into a bad state, this will hopefully be resolved by the https://github.com/PowerShell/PowerShellEditorServices/issues/1295
