### ISSUE TITLE
Powershell 7 Preview crashes Intergated Console v2021.2.2 on startup: Could not load file or assembly 'System.IO.Pipelines'

### ISSUE THREAD

**Issue by thakyZ** [PowerShell/vscode-powershell#3219]
### System Details

System Details Output
```
### VSCode version: 1.53.2 622cb03f7e070a9670c94bae1a45d78d7181fbd4 x64

### VSCode extensions:
adamprzybylski.paradox-syntax@1.0.1
alefragnani.Bookmarks@13.0.2
alefragnani.project-manager@12.0.1
AnthonyJ.stellaris-localisation-syntax@1.1.0
arcanis.vscode-zipfs@2.2.2
arcensoth.language-mcfunction@0.17.0
asciidoctor.asciidoctor-vscode@2.8.7
bierner.emojisense@0.8.0
bierner.markdown-checkbox@0.1.3
brunnerh.insert-unicode@0.10.0
chiehyu.vscode-astyle@0.9.0
christian-kohler.npm-intellisense@1.3.1
christian-kohler.path-intellisense@2.3.0
codezombiech.gitignore@0.6.0
CoenraadS.bracket-pair-colorizer@1.0.61
CoenraadS.bracket-pair-colorizer-2@0.2.0
coolbear.systemd-unit-file@1.0.6
danielpinto8zz6.c-cpp-compile-run@1.0.13
DavidAnson.vscode-markdownlint@0.39.0
dbaeumer.jshint@0.11.0
dbaeumer.vscode-eslint@2.1.14
devCAT.kailua@1.1.0
donjayamanne.githistory@0.6.14
DotJoshJohnson.xml@2.5.1
eamodio.gitlens@11.2.1
EditorConfig.EditorConfig@0.16.4
eg2.vscode-npm-script@0.3.16
eppz.eppz-code@1.2.52
esbenp.prettier-vscode@5.9.2
faustinoaq.crystal-lang@0.4.0
firefox-devtools.vscode-firefox-debug@2.9.2
fireside21.cshtml@0.1.3
formulahendry.auto-close-tag@0.5.10
formulahendry.auto-complete-tag@0.1.0
formulahendry.auto-rename-tag@0.1.6
g3ortega.crystal@0.1.9
gbasood.byond-dm-language-support@1.0.1
george3447.docker-run@1.0.0
Gydunhn.javascript-essentials@0.0.7
hans000.mc-json-viewer@1.0.6
hans0000.texture-json@1.0.5
henriiik.docker-linter@0.5.0
HookyQR.beautify@1.5.0
HuJohner.mc-datapack@0.0.5
ikappas.phpcs@1.0.5
Indexyz.zenscript@0.0.2
ionutvmi.reg@1.0.2
jbenden.c-cpp-flylint@1.8.2
jbw91.theme-material-dark-soda@1.3.1
joaompinto.asciidoctor-vscode@2.8.0
jRichardeau.vscode-vsproj@1.2.1
kofno.crystal-ide@0.0.4
KyleeTehKitty.StarboundJson@0.1.3
Leopotam.csharpfixformat@0.0.84
Levertion.mcjson@0.4.1
lukas-tr.materialdesignicons-intellisense@3.1.0
madeline.rwxml-lang-serv@0.4.29
mathiasfrohlich.Kotlin@1.7.1
mitaki28.vscode-clang@0.2.3
mohsen1.prettify-json@0.0.3
mrmlnc.vscode-json5@1.0.0
ms-azuretools.vscode-docker@1.10.0
ms-dotnettools.csharp@1.23.9
ms-python.python@2021.2.582707922
ms-python.vscode-pylance@2021.2.4
ms-toolsai.jupyter@2021.2.603412351
ms-vscode-remote.remote-containers@0.158.0
ms-vscode-remote.remote-ssh@0.64.0
ms-vscode-remote.remote-ssh-edit@0.64.0
ms-vscode-remote.remote-wsl@0.53.4
ms-vscode-remote.vscode-remote-extensionpack@0.20.0
ms-vscode.cmake-tools@1.6.0
ms-vscode.cpptools@1.2.2
ms-vscode.powershell@2021.2.2
ms-vscode.vs-keybindings@0.2.0
oderwat.indent-rainbow@7.5.0
pahimar.minecraft-essentials-extension-pack@1.0.1
PKief.material-icon-theme@4.5.0
PKief.material-product-icons@1.0.2
platymuus.dm-langclient@0.1.10
redhat.java@0.75.0
redhat.vscode-xml@0.15.0
redhat.vscode-yaml@0.15.0
ritwickdey.live-sass@3.0.0
ritwickdey.LiveServer@5.6.1
romanrei.material-dark@1.1.0
shakram02.bash-beautify@0.1.1
shd101wyy.markdown-preview-enhanced@0.5.16
shengchen.vscode-checkstyle@1.4.0
slevesque.shader@1.1.5
slevesque.vscode-autohotkey@0.2.2
SonarSource.sonarlint-vscode@1.20.1
Stevertus.mcscript@0.0.3
sth4nothing.paradox-formatter@0.1.7
streetsidesoftware.code-spell-checker@1.10.2
StroupBSlayen.vscord@0.5.3
Strum355.vscode-mc-shader@0.9.5
subtixx.starbound-lua@2.4.0
sumneko.lua@1.17.3
tboby.cwtools-vscode@0.9.3
tboby.paradox-syntax@0.1.16
timonwong.shellcheck@0.13.2
ultram4rine.vscode-choosealicense@0.4.0
VisualStudioExptTeam.vscodeintellicode@1.2.11
vscjava.vscode-java-debug@0.31.0
vscjava.vscode-java-dependency@0.18.1
vscjava.vscode-java-pack@0.12.1
vscjava.vscode-java-test@0.28.0
vscjava.vscode-maven@0.27.1
vsls-contrib.codetour@0.0.44
vsls-contrib.gistfs@0.2.2
xabikos.JavaScriptSnippets@1.8.0
zokugun.explicit-folding@0.11.0
zz5840.minecraft-lang-colorizer@1.0.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

Whenever I try to start PowerShell Integrated console with PowerShell 7 Preview it crashes with this error:

```
=====> PowerShell Integrated Console v2021.2.2 <=====

Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 248 in EndProcessing:
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Pipelines, Version=4.0.2.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.File name: 'System.IO.Pipelines, Version=4.0.2.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1.WithInput(Stream input)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>b__14_0(LanguageServerOptions options) in D:\a\1\s\src\PowerShellEditorServices\Server\PsesLanguageServer.cs:line 63 
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction, IServiceProvider outerServiceProvider, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.StartAsync() in D:\a\1\s\src\PowerShellEditorServices\Server\PsesLanguageServer.cs:line 61
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.CreateEditorServicesAndRunUntilShutdown() in D:\a\1\s\src\PowerShellEditorServices.Hosting\Internal\EditorServicesRunner.cs:line 130
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing() in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs:line 243       

== Press any key to close terminal ==
```

#### Expected Behaviour

PowerShell 7 Preview opens with Integrated Console Correctly

#### Actual Behaviour

Crashes every time without opening the terminal.

### Attached Logs

https://pastebin.com/BF77HUAS

**Comment by andschwa** [comment]
Hey! I know the bot closed this automatically, but I wanted to add that I actually identified and fixed a bug where the required DLLs were not being included in the PSES bits bundled with the extension. It turned out to be a bug in the .NET SDK that we since worked around and they recently resolved upstream. Please test the latest preview extension on the marketplace (v2021.8.1-preview) and re-open this if it recurs! (Actually, let me know if _doesn't_ happen any more, too, that'd be awesome!)
