### ISSUE TITLE
Fix flaky CI pipelines

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#3326]
Our Azure CI pipelines (especially but not only the macOS variant) are super flaky, to the point that they're almost always taking one to three retries to pass.

**Comment by andschwa** [comment]
@rjmholt I'm seeing:

```
1 failing

  1) ExternalApi feature - Other APIs
       It can get PowerShell version details:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/out/test/features/ExternalApi.test.js)
  	at listOnTimeout (internal/timers.js:554:17)
  	at processTimers (internal/timers.js:497:7)
```

Fail more and more often, especially on macOS...

**Comment by andschwa** [comment]
This isn't happening nearly as often now @rjmholt 🤷

**Comment by andschwa** [comment]
These are no longer flaky, and we're not sure why, but let's not solve problems that no longer exist.
