### ISSUE TITLE
Debugging with active breakpoint crashes Powershell session

### ISSUE THREAD

**Issue by fflaten** [PowerShell/vscode-powershell#3667]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Powershell session crashes in preview extension when attempting to debug a script with active breakpoint in unsaved file. Debugging the same code in a saved file works.

Also occurs when debugging Pester tests, but was able to reproduce the same exception in this simpler demo so I believe it might be the same root cause.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.62.0-insider
b3318bc0524af3d74034b8bb8a64df0ccf35549a
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2021.11.0
```

### Steps to Reproduce

1. Open a new unsaved file with content `$a = 1`
2. Place a breakpoint on the line and launch/debug file as normal
 

### Visuals

**Repro**
![pses3-debug-crash](https://user-images.githubusercontent.com/3436158/140298348-62f1235e-4ce0-4704-b471-dd985c3a3528.gif)

**Exception**
![115](https://user-images.githubusercontent.com/3436158/140298677-b4cbfb6b-7ef3-46ec-b9c2-9def18ff7a90.png)

**Comment by fflaten** [comment]
@JustinGrote Can you repro this? Would've thought you'd hit it while troubleshooting #3655

**Comment by JustinGrote** [comment]
I can consistently reproduce if you:
1. Start a debug session
2. Run a pester test

I get the same scopes issue.

**Comment by JustinGrote** [comment]
This particular issue (not the pester reproduction) also just happens with an unsaved file. If you save the file it works fine.

![image](https://user-images.githubusercontent.com/15258962/140424007-405f5184-fced-41f6-bbcb-ef1bfecbea86.png)

**Comment by andschwa** [comment]
Definitely some debugging issues to work through...

**Comment by JustinGrote** [comment]
Full stacktrace of being able to reproduce it, I'm pretty sure whatever the problem is happens before this point. I'll try to get a debug session going.

```
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.Management.Automation.CmdletInvocationException: The scope number '3' exceeds the number of active scopes. (Parameter 'Scope')       
Actual value was 3.
 ---> System.Management.Automation.PSArgumentOutOfRangeException: The scope number '3' exceeds the number of active scopes. (Parameter 'Scope')
Actual value was 3.
   at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
   at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
   at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
   at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
   at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)     
   at System.Management.Automation.PowerShell.InvokeWithDebugger(IEnumerable`1 input, IList`1 output, PSInvocationSettings settings, Boolean invokeMustRun)      
   at System.Management.Automation.ScriptDebugger.ProcessCommand(PSCommand command, PSDataCollection`1 output)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteInDebugger(CancellationToken cancellationToken) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 153
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.Run(CancellationToken cancellationToken) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 55
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 92
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.DebugService.FetchVariableContainerAsync(String scope, VariableContainerDetails autoVariables) in D:\a\1\s\src\PowerShellEditorServices\Services\DebugAdapter\DebugService.cs:line 690
   at Microsoft.PowerShell.EditorServices.Services.DebugService.FetchStackFramesAsync(String scriptNameOverride) in D:\a\1\s\src\PowerShellEditorServices\Services\DebugAdapter\DebugService.cs:line 818
   at Microsoft.PowerShell.EditorServices.Services.DebugService.FetchStackFramesAndVariablesAsync(String scriptNameOverride) in D:\a\1\s\src\PowerShellEditorServices\Services\DebugAdapter\DebugService.cs:line 661
   at Microsoft.PowerShell.EditorServices.Services.DebugService.OnDebuggerStopAsync(Object sender, DebuggerStopEventArgs e) in D:\a\1\s\src\PowerShellEditorServices\Services\DebugAdapter\DebugService.cs:line 920
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   ```

**Comment by JustinGrote** [comment]
Looks normal up to this point, something in the _pwsh prcess setup?
![image](https://user-images.githubusercontent.com/15258962/140429663-f6204fa0-8a64-45a5-8eed-dd7c18548f4b.png)

**Comment by JustinGrote** [comment]
This part of the fetching of stack frames is the problem, the i loop goes to an undefined scope.

https://github.com/PowerShell/PowerShellEditorServices/blob/f825d89c5ef13423f78c5c3b68809a3daca9609f/src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs#L809-L844

**Comment by andschwa** [comment]
This line sure looks funny: https://github.com/PowerShell/PowerShellEditorServices/blob/f825d89c5ef13423f78c5c3b68809a3daca9609f/src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs#L813

**Comment by JustinGrote** [comment]
Fails here, tries to do a `Get-Variable -Scope 3`
https://github.com/PowerShell/PowerShellEditorServices/blob/f825d89c5ef13423f78c5c3b68809a3daca9609f/src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs#L687-L692

![image](https://user-images.githubusercontent.com/15258962/140432776-e24fc005-acac-4de2-a827-524683ad76f1.png)

**Comment by JustinGrote** [comment]
I think I found the problem. This seems to assume the stacktrace length is the same as the number of variable scopes, which is going to not be true if any assemblies are involved I think.
![image](https://user-images.githubusercontent.com/15258962/140433695-f2f9beda-e874-4396-83ed-8e70b23d3553.png)

**Comment by JustinGrote** [comment]
This doesn't account for a scope exception. Adding a try catch to swallow that specific exception here should have the expected result, at least unless we can find a more proactive way to determine if variables exist without having to run a command. Any advice @rjmholt?


https://github.com/PowerShell/PowerShellEditorServices/blob/f825d89c5ef13423f78c5c3b68809a3daca9609f/src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs#L690-L691

**Comment by SeeminglyScience** [comment]
This is a pretty old issue (#1856) though in the past it just polluted `$Error` so not much of an issue.

In the PR for the rewrite I made a comment about us setting `ErrorActionPreference` to `Stop` somewhere.  @andschwa do you know if that got resolved? Non-terminating errors like parameter binding definitely should not be crashing or even hitting a catch.

**Comment by SeeminglyScience** [comment]
Some details about why this error occurs in general [in this comment](https://github.com/PowerShell/vscode-powershell/issues/1856#issuecomment-511784392).

**Comment by JustinGrote** [comment]
This does look exactly what it is https://github.com/PowerShell/vscode-powershell/issues/1856#issuecomment-511784392

**Comment by SeeminglyScience** [comment]
Yeah it comes up from time to time.  I think the real problem is that a benign error is causing a crash.  Ideally it would be a silent non-terminating error, but at the very least there's a catch somewhere that's too specific.

**Comment by JustinGrote** [comment]
Agreed, @andschwa there should be a broad catch for all otherwise-uncaught pwsh invocation exceptions that logs the exception occurred but doesn't kill PSES (or at the very worst auto-restarts it)

**Comment by SeeminglyScience** [comment]
Ah right parameter binding exceptions are terminating so not `ErrorActionPreference` related.  Just a catch somewhere that's too narrow probably

**Comment by JustinGrote** [comment]
Draft Fix: https://github.com/PowerShell/PowerShellEditorServices/pull/1620

**Comment by SeeminglyScience** [comment]
I think it might need to [just be here](https://github.com/PowerShell/PowerShellEditorServices/blob/5e40029bfb7d9cc3d17bdd69db24c71836da7cfb/src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs#L112).  Maybe change the `RuntimeException` clause to `Exception` since really anything can be thrown there.

**Comment by JustinGrote** [comment]
> I think it might need to [just be here](https://github.com/PowerShell/PowerShellEditorServices/blob/5e40029bfb7d9cc3d17bdd69db24c71836da7cfb/src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs#L112). Maybe change the `RuntimeException` clause to `Exception` since really anything can be thrown there.

Makes sense, @andschwa this should be a separate PR and it has wide reaching consequences so I'd ask you try this part :)
