### ISSUE TITLE
Addition to #3733 - Launching VSCode with AllSigned GPO still fails as not all certificates were updated

### ISSUE THREAD

**Issue by MN-Joe** [PowerShell/vscode-powershell#3741]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Do you want to run software from this untrusted publisher?
File C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run [D] Do not run [R] Run once [A] Always run [?] Help (default is "Do not run"): Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 246 in EndProcessing:
System.Management.Automation.CmdletInvocationException: Errors occurred while loading the format data file: 
C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml, , C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: AuthorizationManager check failed..
 ---> System.Management.Automation.RuntimeException: Errors occurred while loading the format data file:
C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml, , C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: AuthorizationManager check failed..

   at System.Management.Automation.Runspaces.InitialSessionState.ThrowTypeOrFormatErrors(String resourceString, String errorMsg, String errorId)
   at System.Management.Automation.Runspaces.InitialSessionState.UpdateFormats(ExecutionContext context, Boolean update)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind_UpdateFormats(ExecutionContext context, Boolean updateOnly)    
   at System.Management.Automation.Runspaces.InitialSessionState.<>c__DisplayClass142_0.<Bind>b__1()
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings 
settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.PSReadLinePromptContext.TryGetPSReadLineProxy(ILogger logger, Runspace runspace, String bundledModulePath, PSReadLineProxy& readLineProxy)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.Initialize(ProfilePathInfo profilePaths, Runspace initialRunspace, Boolean ownsInitialRunspace, IHostOutput consoleHost)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.Create(ILoggerFactory factory, ILanguageServerFacade languageServer, HostStartupInfo hostStartupInfo)
   at Microsoft.PowerShell.EditorServices.Server.PsesServiceCollectionExtensions.<>c__DisplayClass0_0.<AddPsesLanguageServices>b__0(IServiceProvider provider)
   at DryIoc.Registrator.ToFactoryDelegate[TService](Func`2 f, IResolverContext r)
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result)
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result)   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Rules.<>c__DisplayClass74_1.<ConcreteTypeDynamicRegistrations>b__2(Request req)
   at DryIoc.Factory.CheckCondition(Request request)
   at DryIoc.RequestTools.MatchFactoryConditionAndMetadata(Request request, Factory factory)
   at DryIoc.RequestTools.MatchFactoryConditionAndMetadata(Request r, KV`2 f)
   at DryIoc.Container.GetRuleSelectedServiceFactoryOrDefault(Request request, Type serviceType)
   at DryIoc.Container.DryIoc.IContainer.GetServiceFactoryOrDefault(Request request)
   at DryIoc.Container.DryIoc.IContainer.ResolveFactory(Request request)
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at OmniSharp.Extensions.JsonRpc.JsonRpcHandlerCollectionExtensions.Populate(IJsonRpcHandlerCollection collection, IResolverContext resolverContext, IHandlersManager handlersManager)
   at OmniSharp.Extensions.LanguageServer.Shared.LanguageProtocolServiceCollectionExtensions.<>c__0`1.<AddLanguageProtocolInternals>b__0_2(SharedHandlerCollection manager, IResolverContext context)
   at DryIoc.Registrator.Initializer[TTarget,TService](TService service, IResolverContext resolver, Action`2 initialize)
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result)   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Container.DryIoc.IContainer.GetDecoratorExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<From>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.<CreateEditorServicesAndRunUntilShutdown>d__9.MoveNext()      
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

### PowerShell Version

```console
Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.19041.1320                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.19041.1320                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

I did a full remove and totally reinstalled VSCode and just loaded the PowerShell extension - similar type of error "Could not load language files comes up but if you look in the displayed text - shown above you can see it is referencing a .ps1xml file which appears to maybe still have a 3/3/2021 certificate associated with it.

### Logs

Do you want to run software from this untrusted publisher?
File C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run [D] Do not run [R] Run once [A] Always run [?] Help (default is "Do not run"): Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 246 in EndProcessing:
System.Management.Automation.CmdletInvocationException: Errors occurred while loading the format data file: 
C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml, , C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: AuthorizationManager check failed..
 ---> System.Management.Automation.RuntimeException: Errors occurred while loading the format data file:
C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml, , C:\Users\JWGasner\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: AuthorizationManager check failed..

   at System.Management.Automation.Runspaces.InitialSessionState.ThrowTypeOrFormatErrors(String resourceString, String errorMsg, String errorId)
   at System.Management.Automation.Runspaces.InitialSessionState.UpdateFormats(ExecutionContext context, Boolean update)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind_UpdateFormats(ExecutionContext context, Boolean updateOnly)    
   at System.Management.Automation.Runspaces.InitialSessionState.<>c__DisplayClass142_0.<Bind>b__1()
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings 
settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.PSReadLinePromptContext.TryGetPSReadLineProxy(ILogger logger, Runspace runspace, String bundledModulePath, PSReadLineProxy& readLineProxy)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.Initialize(ProfilePathInfo profilePaths, Runspace initialRunspace, Boolean ownsInitialRunspace, IHostOutput consoleHost)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.Create(ILoggerFactory factory, ILanguageServerFacade languageServer, HostStartupInfo hostStartupInfo)
   at Microsoft.PowerShell.EditorServices.Server.PsesServiceCollectionExtensions.<>c__DisplayClass0_0.<AddPsesLanguageServices>b__0(IServiceProvider provider)
   at DryIoc.Registrator.ToFactoryDelegate[TService](Func`2 f, IResolverContext r)
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result)
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result)   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Rules.<>c__DisplayClass74_1.<ConcreteTypeDynamicRegistrations>b__2(Request req)
   at DryIoc.Factory.CheckCondition(Request request)
   at DryIoc.RequestTools.MatchFactoryConditionAndMetadata(Request request, Factory factory)
   at DryIoc.RequestTools.MatchFactoryConditionAndMetadata(Request r, KV`2 f)
   at DryIoc.Container.GetRuleSelectedServiceFactoryOrDefault(Request request, Type serviceType)
   at DryIoc.Container.DryIoc.IContainer.GetServiceFactoryOrDefault(Request request)
   at DryIoc.Container.DryIoc.IContainer.ResolveFactory(Request request)
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at OmniSharp.Extensions.JsonRpc.JsonRpcHandlerCollectionExtensions.Populate(IJsonRpcHandlerCollection collection, IResolverContext resolverContext, IHandlersManager handlersManager)
   at OmniSharp.Extensions.LanguageServer.Shared.LanguageProtocolServiceCollectionExtensions.<>c__0`1.<AddLanguageProtocolInternals>b__0_2(SharedHandlerCollection manager, IResolverContext context)
   at DryIoc.Registrator.Initializer[TTarget,TService](TService service, IResolverContext resolver, Action`2 initialize)
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result)   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Container.DryIoc.IContainer.GetDecoratorExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<From>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.<CreateEditorServicesAndRunUntilShutdown>d__9.MoveNext()      
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

**Comment by andschwa** [comment]
Oh, I see. Thanks for the more detailed info. The stack trace indicates it's failing when loading the bundled [PSReadLine](https://github.com/PowerShell/PSReadLine) module. @daxian-dbw Looks like we need a re-release of the last stable version of PSReadLine, v2.1.0, with an updated signature as its signing certificate has seemingly expired. Can you take a look? I am rather surprised there are no open issues against PSReadLine about this...

**Comment by daxian-dbw** [comment]
I doubt that's the problem. The certificate used to sign `PSReadLine` and other modules that PowerShell team owns is never considered as trusted publishers by Windows by default. You will have to add it to the `Trusted Publishers` to make then trusted by default.

If you look at the built-in modules shipped with PS 7.2, all the following modules are signed with a certificate that's no longer valid anymore:
```
Microsoft.PowerShell.Archive
PackageManagement
PowerShellGet
PSReadLine
ThreadJob
```
but they don't affect anything.

I think the **"Valid from xxx to xxx"** means the certificate can be used to sign during that period, but it doesn't affect the signed filed.

**Comment by daxian-dbw** [comment]
It looks to me @MN-Joe has execution policy set to be `AllSigned` on his machine. That's the only case I can think of that would cause the "trusted publishers" prompt.

**Comment by MN-Joe** [comment]
The certificate expired on 3/3/21, under allsigned this will not run, prompt yes and it gets saved to the trusted publishers but will fail as shown in my logs.


________________________________

**Comment by daxian-dbw** [comment]
> The certificate expired on 3/3/21, under allsigned this will not run, prompt yes and it gets saved to the trusted publishers but will fail as shown in my logs.

The signing cert is never trusted by Windows by default, so even if it's still valid for signing purpose, you will get the same "trust publisher" prompt when running with `AllSigned` execution policy.

The certificate expired, but that only means it cannot be used for signing anymore. For files that are already signed by it, it still shows who published the files as expected.

**Comment by SydneyhSmith** [comment]
Thanks @MN-Joe for your responses! Does PSReadLine 2.1.0 (latest stable) work with AllSigned in PowerShell outside of VSCode for you?

**Comment by andschwa** [comment]
Hi @MN-Joe, actually I see what's going on now. Since you're running under AllSigned, you will need to manually import the modules the extension needs to load (all modules under the extension's folder) and interactively trust the publishers. Once you've established trust of the modules on your system, the extension will load correctly. It cannot interactively ask for you to trust the module, as loading the module happens before an interactive console is available.

**Comment by bucmic** [comment]
I would like to know how Microsoft will solve this issue. Will the certificate be installed by any future VS Code installer? It's no very practicable for every user to import the certificate from the module file into the Trusted Publisher store manually.

**Comment by andschwa** [comment]
@bucmic you are running on with an explicit `AllSigned` policy, it is up to you to manage your certificate trust. Trusting the certificate _for you_ in an installer would defeat the purpose of the `AllSigned` policy. You should evaluate if that's a policy you actually want enforced on your system considering the trouble it's giving you.
