### ISSUE TITLE
Fix (or disable) "attach to process" debugging

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#3849]
This is tied into "remote debugging" and we need to be sure it works.

**Comment by JustinGrote** [comment]
There is still a big issue, more about runspaces, that entering a runspace still hangs the console. This is a "big deal" showstopper for doing any kind of debugging in this environment.

**Comment by andschwa** [comment]
Completely agree!

**Comment by andschwa** [comment]
It's probably our last and biggest blocker to move the preview to stable.

**Comment by andschwa** [comment]
Just running the "attach process" kinda works works?

**Comment by SeeminglyScience** [comment]
Attach to process definitely doesn't work.

1. Doesn't `Debug-Runspace` after entering the target process
2. If you do it manually, breakpoints aren't transferred
3. Trying to abort the debug session dead locks the session completely

Note, unfortunately this is a potentially quite large work item and was the most difficult piece to fix when I integrated PSRL years ago. I have also verified it **does** work in stable. Pretty finicky, but definitely usable.

Hopefully easier to fix with the improved architecture though 🤞

**Comment by SeeminglyScience** [comment]
We also need to test (after this is fixed) if debugging an azure function still works.

**Comment by andschwa** [comment]
Thanks @SeeminglyScience!

**Comment by JustinGrote** [comment]
> We also need to test (after this is fixed) if debugging an azure function still works.

Just as FYI, doesn't work as expected:
1. Running the attach does attach once the process starts and the named pipe is available
1. Breakpoints don't work or register, 
1. Subsequent runs fail to attach, requires PSIC restart
1. On Debug stop, finally enters debugging but hangs, and then eventually handle closes and Runspace error

```
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.2
PowerShell: 2022.4.0
OS: Microsoft Windows 10.0.22593
BufferWidth: 204
BufferHeight: 22

Last 137 Keys:

 Enter
 Ctrl+@ Enter
 Ctrl+@ Enter
 Ctrl+@ Enter
 Ctrl+@ g e t - p s b r e a k Ctrl+@ p o i n t Enter
 Ctrl+@ g e t - p s b r e a k p o i n t Enter
 Ctrl+@ a w e Ctrl+@ r a w Backspace Backspace Backspace a s d f a s d f a s d f a w e r Ctrl+a Backspace Backspace Enter
 Enter
 Ctrl+@ a s d f a s d f Ctrl+a Backspace Backspace a s d f a w e r a w e r Ctrl+a Backspace g e t - p s b r e a k p o i n t Enter
 Ctrl+@ g e t - p s b r e a k p o i n t DownArrow

### Exception

System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
   at System.Threading.WaitHandle.ObtainSafeWaitHandles(ReadOnlySpan`1 waitHandles, Span`1 safeWaitHandles, Span`1 unsafeWaitHandles)
   at System.Threading.WaitHandle.WaitMultiple(ReadOnlySpan`1 waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
                                                                                                                                                                                                            🚧\AzureFunctionsMissingManual on main❯
The current runspace entered state 'Opened' for reason ''. If this occurred when using Ctrl+C in a Windows PowerShell remoting session, this is expected behavior. The session is now returning to the previous runspace.

```

1. Occasional REPL fail
```
An error occurred while running the REPL loop:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Console.PsrlReadLine.InvokePSReadLine(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Console\PsrlReadLine.cs:line 42
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousDelegateTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousDelegateTask.cs:line 63
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 91
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.get_Result() in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 58
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteAndGetResult(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 107
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokeDelegate[TResult](String representation, ExecutionOptions executionOptions, Func`2 func, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 347
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Console.PsrlReadLine.ReadLine(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Console\PsrlReadLine.cs:line 35
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokeReadLine(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 700
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.DoOneRepl(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 616
   ```

**Comment by JustinGrote** [comment]
Can confirm this years-long bug is *finally* fixed in preview. You can debug an Azure Functions worker *and* get repl at the console at that point.
![image](https://user-images.githubusercontent.com/15258962/163893209-e72e1a10-bc8f-4d20-aefb-24a441c376a9.png)
