### ISSUE TITLE
Powershell Integrated Console 2022.5.1 had problems with PnP Powershell

### ISSUE THREAD

**Issue by gitulm** [PowerShell/vscode-powershell#3968]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

After updating VSC to 1.67 and Powershell Integrated Console (2022.5.1), PnP Powershell (1.10.0) no longer works for me. When I want to connect:
Connect-PnPOnline -Url https://xxx.sharepoint.com/sites/zhs-dokumente -Credentials $userCredential2
then I get the following error message:

Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)

If I do the same with PWSH 7.2 everything works. The command has always worked so far.

$error[0] | fl * -force says the following:

PSMessageDetails      : 
Exception             : System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could    
                        not find or load a specific file. (0x80131621)
                        File name: 'Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
                         ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'.
                           at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)       
                           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
                           at System.Reflection.Assembly.LoadFrom(String assemblyFile)
                           at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
                           at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
                           at PnP.PowerShell.Commands.Base.PnPConnection.CreateWithCredentials(Cmdlet cmdlet, Uri url, PSCredential credentials, Boolean currentCredentials, String
                        tenantAdminUrl, AzureEnvironment azureEnvironment, String clientId, String redirectUrl, Boolean onPrem, InitializationType initializationType)
                           at PnP.PowerShell.Commands.Base.ConnectOnline.ConnectCredentials(PSCredential credentials, InitializationType initializationType) in
                        c:\build\src\Commands\Base\ConnectOnline.cs:line 514
                           at PnP.PowerShell.Commands.Base.ConnectOnline.Connect(CancellationToken& cancellationToken) in c:\build\src\Commands\Base\ConnectOnline.cs:line 260
                           at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() in c:\build\src\Commands\Base\ConnectOnline.cs:line 210
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], FileLoadException
FullyQualifiedErrorId : System.IO.FileLoadException,PnP.PowerShell.Commands.Base.ConnectOnline
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

Can someone tell me where the error is?

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.1
da15b6fd3ef856477bf6f4fb29ba1b7af717770d
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

Connect-PnPOnline -Url https://xxx.sharepoint.com/sites/zhs-dokumente -Credentials $userCredential2

**Comment by gitulm** [comment]
I think I found the problem. If I integrate the Exchange environment into my Powershell profile:
Connect-ExchangeOnline -Credential $userCredential2
after that PnP Powershell doesn't work properly anymore.
