### ISSUE TITLE
PSIC> spam when using Stop button with -ErrorAction Break and nested scopes

### ISSUE THREAD

**Issue by ninmonkey** [PowerShell/vscode-powershell#4010]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

The `stop` button in the UI causes the `PSIC>` error, 100% of the time.
When paused in a break point:

![image](https://user-images.githubusercontent.com/3892031/172030376-2fd316b5-7fd4-4fb1-ab2a-1db1a67e4d44.png)

- click continue, and everything works
- click stop, it breaks

![image](https://user-images.githubusercontent.com/3892031/172030373-a780f9b3-321a-44f5-96ca-afe4656a4462.png)

The callstack is always the same

```csharp
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

## Maybe Related or Not?

> This is complicated. The reason it started happening is that we synced the state of the PowerShell debugger and the VS Code debugger. We did this by essentially checking on each REPL if the PowerShell debugger was still running; if not, we stop the VS Code debugger. This seems to be the edge case where that behavior is _not_ wanted, so we need another condition, but it's a whole lot of complex state tracking.

_Originally posted by @andschwa in https://github.com/PowerShell/vscode-powershell/issues/3998#issuecomment-1145388239_ 

>  or fix it so that issuing a command doesn't stop the debugger @JustinGrote 

Does command "issue a command" mean running commands in the REPL? Or Clicking stop on the UI? For this case, when paused in a breakpoint:

- I can continue to use to use the PSIT REPL, as normal
- hitting `f5` or `continue` it works as normal
- it's only when I click `stop` that it explodes.  

### PowerShell Version

```console
Name                      Value
----                      -----
PSVersion                 7.2.4
PSEdition                 Core
GitCommitId               7.2.4
OS                        Microsoft Windows 10.0.19043
Platform                  Win32NT
PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion      1.1.0.1
WSManStackVersion         3.0
```

### Visual Studio Code Version

```console
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

## To Recreate: Stop on -EA 'break' plus nested Scope

This one breaks 100% of the time, even on new windows

```ps1
function doWork {
    if ($true) {
        Write-Error 'normally -Continue'
        <#
        while in the breakpoint:
             hit continue -> normal behavior
             click stop -> PSIC spam.
        #>
    }
    'other stuff'
}
if ($true) {
    & {

        $ErrorActionPreference = 'break'
        doWork
    }
}
``` 

![image](https://user-images.githubusercontent.com/3892031/172030376-2fd316b5-7fd4-4fb1-ab2a-1db1a67e4d44.png)

## Example2 : Sometimes breaks

I ran this 5 times in a row. They were okay until the 5th time it crashed.

```ps1 
if ($true) {
    & {
        $ErrorActionPreference = 'break'
        $x = 0; $x; # breakpoint here
        $ErrorActionPreference = 'stop'
    }
}
```

## Example that Works: No Nested Scope, No Crash

![image](https://user-images.githubusercontent.com/3892031/172030778-62a9355e-3934-42bd-9957-f2b6cf3889b9.png)

```ps1
if ($true) {
    $ErrorActionPreference = 'break'
    $x = 0 # breakpoint here
    $ErrorActionPreference = 'stop'
}
```

### Logs

[2022-06-03-editorservicesPSICspam.zip](https://github.com/PowerShell/vscode-powershell/files/8839165/2022-06-03-editorservicesPSICspam.zip)

**Comment by ninmonkey** [comment]
from the zip's iter2's logs:

### Double dots

Two functions are showing as double dots
```log
at System.Management.Automation.WildcardPatternMatcher..ctor(WildcardPattern wildcardPattern)
```

### Local Path 

```
at Microsoft.PowerShell.EditorServices.Services.SymbolsService.FindParameterSetsInFileAsync(
    ScriptFile file, Int32 lineNumber, Int32 columnNumber)
    in D:\a\_work\1\s\src\PowerShellEditorServices\Services\Symbols\SymbolsService.cs:line 342
```
> D:\a\_work\1\s\src\

- this path doesn't exist, is this a problem?
- Could that be related to the editorservices missing path error?

## `extension-host.log` - Runspaces.RunspaceBase.DoConcurrentCheckAndMarkSessionStateProxyCallInProgress()

<details><summary>PSInvalidOperationBaseException  (Click to Expand)

```log
[2022-06-04 11:54:50.507] [exthost] [error] [ms-vscode.powershell] provider FAILED
[2022-06-04 11:54:50.507] [exthost] [error] Error: Internal Error - System.Management.Automation.PSInvalidOperationException: A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndMarkSessionStateProxyCallInProgress()
   at System.Management.Automation.Runspaces.RunspaceBase.get_InvokeCommand()
   at System.Management.Automation.Runspaces.SessionStateProxy.get_InvokeCommand()
```

</summary>

```log
[2022-06-04 11:54:50.507] [exthost] [error] [ms-vscode.powershell] provider FAILED
[2022-06-04 11:54:50.507] [exthost] [error] Error: Internal Error - System.Management.Automation.PSInvalidOperationException: A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndMarkSessionStateProxyCallInProgress()
   at System.Management.Automation.Runspaces.RunspaceBase.get_InvokeCommand()
   at System.Management.Automation.Runspaces.SessionStateProxy.get_InvokeCommand()
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CommandHelpers.<>c.<GetAliasesAsync>b__8_0(PowerShell pwsh, CancellationToken _) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\CommandHelpers.cs:line 192
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPSDelegateTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousDelegateTask.cs:line 127
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 102
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CommandHelpers.GetAliasesAsync(IInternalPowerShellExecutionService executionService) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\CommandHelpers.cs:line 211
```


</details>



## `extension-host.log` - Crash on Provider Wildcard

<details><summary>provider failed  (Click to Expand)

```log
[2022-06-04 11:53:50.211] [exthost] [error] [ms-vscode.powershell] provider FAILED
[2022-06-04 11:53:50.211] [exthost] [error] Error: Internal Error - System.Management.Automation.CmdletInvocationException: The specified wildcard character pattern is not valid: []
 ---> System.Management.Automation.WildcardPatternException: The specified wildcard character pattern is not valid: []
   at System.Management.Automation.WildcardPatternParser.Parse(WildcardPattern pattern, WildcardPatternParser parser)
```

</summary>

```log
[2022-06-04 11:52:52.361] [exthost] [info] ExtensionService#_doActivateExtension mechatroner.rainbow-csv, startup: false, activationEvent: 'onLanguage:plaintext'
[2022-06-04 11:53:03.745] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.powershell, startup: false, activationEvent: 'onLanguage:powershell'
[2022-06-04 11:53:50.211] [exthost] [error] [ms-vscode.powershell] provider FAILED
[2022-06-04 11:53:50.211] [exthost] [error] Error: Internal Error - System.Management.Automation.CmdletInvocationException: The specified wildcard character pattern is not valid: []
 ---> System.Management.Automation.WildcardPatternException: The specified wildcard character pattern is not valid: []
   at System.Management.Automation.WildcardPatternParser.Parse(WildcardPattern pattern, WildcardPatternParser parser)
   at System.Management.Automation.WildcardPatternMatcher.MyWildcardPatternParser.Parse(WildcardPattern pattern, CharacterNormalizer characterNormalizer)
   at System.Management.Automation.WildcardPatternMatcher..ctor(WildcardPattern wildcardPattern)
   at System.Management.Automation.WildcardPattern.Init()
   at System.Management.Automation.CommandSearcher.GetNextAlias()
   at System.Management.Automation.CommandSearcher.SearchForAliases()
   at System.Management.Automation.CommandSearcher.MoveNext()
   at Microsoft.PowerShell.Commands.GetCommandCommand.FindCommandForName(SearchResolutionOptions options, String commandName, Boolean isPattern, Boolean emitErrors, Int32& currentCount, Boolean& isDuplicate)
   at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands(IEnumerable`1 commandNames)
   at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands()
   at Microsoft.PowerShell.Commands.GetCommandCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 76
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeCommand[TResult](PowerShell pwsh, PSCommand psCommand, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 99
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 124
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 68
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 91
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CommandHelpers.GetCommandInfoAsync(String commandName, IRunspaceInfo currentRunspace, IInternalPowerShellExecutionService executionService, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\CommandHelpers.cs:line 101
   at Microsoft.PowerShell.EditorServices.Services.SymbolsService.FindParameterSetsInFileAsync(ScriptFile file, Int32 lineNumber, Int32 columnNumber) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\Symbols\SymbolsService.cs:line 342
   at Microsoft.PowerShell.EditorServices.Handlers.PsesSignatureHelpHandler.Handle(SignatureHelpParams request, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\SignatureHelpHandler.cs:line 51
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
	at Ve (c:\Users\cppmo_000\.vscode\extensions\ms-vscode.powershell-2022.5.1\out\main.js:17:223)
	at Ue (c:\Users\cppmo_000\.vscode\extensions\ms-vscode.powershell-2022.5.1\out\main.js:16:11253)
	at Immediate.<anonymous> (c:\Users\cppmo_000\.vscode\extensions\ms-vscode.powershell-2022.5.1\out\main.js:16:11103)
	at processImmediate (node:internal/timers:464:21)
```

</details>


## `window.log`

<details><summary> 
Wildcard Not Valid 

```log
[2022-06-04 11:53:50.225] [renderer8] [error] Internal Error - System.Management.Automation.CmdletInvocationException: The specified wildcard character pattern is not valid: []
 ---> System.Management.Automation.WildcardPatternException: The specified wildcard character pattern is not valid: []
```
(Click to Expand)
</summary>

```log
[2022-06-04 11:53:50.225] [renderer8] [error] Internal Error - System.Management.Automation.CmdletInvocationException: The specified wildcard character pattern is not valid: []
 ---> System.Management.Automation.WildcardPatternException: The specified wildcard character pattern is not valid: []
   at System.Management.Automation.WildcardPatternParser.Parse(WildcardPattern pattern, WildcardPatternParser parser)
   at System.Management.Automation.WildcardPatternMatcher.MyWildcardPatternParser.Parse(WildcardPattern pattern, CharacterNormalizer characterNormalizer)
   at System.Management.Automation.WildcardPatternMatcher..ctor(WildcardPattern wildcardPattern)
   at System.Management.Automation.WildcardPattern.Init()
   at System.Management.Automation.CommandSearcher.GetNextAlias()
   at System.Management.Automation.CommandSearcher.SearchForAliases()
   at System.Management.Automation.CommandSearcher.MoveNext()
   at Microsoft.PowerShell.Commands.GetCommandCommand.FindCommandForName(SearchResolutionOptions options, String commandName, Boolean isPattern, Boolean emitErrors, Int32& currentCount, Boolean& isDuplicate)
   at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands(IEnumerable`1 commandNames)
   at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands()
   at Microsoft.PowerShell.Commands.GetCommandCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 76
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeCommand[TResult](PowerShell pwsh, PSCommand psCommand, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 99
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 124
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 68
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 91
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CommandHelpers.GetCommandInfoAsync(String commandName, IRunspaceInfo currentRunspace, IInternalPowerShellExecutionService executionService, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\CommandHelpers.cs:line 101
   at Microsoft.PowerShell.EditorServices.Services.SymbolsService.FindParameterSetsInFileAsync(ScriptFile file, Int32 lineNumber, Int32 columnNumber) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\Symbols\SymbolsService.cs:line 342
   at Microsoft.PowerShell.EditorServices.Handlers.PsesSignatureHelpHandler.Handle(SignatureHelpParams request, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\SignatureHelpHandler.cs:line 51
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext(): Error: Internal Error - System.Management.Automation.CmdletInvocationException: The specified wildcard character pattern is not valid: []
 ---> System.Management.Automation.WildcardPatternException: The specified wildcard character pattern is not valid: []
   at System.Management.Automation.WildcardPatternParser.Parse(WildcardPattern pattern, WildcardPatternParser parser)
   at System.Management.Automation.WildcardPatternMatcher.MyWildcardPatternParser.Parse(WildcardPattern pattern, CharacterNormalizer characterNormalizer)
   at System.Management.Automation.WildcardPatternMatcher..ctor(WildcardPattern wildcardPattern)
   at System.Management.Automation.WildcardPattern.Init()
   at System.Management.Automation.CommandSearcher.GetNextAlias()
   at System.Management.Automation.CommandSearcher.SearchForAliases()
   at System.Management.Automation.CommandSearcher.MoveNext()
   at Microsoft.PowerShell.Commands.GetCommandCommand.FindCommandForName(SearchResolutionOptions options, String commandName, Boolean isPattern, Boolean emitErrors, Int32& currentCount, Boolean& isDuplicate)
   at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands(IEnumerable`1 commandNames)
   at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands()
   at Microsoft.PowerShell.Commands.GetCommandCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 76
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeCommand[TResult](PowerShell pwsh, PSCommand psCommand, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 99
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 124
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 68
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 91
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CommandHelpers.GetCommandInfoAsync(String commandName, IRunspaceInfo currentRunspace, IInternalPowerShellExecutionService executionService, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\CommandHelpers.cs:line 101
   at Microsoft.PowerShell.EditorServices.Services.SymbolsService.FindParameterSetsInFileAsync(ScriptFile file, Int32 lineNumber, Int32 columnNumber) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\Symbols\SymbolsService.cs:line 342
   at Microsoft.PowerShell.EditorServices.Handlers.PsesSignatureHelpHandler.Handle(SignatureHelpParams request, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\SignatureHelpHandler.cs:line 51
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
	at Ve (c:\Users\cppmo_000\.vscode\extensions\ms-vscode.powershell-2022.5.1\out\main.js:17:223)
	at Ue (c:\Users\cppmo_000\.vscode\extensions\ms-vscode.powershell-2022.5.1\out\main.js:16:11253)
	at Immediate.<anonymous> (c:\Users\cppmo_000\.vscode\extensions\ms-vscode.powershell-2022.5.1\out\main.js:16:11103)
	at processImmediate (node:internal/timers:464:21)
```
</details>
