### ISSUE TITLE
Error on Integrated Console Start - PSInvalidOperationException Pipeline Issue

### ISSUE THREAD

**Issue by dgcode** [PowerShell/vscode-powershell#4048]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml        
Thank you!

### Environment
PSReadLine: 2.2.5
PowerShell: 2022.6.1
OS: Microsoft Windows 10.0.19044
BufferWidth: 196
BufferHeight: 22

Last 0 Keys:



### Exception

System.Management.Automation.PSInvalidOperationException: The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently.
   at System.Management.Automation.Runspaces.PipelineBase.DoConcurrentCheck(Boolean syncCall, Object syncObject, Boolean isInLock)
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndAddToRunningPipelines(PipelineBase pipeline, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 76
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeCommand[TResult](PowerShell pwsh, PSCommand psCommand, PSInvocationSettings invocationSettings) in 
D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 99
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 119
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 70
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 92
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.get_Result() in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 58
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteAndGetResult(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 108
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokePSCommand[TResult](PSCommand psCommand, PowerShellExecutionOptions executionOptions, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 432
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokePSCommand(PSCommand psCommand, PowerShellExecutionOptions executionOptions, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 435
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.OnPowerShellIdle(CancellationToken idleCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 1078
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://user-images.githubusercontent.com/12691691/175834731-52c111a3-854b-4bab-9dd1-00dd2dbcbd54.png)

### Environment data

```console
PS Version: 7.2.5
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 121
BufferHeight: 65
```

### Steps to reproduce

* Start VS Code
* Open a PowerShell script/launch the integrated console

### Expected behavior

* Console should start with no issues

### Actual behavior

* Console continuously spits out the stated error
* Regular commands can be run without issue

**Comment by andschwa** [comment]
What happens if you load without profiles?

**Comment by dgcode** [comment]
The terminal loads without issue.

Following this thread further, I narrowed down the issue to the following:
```ps1
# Attempt to load and start Az Predictor
try {
    if ($PSVersionTable.PSVersion.Major -gt 5) {
        Import-Module Az.Tools.Predictor
        Set-PSReadLineOption -PredictionSource History
    }
}
catch {
    Write-Warning "An Error occurred loading Az Predictor: $($Error[0].Exception.Message)" 
}
```

Since these specific cmdlets were from when Az.Tools.Predictor was in preview, I thought I'd check the [documentation](https://docs.microsoft.com/en-us/powershell/azure/az-predictor?view=azps-8.0.0#enable-az-predictor) and can see that they recommend a different approach to starting it:

```ps1
# Attempt to load and start Az Predictor
try {
    if ($PSVersionTable.PSVersion.Major -gt 5) {
        Enable-AzPredictor -AllSession
        Set-PSReadLineOption -PredictionViewStyle InlineView
    }
}
catch {
    Write-Warning "An Error occurred loading Az Predictor: $($Error[0].Exception.Message)" 
}
```

Tried this which resulted in the same error.

**Comment by andschwa** [comment]
Try taking out the `Write-Warning`. I have a hunch that won't work in a profile on startup of the extension.

**Comment by dgcode** [comment]
Can confirm that even with a Write-Host, it still errors:
![image](https://user-images.githubusercontent.com/12691691/176051816-7a7cbe95-483e-401f-8d78-5e63b8ec2324.png)

And with no exception handling:
![image](https://user-images.githubusercontent.com/12691691/176052244-f9be2b1f-e627-4e5c-97a2-afac63da4e13.png)

**Comment by andschwa** [comment]
How about narrowing it down between: `Import-Module Az.Tools.Predictor` and `Set-PSReadLineOption -PredictionViewStyle InlineView`?

**Comment by dgcode** [comment]
With just those two lines in the profile, I still get the issue on version `2022.5.0` and above:
![image](https://user-images.githubusercontent.com/12691691/176327196-1065c1cb-aa8d-478b-93b8-173bfa9d76d0.png)

**Comment by dgcode** [comment]
Details on the version of Az.Tools.Predictor I am using in case it's helpful:
![image](https://user-images.githubusercontent.com/12691691/176328017-63b41c01-cec0-4993-8955-eac6eaddcbce.png)

**Comment by andschwa** [comment]
I think you'll need to not import `Az.Tools.Predictor` when your host is the PSIC, seems broken.

**Comment by andschwa** [comment]
Or set `[Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictorData]::ShowSurveyOnIdle = $False`?

**Comment by andschwa** [comment]
Sounds like @SeeminglyScience might have a fix.

**Comment by dgcode** [comment]
Re-opening, have already provided repro info.

**Comment by andschwa** [comment]
Idea from Patrick: "When we create the initial PowerShell instance, we need to mark it as nested with RunspaceMode.CurrentRunspace. Will probably through an exception, will need to temporarily set a default runspace while we mark it as nested." Currently being done elsewhere in the code. In most cases we don't use the initial instance. Because this is being loaded in the profile specifically, it's hitting an OnIdle run before we've ran something else, hence using the non-nested runspace and failing.

**Comment by andschwa** [comment]
@dgcode I think I have a fix, I need to have @SeeminglyScience review it and then we'll test it with you in Preview.

**Comment by dgcode** [comment]
Sounds good, cheers!
