### ISSUE TITLE
Code action requests from other extensions crash the language server

### ISSUE THREAD

**Issue by itzik-h** [PowerShell/vscode-powershell#408]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: win 7x64
- VS Code version: 1.8.0, 1.8.1
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

PowerShell extension is terminating continuously (after each restart vie the new option to restart).
I could not find any specific action that triggers this.

### Attached Logs

[1482223271-ffd84f24-843f-4fa6-9ca4-8121f1d74e961482222573215.zip](https://github.com/PowerShell/vscode-powershell/files/663252/1482223271-ffd84f24-843f-4fa6-9ca4-8121f1d74e961482222573215.zip)

**Comment by daviwil** [comment]
Hey @itzik-h, I see what's going on in the logs but I am a little surprised at what is happening.  Could you [turn on verbose logging](https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us), reproduce the issue, and send me your logs again?  It'd help me understand what VS Code is sending which is causing the problem.  At any rate, we'll definitely get this fixed for tomorrow's patch release!

**Comment by itzik-h** [comment]
The log contains lots of sensitive information.
Using the Verbose logs I think I have narrowed it down to some interop with a spellchecker plugin `streetsidesoftware.code-spell-checker`.
log snippet:
```
20/12/2016 17:51:04 [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 16,
      "method": "textDocument/codeAction",
      "params": {
        "textDocument": {
          "uri": "file:///removed_path.ps1"
        },
        "range": {
          "start": {
            "line": 6,
            "character": 18
          },
          "end": {
            "line": 6,
            "character": 32
          }
        },
        "context": {
          "diagnostics": [
            {
              "range": {
                "start": {
                  "line": 6,
                  "character": 18
                },
                "end": {
                  "line": 6,
                  "character": 32
                }
              },
              "message": "Unknown word: \"sdfgsdfgsdfg\"",
              "severity": 3,
              "source": "cSpell Checker"
            }
          ]
        }
      }
    }

20/12/2016 17:51:04 [ERROR] - Method "OnListenTaskCompleted" at line 337 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
    Parameter name: key
       at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
       at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCodeActionRequest>d__38.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__34.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
    Parameter name: key
       at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
       at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleCodeActionRequest>d__38.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__34.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
```
When ever there is a typo in the code - PowerShellEditorServices crushes.
I must have lots of typos :) as disabling this plugin stooped the problem.

**Comment by daviwil** [comment]
Thanks for sending that, it's exactly what I needed to see.  Weird that they're sending us requests for the markers of a different extension!  Looks like I'll need to ignore anything code action request with a `source` that I don't recognize.

**Comment by rkeithhill** [comment]
I wonder if that is a VSCode bug?

**Comment by daviwil** [comment]
Yeah, it's a possibility. I might file an issue over there to see what they say about it.
