### ISSUE TITLE
2022-11-10 15:41:59.871 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}

### ISSUE THREAD

**Issue by penalvch** [PowerShell/vscode-powershell#4254]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

What is expected to happen with Windows 11 ARM in a UTM guest, macOS host wifi connected to a 5G router (e.g. higher average latency/jitter than wired ISPs) with excellent WiFi signal to/from router, is that when opening Visual Studio Code for the first time and immediately try to install the Powershell extension, it installs successfully with no issues.

What happens instead, is it consistently fails, despite able to navigate websites via Microsoft Edge in Windows (e.g. internet working fine).

As per below extension install failure log, this issue appears to be either the upstream endpoint may be busted, or is configured such that if there is too much latency/jitter it considers this effectively not connected to the internet and stops the attempt.

Guest OS Details:
- Windows 11 for ARM
```
[environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.25227.0 Microsoft Windows NT 10.0.25227.0

(Get-CimInstance Win32_operatingsystem).OSArchitecture
ARM 64-bit Processor
```
- UTM
![image](https://user-images.githubusercontent.com/115644052/201204465-e2e9e507-d0fa-4f2d-b4e4-8a706e6b2b45.png)

Host Details:
```
[environment]::OSVersion

Platform ServicePack Version VersionString
-------- ----------- ------- -------------
    Unix             13.0.0  Unix 13.0.0

sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Apple M1
```

Failure log:
```
2022-11-10 15:40:54.436 [info] The pty host became responsive again
2022-11-10 15:41:33.864 [info] [perf] Render performance baseline is 323ms
2022-11-10 15:41:38.557 [info] UNRESPONSIVE extension host: received responsive event and cancelling profiling session
2022-11-10 15:41:39.196 [info] UNRESPONSIVE extension host: starting to profile NOW
2022-11-10 15:41:59.871 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
2022-11-10 15:42:19.150 [error] Error: XHR failed
    at b.onerror (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:57655)
2022-11-10 15:42:21.955 [error] XHR failed: Error: XHR failed
    at b.onerror (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:57655)
2022-11-10 15:46:02.435 [error] Canceled: Canceled
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:11392
    at v.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:145)
    at p.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:2266)
    at y.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:1844)
    at T.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:6732)
    at L.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:7273)
    at Object.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:11544)
    at V.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:105175)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:92712
    at Array.forEach (<anonymous>)
    at $.installExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:92690)
    at async $.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86873)
2022-11-10 15:46:02.637 [error] Canceled: Canceled: Canceled
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:11392
    at v.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:145)
    at p.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:2266)
    at y.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:1844)
    at T.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:6732)
    at L.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:7273)
    at Object.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:11544)
    at V.cancel (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:105175)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:92712
    at Array.forEach (<anonymous>)
    at $.installExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:92690)
    at async $.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86873)
```

### PowerShell Version

```console
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.25227.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.25227.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
code --version
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell
```

### Steps to Reproduce

SEE SUMMARY

### Visuals

SEE SUMMARY

### Logs

NOT APPLICABLE AS NOT INSTALLED YET TO GET LOGS

**Comment by andschwa** [comment]
Hi, can you file this with VS Code? The extension doesn't control the installation process. Thanks!

**Comment by penalvch** [comment]
Hi @andschwa, no problem and thanks for the quick response!
