### ISSUE TITLE
Teams Code connect

### ISSUE THREAD

**Issue by ivanja81** [PowerShell/vscode-powershell#4402]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

https://github.com/microsoft/vscode/issues/173211

Looks to me it doesn't like the path as when i change path the issue is not there.

PS C:\Users\ivanja\OneDrive - Microsoft\Desktop\SFBTEAMSScripts> Connect-MicrosoftTeams
RuntimeException: Unable to find type [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IGetGroupsResponse].
at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
at System.Management.Automation.Language.Compiler.NewOutputTypeAttribute(AttributeAst ast)
at System.Management.Automation.Language.Compiler.GetAttribute(AttributeAst attributeAst)
at System.Management.Automation.Language.ScriptBlockAst.d__68.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source) at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata() at System.Management.Automation.ScriptBlock.get_Attributes() at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.<ProcessRecord>b__16_0(FunctionInfo fi) at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source) at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord() RuntimeException: Unable to find type [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IGetGroupsResponse]. at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos) at System.Management.Automation.Language.Compiler.NewOutputTypeAttribute(AttributeAst ast) at System.Management.Automation.Language.Compiler.GetAttribute(AttributeAst attributeAst) at System.Management.Automation.Language.ScriptBlockAst.<System-Management-Automation-Language-IParameterMetadataProvider-GetScriptBlockAttributes>d__68.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
at System.Management.Automation.ScriptBlock.get_Attributes()
at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.b__16_0(FunctionInfo fi)
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()
RuntimeException: Unable to find type [Microsoft.Teams.ConfigAPI.Cmdlets.Models.AccountType].
at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst)
at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding) at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata() at System.Management.Automation.ScriptBlock.get_Attributes() at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.<ProcessRecord>b__16_0(FunctionInfo fi) at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source) at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord() RuntimeException: Unable to find type [Microsoft.Teams.ConfigApi.Cmdlets.FlightingUtils+OverrideFlightMode]. at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos) at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst) at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding) at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
at System.Management.Automation.ScriptBlock.get_Attributes()
at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.b__16_0(FunctionInfo fi)
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()

### PowerShell Version

```console
PS C:\Users\ivanja\TeamsApps\stocks-update-notification-bot> $psVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  963
```

### Visual Studio Code Version

```console
PS C:\Users\ivanja\TeamsApps\stocks-update-notification-bot> code --version
1.75.0
e2816fe719a4026ffa1ee0189dc89bdfdbafb164
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.1.0
ms-vscode.powershell-preview@2023.2.0
tobysmith568.run-in-powershell@1.1.1
```

### Steps to Reproduce

connect-microsoftteams in code

**Comment by SydneyhSmith** [comment]
Thanks @ivanja81 what path are you referring to?
