### ISSUE TITLE
Installation -> CorruptZip: end of central directory record signature not found

### ISSUE THREAD

**Issue by alexanderarnst** [PowerShell/vscode-powershell#4474]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hi guys,

I have fresh installed VS Code and try to install the Powershell extension from MS. Unfortunatelly there is just an error, that the downloaded Zip is corrupted. No infromation about which URL was accessed, nor where to find the corrupted Zip File... Any ideas? Other extensions, like the "poweshellprotools" installs with not problems.

2023-03-23 08:55:50.456 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:55:50.476 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)

Thanks a lot in advance.
Alexander

### PowerShell Version

```console
PS C:\Users\860000165> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
PS C:\Users\860000165> code --version
1.76.2
ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
x64
```

### Extension Version

```console
PS C:\Users\860000165> code --list-extensions --show-versions | Select-String powershell

ironmansoftware.powershellprotools@2023.3.0
```

### Steps to Reproduce

1. Open VS Code -> Extensions
2. Search for powershell Extension from MS
3. Click the "Install" button.
4. The error appears in the Output window.

### Visuals

![image](https://user-images.githubusercontent.com/78720525/227140459-bf15bd94-bcf7-4778-9bac-4262306e03de.png)

### Logs

2023-03-23 08:44:05.389 [info] Electron sandbox mode is enabled!
2023-03-23 08:44:07.678 [warning] Settings pattern "application.*" doesn't match any settings
2023-03-23 08:44:15.640 [warning] Settings pattern "application.*" doesn't match any settings
2023-03-23 08:44:18.632 [warning] Settings pattern "application.*" doesn't match any settings
2023-03-23 08:44:20.589 [warning] Settings pattern "application.*" doesn't match any settings
2023-03-23 08:44:22.268 [info] [perf] Render performance baseline is 141ms
2023-03-23 08:44:22.685 [warning] Settings pattern "application.*" doesn't match any settings
2023-03-23 08:44:24.994 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:44:25.008 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:52:39.743 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:52:39.780 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:52:47.432 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:52:47.435 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:54:06.547 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:54:06.598 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:54:08.347 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:54:08.350 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:54:23.337 [warning] Settings pattern "application.*" doesn't match any settings
2023-03-23 08:55:32.049 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:55:32.071 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:55:49.417 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:55:49.438 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:55:50.456 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 08:55:50.476 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async X.x (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/860000165/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)

**Comment by andschwa** [comment]
I would try restarting VS Code, clearing any cache it has if possible, and trying again. My guess is it just got corrupted when downloading (like a transient network or disk issue), as I haven't otherwise heard of this being an issue (and I would expect to given the amount of users it has).

**Comment by dramerus** [comment]
I also have this issue, with both my local and portable installs. The only resolution that seemed to work was manually downloading the .vsix file and installing it that way. 

Waiting to see if it will upgrade with the next release or if I'll need to manually upgrade moving forward.

**Comment by Mehdi-Dehghan** [comment]
I've been having the same issue with any extension and I tried to use downloaded .vsix files. but the vscode showed "end of central directory record signature not found"!

**Comment by andschwa** [comment]
Interesting...I'm trying to get a new pre-release out today for you guys to try. I wonder if just a bad upload happened.

**Comment by andschwa** [comment]
Hey all, a new pre-release is installed. Can you try again?

Thanks!

**Comment by andschwa** [comment]
Since this recently changed (the separate "Preview" extension is no more) that means going to the "PowerShell" extension in the marketplace within VS Code and clicking this "Switch to Pre-Release Version" button:

<img width="783" alt="Screenshot 2023-03-27 at 5 00 07 PM" src="https://user-images.githubusercontent.com/2226434/228093082-5a965264-dc09-4f02-82c3-f78a24db73c2.png">

**Comment by alexanderarnst** [comment]
Hi guys,

thanks a lot for your help. Unfortunatelly there is still the same error, installing the „Pre-Release“ Version.

***@***.***

Any idea? Thanks a lot again to you all and Andy! ☺

Best regards,
Alexander


Von: Andy Jordan ***@***.***>
Gesendet: Dienstag, 28. März 2023 02:02
An: PowerShell/vscode-powershell ***@***.***>
Cc: Arnst, Alexander (OWL-IT) ***@***.***>; Author ***@***.***>
Betreff: Re: [PowerShell/vscode-powershell] Installation -> CorruptZip: end of central directory record signature not found (Issue #4474)


Since this recently changed (the separate "Preview" extension is no more) that means going to the "PowerShell" extension in the marketplace within VS Code and clicking this "Switch to Pre-Release Version" button:

[Screenshot 2023-03-27 at 5 00 07 PM]<https://user-images.githubusercontent.com/2226434/228093082-5a965264-dc09-4f02-82c3-f78a24db73c2.png>

**Comment by andschwa** [comment]
Hm...what happens if you download the VSIX file from here: https://github.com/PowerShell/vscode-powershell/releases/tag/v2023.3.2-preview

and install it "manually" that is in the VS Code Command picker, choose "Extensions: Install from VSIX" and then point it to the downloaded VSIX.

**Comment by alexanderarnst** [comment]
Hmm, still there is an error in downloading the vspackage.

***@***.***

When I click on the „Try Downloading Manually…“ this error response appears:

***@***.***


So I guess, our company has blocked these kind of packages.

Thanks a lot for your time and help.

BR,
Alexander


Von: Andy Jordan ***@***.***>
Gesendet: Dienstag, 28. März 2023 20:45
An: PowerShell/vscode-powershell ***@***.***>
Cc: Arnst, Alexander (OWL-IT) ***@***.***>; Author ***@***.***>
Betreff: Re: [PowerShell/vscode-powershell] Installation -> CorruptZip: end of central directory record signature not found (Issue #4474)


So this looks eerily similar to issues reported with the Python extension here microsoft/vscode-python#17491<https://github.com/microsoft/vscode-python/issues/17491> and upstream here microsoft/vscode#131022<https://github.com/microsoft/vscode/issues/131022>. The only extension dependency we have is the built-in "powershell" extension (that just installs a basic grammar, and is part of VS Code). I'd like to follow their guess about corrupted downloads in VS Code's user data folder.

So a way to test this would be to open Code from the command line with a flag like this: code --user-data-dir <some random test folder> so that Code opens with a fresh (and empty) user data directory.

**Comment by andschwa** [comment]
Ahh, interesting. I'm sorry about that! I can't think of a good workaround other than contacting your IT department and explaining you need to download VSIX packages as part of your workflow.

**Comment by andschwa** [comment]
@dramerus if you're at least able to download the VSIX, then I think your issue is just a corrupted download in your existing user data folder. I'm...not sure how to fix that. Theoretically you could clear VS Code's cache? I'd try checking its user data folder for anything mentioning "extensions," deleting them, and then reinstalling them (you could be extra careful and just try to delete the PowerShell extensions). Hope that works! Fortunately it's not a huge deal to re-download extensions, as their settings are saved separately (in your user `settings.json` file).

**Comment by MarkoCharqueno** [comment]
I was able to work around this issue by deleting the following folders .
`C:\Users\UserName\AppData\Roaming\Code\CachedExtensionVSIXs`
`C:\Users\UserName\AppData\Roaming\Code\CachedData`

Attempting to download and install the VSIX directly produced the same error, so I assume vscode ignores the download if there is already a VSIX cached.

**Comment by JamesAMartin** [comment]
I am building out a new system, clean install of everything, and am running into the same issues with trying to install the PowerShell module in VSCode.  Trying all of the suggestions above, I am continually getting the "Corupt ZIP: end of central directory record signature not found" error.  

I am able to download the VSIX clean (I think) but even the manual install of it does not work, even after uninstalling all other extensions (Git Graph was the only other installed so far) and deleting anything that looked like cache in the AppData\Roaming\Code folder.  Even starting with `code --user-data-dir <some random test folder>` made no difference.

On my old system, about a month ago I noticed the PowerShell extension needed an update, and I have not been able to get it to install on that system either.  I was expecting a clean install to work, but is seems to be something with VSCode or the PowerShell extension file.

Any help would be seriously appreciated.

**Comment by JamesAMartin** [comment]
andschwa,  

You are spot on with your suggestion.  I should have checked file size on the download, but as everything appeared to work properly, I did not suspect an issue.  It turns out that our firewalls were updated to protect against a vulnerability from a few months ago, and that has not been lifted yet.  It specifically targeted the PowerShell VSIX, but the firewalls were not updated after the vulnerability was fixed.  I've got network guys looking at it now.

Why the firewalls would allow any part of the file to download and not throw an exception to the user is a different question...

Thanks for the quick and excellent assistance!

**Comment by andschwa** [comment]
And I sure am curious _why_ they specifically blocked the PowerShell VSIX...I don't have any reports about vulnerabilities.

**Comment by JamesAMartin** [comment]
I have gotten a little more detail from our network guys...

We are using Palo Alto firewalls, and it appears they setup the initial restriction to help protect our systems.  Details of the vulnerability can be found at https://github.com/google/security-research/security/advisories/GHSA-pw56-c55x-cm9m.

Summary is below:
![image](https://user-images.githubusercontent.com/11860698/232144150-ffc85529-0b6b-4961-94ff-e1f664f558a7.png)

**Comment by andschwa** [comment]
Oh, I see. So it's a blanket ban on allowing VS Code to download VSIXs (meaning it breaks ours and all other non-built-in extensions). Fortunately, according to that CVE it was patched back in October 2022. As long as your VS Code version [v1.73.1](https://github.com/microsoft/vscode/releases/tag/1.73.1) or above it's no longer a threat. Since VS Code auto-updates, and you're likely already on the latest (1.77.3), your IT team can probably be convinced to allow VSIX downloads again (and thus allow marketplace extensions to be installed).

> Affected versions
> v1.4.0 - v1.71.1
> Patched versions
> v1.73.1

The only thing I don't get is why they blocked VSIX downloads...like, it doesn't have anything to do with the CVE as far as I can tell. That vulnerability existed in VS Code's built-in Jypiter Notebook's feature code.

**Comment by JamesAMartin** [comment]
The strange thing from my perspective, is that only the PowerShell extension seemed to be affected.  All of the others I tried installed with no problem.  Hopefully this will help someone else that has been bit by the same issue.

**Comment by andschwa** [comment]
That's so weird..._once upon a time_ the PowerShell extension shipped some Jypiter Notebook code too, but it was removed over a year ago. Maybe it's just because it contains PowerShell scripts and modules? Palo Alto is being a bit too "helpful" I think.

**Comment by MarkoCharqueno** [comment]
I experienced this issue with the C# extension as well, but no other extensions. So not entirely isolated to just the PowerShell extension.

**Comment by afsneto** [comment]
I've been having the same issue with any extension and I tried to use downloaded .vsix files. but the vscode showed "end of central directory record signature not found"!

`code --version
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64`

**Comment by andyleejordan** [comment]
Yes, it is most likely a problem with your proxy.

**Comment by afsneto** [comment]
> I was able to work around this issue by deleting the following folders . `C:\Users\UserName\AppData\Roaming\Code\CachedExtensionVSIXs` `C:\Users\UserName\AppData\Roaming\Code\CachedData`
> 
> Attempting to download and install the VSIX directly produced the same error, so I assume vscode ignores the download if there is already a VSIX cached.

Thank you so much, that worked! Finally, I can update/install extensions!

**Comment by Roymprog** [comment]
This was an issue with the proxy on my end as well. Make sure you can connect to all (relevant) domains on [this page](https://code.visualstudio.com/docs/setup/network).

**Comment by RacketyWater7** [comment]
thank you soo much guys for the wonderful suggestions
