### ISSUE TITLE
Extension randomly runs something in the background when writing in the code pane

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#4773]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

While writing PowerShell in the code pane the terminal suddenly seems to have ran something on my unfinished code, and must be exited with CTRL+C to stop.

<img width="632" alt="image" src="https://github.com/PowerShell/vscode-powershell/assets/6450056/8b33c1a9-0add-4a23-83c6-c2b683890660">

In this example I was going to write `Get-AzResource`, only got to `Get-AzResour` before a warning pops up saying `WARNING: Get-AzResour is not found. The most similar Azure PowerShell command is: Get-AzResource`.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.83.0
e7e037083ff4455cf320e344325dacb480062c3c
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

Write PowerShell in the code view, suddenly something (`vscode-powershell`? `PSReadLine`?) triggers something that outputs to the terminal.

### Visuals

See summary.

### Logs

Tried following https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#logs
But there's no log directory inside `%USERPROFILE%\.vscode\extensions\ms-vscode.powershell-2023.6.0`, even after I added following to `settings.json`:

```json
"powershell editor services.trace.server": "verbose",
"powershell.developer.editorServicesLogLevel": "Diagnostic"
```

**Comment by SydneyhSmith** [comment]
Thanks for letting us know about this @o-l-a-v , @StevenBucher98 do you think this is coming from a feedback provider?

**Comment by StevenBucher98** [comment]
Feedback providers are still in experimental so it would only affect it if the experimental feature was set to true. The text is from Az cmdlets own feedback system, tagging @dcaro if he thinks this may be an issue on their end. 

The fact it seemingly execute your command before you finish typing it is very weird. Does this happen with any other commands or just Az.* cmdlets?

**Comment by o-l-a-v** [comment]
@StevenBucher98 

This has just happened with the Az modules for me. Haven't done much work with other modules the last months.

**Comment by dcaro** [comment]
@Alex-wdy, @isra-fel PTAL, this seems to be related to the cmdlet discovery mechanism of Az 10.3 / Az.Accounts 2.13.0

**Comment by andyleejordan** [comment]
Sounds like this is not a VS Code extension bug at this point, is there an Az module issue we can reference and close this?

**Comment by o-l-a-v** [comment]
Happened again today. `Az.Accounts` v2.13.2 and `Az.SecurityInsights` loaded into VSCode with PowerShell v7.4.0, `vscode-powershell` v2023.8.0.

```
PS C:\Users\olav.birkeland\OneDrive\IT\Code> PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)       
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.PsHelpers.RunScript[T](CommandInvocationIntrinsics cii, String script)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.PsExtensions.RunScript[T](PSCmdlet cmdlet, String script)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.PsHelpers.GetScriptCmdlets(PSCmdlet cmdlet, String scriptFolder)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()
                                             ^C
PS C:\Users\olav.birkeland\OneDrive\IT\Code>
```

**Comment by isra-fel** [comment]
Thanks for reporting. Did `Resolve-AzError` not return anything?

@dolauli let's look into it tomorrow.

**Comment by o-l-a-v** [comment]
I have some bisarre errors from `Resolve-AzError`, don't know if they're related. Did not run `Resolve-AzError` right after it happened. Will do that next time.

First

```powershell
Message        : The term 'WhereWhere--OObbjjeecctt' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.MonitoringSolutions.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Get-ChildItem function: | Where-Object { ($currentFunctions -notcontains $_) -and $_.CmdletBinding }

Position       : At line:4 char:27
                 + Get-ChildItem function: | Where-Object { ($currentFunctions -notconta …
                 +                           ~~~~~~~~~~~~
HistoryId      : 39
```


Second

```powershell
Message        : Cannot find a provider with the name 'functionfunction'.
StackTrace     :    at System.Management.Automation.SessionStateInternal.GetProvider(PSSnapinQualifiedName providerName)
                    at System.Management.Automation.SessionStateInternal.GetSingleProvider(String name)
                    at System.Management.Automation.LocationGlobber.GetProviderPath(String path, CmdletProviderContext context, Boolean isTrusted, ProviderInfo& provider,
                 PSDriveInfo& drive)
                    at System.Management.Automation.SessionStateInternal.GetChildItems(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context)
                    at Microsoft.PowerShell.Commands.GetChildItemCommand.ProcessRecord()
Exception      : System.Management.Automation.ProviderNotFoundException
InvocationInfo : {Get-ChildItem}
Line           : $currentFunctions = Get-ChildItem function:

Position       : At line:2 char:21
                 + $currentFunctions = Get-ChildItem function:
                 +                     ~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 39
```

Third, I got a few of this one:

```powershell
Message        : The term 'GetGet--CChhiillddIItteemm' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.MonitoringSolutions.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Get-ChildItem -Path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom' -Recurse -Include '*.ps1' -File |
                 ForEach-Object { . $_.FullName }

Position       : At line:3 char:1
                 + Get-ChildItem -Path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\ …
                 + ~~~~~~~~~~~~~
HistoryId      : 39
```

**Comment by o-l-a-v** [comment]
This still happens from time to time. I think `Az.Tools.Predictor` is involved.

* <https://github.com/Azure/azure-powershell/tree/main/tools/Az.Tools.Predictor>
* <https://www.powershellgallery.com/packages/Az.Tools.Predictor>
* <https://learn.microsoft.com/en-us/powershell/azure/predictor-overview>
* <https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-general-availability-of-az-tools-predictor/ba-p/3297956>

I never use it intentionally, so I just removed it (the module `Az.Tools.Predictor`). Will report back if I still experience this.
