### ISSUE TITLE
Exception encountered starting EditorServices. Exception logged in C:\__w\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 239 in EndProcessing:

### ISSUE THREAD

**Issue by KevinWGagel** [PowerShell/vscode-powershell#5118]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Whenever I open VSCode with an open script that is using Windows PowerShell 5.1 OR switch to PowerShell 5.1 the terminal crashes and waits for me to press a key. After the key press, VSCode loads PowerShell 7.x.

`Exception encountered starting EditorServices. Exception logged in C:\__w\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 239 in EndProcessing:
System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Serilog.SerilogLoggerFactoryExtensions.AddSerilog(Microsoft.Extensions.Logging.ILoggerFactory, Serilog.ILogger, Boolean)'.
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesServerFactory.Create(String logDirectoryPath, Int32 minimumLogLevel, IObservable`1 hostLogger)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner..ctor(HostLogger logger, EditorServicesConfig config, ISessionFileWriter sessionFileWriter, IReadOnlyCollection`1 loggersToUnsubscribe)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesLoader.LoadAndRunEditorServicesAsync()
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

== Press any key to close terminal ==`

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.4391                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.4391                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.96.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

Open a PS Script and switch to PowerShell 5.1.

### Visuals

![Terminal Startup Error With PS 5 1 Error Message](https://github.com/user-attachments/assets/2722bdf9-eb05-44f5-b525-9b5d38c9a79b)
![Terminal Startup Error With PS 5 1](https://github.com/user-attachments/assets/d240c22e-7d64-4c50-b5a1-8c5dfad2cdcf)

### Logs

[PowerShellEditorServices-35808.log](https://github.com/user-attachments/files/18189045/PowerShellEditorServices-35808.log)
[PowerShellEditorServices-53948.log](https://github.com/user-attachments/files/18189046/PowerShellEditorServices-53948.log)
[StartEditorServices-35808.log](https://github.com/user-attachments/files/18189047/StartEditorServices-35808.log)
[StartEditorServices-48004.log](https://github.com/user-attachments/files/18189048/StartEditorServices-48004.log)
[StartEditorServices-52552.log](https://github.com/user-attachments/files/18189049/StartEditorServices-52552.log)
[StartEditorServices-53948.log](https://github.com/user-attachments/files/18189050/StartEditorServices-53948.log)
[vscode-powershell.log](https://github.com/user-attachments/files/18189051/vscode-powershell.log)
[StartEditorServices-22268.log](https://github.com/user-attachments/files/18189052/StartEditorServices-22268.log)
[PowerShellEditorServices-9424.log](https://github.com/user-attachments/files/18189053/PowerShellEditorServices-9424.log)
[StartEditorServices-9424.log](https://github.com/user-attachments/files/18189054/StartEditorServices-9424.log)
[StartEditorServices-52636.log](https://github.com/user-attachments/files/18189055/StartEditorServices-52636.log)
[PowerShellEditorServices-20056.log](https://github.com/user-attachments/files/18189056/PowerShellEditorServices-20056.log)
[StartEditorServices-20056.log](https://github.com/user-attachments/files/18189057/StartEditorServices-20056.log)
[PowerShellEditorServices-21664.log](https://github.com/user-attachments/files/18189058/PowerShellEditorServices-21664.log)
[StartEditorServices-23680.log](https://github.com/user-attachments/files/18189059/StartEditorServices-23680.log)
[StartEditorServices-21664.log](https://github.com/user-attachments/files/18189060/StartEditorServices-21664.log)

**Comment by KevinWGagel** [comment]
Yes, the pre-release resolved the issue for me.
Thank you.
