### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by kerry-perret** [PowerShell/vscode-powershell#699]
### System Details

- Operating system name and version: Windows 7 x64
- VS Code version: 1.11.2
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`:

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

Debugging does not work.
The issue is similar to this one: https://github.com/PowerShell/vscode-powershell/issues/469
Except that in my case restarting does not really help I start debugging it automatically crash seems the debugger cannot really properly connect.

### Attached Logs

**DebugAdapter.log**
```
Waiting for session file, tries remaining: 30...
Session file present, connecting to debug adapter...

Connecting to port: 19754
Socket ERROR: Error: connect ECONNREFUSED 127.0.0.1:19754
```

**vccode-powershell.log**

```
[10:21:33] Language server starting...
powershell.exe started --
powershell.exe started --
powershell.exe started --
powershell.exe started --
[10:21:35] Language server started.
Connecting to language service on port 26521...

Language service connected.


Shutting down language client...

Terminating PowerShell process...
```

**EditorServices.log**

```
4/10/2017 10:21:34 AM [NORMAL] - Method "StartLogging" at line 126 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    PowerShell Editor Services Host v0.12.1.0 starting (pid 15428)...
    
      Host application details:
    
        Name:      Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version:   1.0.0
        Arch:      64-bit
    
      Operating system details:
    
        Version: Microsoft Windows NT 6.1.7601 Service Pack 1
        Arch:    64-bit

4/10/2017 10:21:34 AM [NORMAL] - Method "Initialize" at line 214 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    PowerShell runtime version: 4.0, edition: Desktop

4/10/2017 10:21:34 AM [NORMAL] - Method "FindPSScriptAnalyzerModule" at line 261 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Analysis\AnalysisService.cs

    PSScriptAnalyzer found at C:\Users\eperret\.vscode\extensions\ms-vscode.powershell-0.12.2\modules\PSScriptAnalyzer\PSScriptAnalyzer.psd1

4/10/2017 10:21:35 AM [NORMAL] - Method "StartLanguageService" at line 160 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    Language service started, listening on port 26521

4/10/2017 10:21:35 AM [NORMAL] - Method "StartDebugService" at line 215 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    Debug service started, listening on port 14719

4/10/2017 11:10:11 AM [NORMAL] - Method "Shutdown" at line 165 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\Server\LanguageServer.cs

    Language service is shutting down...

4/10/2017 11:10:11 AM [ERROR] - Method "OnListenTaskCompleted" at line 337 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.LanguageServer.RunspaceDetails..ctor(RunspaceDetails eventArgs)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<PowerShellContext_RunspaceChanged>d__50.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
       at Microsoft.PowerShell.EditorServices.Utility.ThreadSynchronizationContext.RunLoopOnCurrentThread()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.LanguageServer.RunspaceDetails..ctor(RunspaceDetails eventArgs)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<PowerShellContext_RunspaceChanged>d__50.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
       at Microsoft.PowerShell.EditorServices.Utility.ThreadSynchronizationContext.RunLoopOnCurrentThread()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
```

**Comment by pcgeek86** [comment]
Edited log file output formatting on original post for readability.

**Comment by pcgeek86** [comment]
@ehouarn-perret Do you have any kind of software installed on your system that would prevent connectivity to the IPv4 loopback address on TCP 19754? It looks like something is actively preventing that connection from being made within the network stack, such as an overly aggressive firewall configuration. If it were an issue of the port not listening, you'd receive a timeout instead of a "connection refused" message.

**Comment by SydneyhSmith** [comment]
Closing as this issue is resolved.
