### ISSUE TITLE
Caught error while waiting for EditorServicesHost to complete: One or more errors occurred.

### ISSUE THREAD

**Issue by mbsj** [PowerShell/vscode-powershell#755]
### System Details

- Operating system name and version: Windows 7 Enterprise
- VS Code version: 1.12.2
- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`: 
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

```
PS C:\>code -v

1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
PS C:\>$pseditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0


PS C:\>code --list-extensions --show-versions

DavidAnson.vscode-markdownlint@0.7.2
donjayamanne.githistory@0.2.0
eamodio.gitlens@3.4.9
kamikillerto.vscode-colorize@0.5.1
mitchdenny.ecdc@0.10.3
ms-mssql.mssql@1.0.0
ms-vscode.PowerShell@1.0.0
ms-vsts.team@1.118.0
nonoroazoro.syncing@1.3.8
qub.qub-xml@1.1.2
robertohuertasm.vscode-icons@7.7.0
streetsidesoftware.code-spell-checker@1.1.0
Tyriar.sort-lines@1.2.0
wayou.vscode-todo-highlight@0.5.0
PS C:\>$PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

When edditing any script, after a while the following error is logged: 
```
Caught error while waiting for EditorServicesHost to complete:
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.WaitForExit()
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.

Specified argument was out of the range of valid values.
Parameter name: Position is outside of column range for line 22.
   at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
   at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
   at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventC
ontext eventContext)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass26_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWrite
r messageWriter)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
   at System.Threading.Tasks.Task.Execute()
```

This causes all intellisense and the like to stop functioning until the console is restarted. 

### Attached Logs

[EditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/1007539/EditorServices.zip)
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/1007540/vscode-powershell.zip)

**Comment by pcgeek86** [comment]
@mbsj I've seen cases where VSCode extensions can step on each others' toes. I know it's not the easiest thing to do, but would you mind removing the other extensions that you have installed and seeing if the issue persists?

**Comment by mbsj** [comment]
I ran through the extensions and it turns out that i was the [colorize](https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize) extension that tripped it up. At least it wasn't an essential extension :)

**Comment by pcgeek86** [comment]
Awesome! Thanks for investigating this further. I'm going to close this out for now, but feel free to comment back here so we can reopen it if you find out something new related to this.
