### ISSUE TITLE
Running debugger too soon after starting up crashes the language server

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/vscode-powershell#834]
### System Details

- Operating system name and version: Microsoft Windows [Version 6.1.7601] (Windows 7 Professional SP1)
- VS Code version: 1.12.2
- PowerShell extension version: 1.2.1
- Output from `$PSVersionTable`:
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
PS C:\Program Files (x86)\Microsoft VS Code\bin> .\code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de

PS C:\Program Files (x86)\Microsoft VS Code\bin> .\code --list-extensions --show-versions
ms-vscode.PowerShell@1.2.1
```

### Issue Description

I am experiencing a problem with debugging/running a Powershell script. 

"Running the contributed command:'PowerShell.StartDebugSession' failed."

### Attached Logs

[9:38:53] Language server starting...
powershell.exe started --
    pid: 10016
    exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    args: C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.2.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.2.1' -BundledModulesPath 'C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\logs\1496759933-3e8101cd-8737-4647-ad62-9f83bc4e63651496759913367\EditorServices.log' -SessionDetailsPath 'C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\sessions\PSES-VSCode-8820-923583' -FeatureFlags @()

Shutting down language client...

Terminating PowerShell process...
[9:39:18] Language server starting...
powershell.exe started --
    pid: 6708
    exe: C:\Windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe
    args: C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.2.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.2.1' -BundledModulesPath 'C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\logs\1496759958-3e8101cd-8737-4647-ad62-9f83bc4e63651496759913367\EditorServices.log' -SessionDetailsPath 'C:\Users\lit\.vscode\extensions\ms-vscode.powershell-1.2.1\sessions\PSES-VSCode-8820-839242' -FeatureFlags @()

[9:39:55] Language server startup failed.
Could not start language service: 
Timed out waiting for session file to appear.
[9:40:19] Language server startup failed.
Could not start language service: 
Timed out waiting for session file to appear.

**Comment by wsmelton** [comment]
I can attest that I got this testing a file after the May 2017 Code update. I am on Windows 10 Creator Update, released this past week.

1. Open a new file
2. Set language to PowerShell for the file (did not try and save it as ps1)
3. Added basic function that just outputs a message with `Write-Output`
4. No breakpoints
5. Hit F5 and the error noted shows up.
6. Reload window
7. Hit F5 again and no longer received error, script executed as expected.

After that first hit I could no longer duplicate the error.

**Comment by daviwil** [comment]
Any improvement after the 1.3.2 update?  @Liturgist if you can still reproduce the issue can you capture and send logs as described here:

https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by Liturgist** [comment]
I would like to test this, but I do not know that I have the version of which you speak. When I started VSC code and updated, this is what I have. Which part should be 1.3.2?

Version 1.13.0
Commit 376c52b955428d205459bea6619fc161fc8faacf
Date 2017-06-08T16:43:13.058Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by dfinke** [comment]
Click on the icon on the left to show `extensions`. You should see (or you can search for the) the PowerShell ext. Check the version number. 

![image](https://user-images.githubusercontent.com/67258/27152758-e5e47e9c-511c-11e7-8840-36926dab2e3b.png)

**Comment by rkeithhill** [comment]
I can repro this by following the instructions, then reloading the window, setting the untitled file's language to PowerShell and then immediately pressing F5.  If I wait until PowerShell has finished initializing I don't get the reported error.

I see this in the log - no exceptions but some logged errors:
```
6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs
6/14/2017 2:35:47 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "initialize",
      "arguments": {
        "clientID": "vscode",
        "adapterID": "PowerShell",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true
      },
      "type": "request",
      "seq": 1
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 1,
      "command": "initialize",
      "success": true,
      "body": {
        "supportsConfigurationDoneRequest": true,
        "supportsFunctionBreakpoints": true,
        "supportsConditionalBreakpoints": true,
        "supportsHitConditionalBreakpoints": true,
        "supportsEvaluateForHovers": false,
        "supportsSetVariable": true
      }
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "launch",
      "arguments": {
        "type": "PowerShell",
        "name": "PowerShell Launch Current File",
        "request": "launch",
        "args": [],
        "script": "untitled:Untitled-1",
        "internalConsoleOptions": "neverOpen"
      },
      "type": "request",
      "seq": 2
    }

6/14/2017 2:35:47 PM [ERROR] - Method "HandleLaunchRequest" at line 259 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    cwd path is invalid: The given path's format is not supported.

6/14/2017 2:35:47 PM [VERBOSE] - Method "HandleLaunchRequest" at line 278 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Working dir set to: C:\Users\hillr

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 2,
      "command": "launch",
      "success": true,
      "body": null
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "initialized",
      "body": null
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "setFunctionBreakpoints",
      "arguments": {
        "breakpoints": []
      },
      "type": "request",
      "seq": 3
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "ExecuteCommand" at line 491 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Attempting to execute command(s):
    
        Microsoft.PowerShell.Utility\Get-PSBreakpoint
        Microsoft.PowerShell.Utility\Remove-PSBreakpoint
    

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Ready
        New state: Running
        Result: NotFinished

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Running
        New state: Ready
        Result: Completed

6/14/2017 2:35:47 PM [VERBOSE] - Method "ExecuteCommand" at line 551 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution completed successfully.

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 3,
      "command": "setFunctionBreakpoints",
      "success": true,
      "body": {
        "breakpoints": []
      }
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "configurationDone",
      "type": "request",
      "seq": 4
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "ResolveFilePath" at line 354 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: untitled:Untitled-1

6/14/2017 2:35:47 PM [VERBOSE] - Method "ExecuteCommand" at line 491 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Attempting to execute command(s):
    
        function foo {
        Write-Output "In $($MyInvocation.MyCommand.Name)"
    }
    
    foo
        Out-Default
    

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Ready
        New state: Running
        Result: NotFinished

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 4,
      "command": "configurationDone",
      "success": true,
      "body": null
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "threads",
      "type": "request",
      "seq": 5
    }

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 5,
      "command": "threads",
      "success": true,
      "body": {
        "threads": [
          {
            "id": 1,
            "name": "Main Thread"
          }
        ]
      }
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Running
        New state: Ready
        Result: Completed

6/14/2017 2:35:47 PM [VERBOSE] - Method "ExecuteCommand" at line 551 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution completed successfully.

6/14/2017 2:35:47 PM [VERBOSE] - Method "ExecuteCommand" at line 491 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Attempting to execute command(s):
    
        prompt
    

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Ready
        New state: Running
        Result: NotFinished

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnExecutionCompleted" at line 113 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Execution completed, terminating...

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "terminated",
      "body": {
        "restart": false
      }
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Running
        New state: Ready
        Result: Completed

6/14/2017 2:35:47 PM [VERBOSE] - Method "ExecuteCommand" at line 551 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution completed successfully.

6/14/2017 2:35:47 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "disconnect",
      "arguments": {
        "restart": false
      },
      "type": "request",
      "seq": 6
    }

6/14/2017 2:35:47 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 6,
      "command": "disconnect",
      "success": true,
      "body": null
    }

6/14/2017 2:35:47 PM [NORMAL] - Method "Stop" at line 159 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Debug adapter is shutting down...

6/14/2017 2:35:47 PM [NORMAL] - Method "OnDebugServiceClientConnect" at line 292 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    Previous debug session ended, restarting debug service listener...

6/14/2017 2:35:47 PM [ERROR] - Method "ListenForMessages" at line 344 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs

    Stream terminated unexpectedly, ending MessageDispatcher loop
    
    Exception: IOException
    Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

6/14/2017 2:35:59 PM [VERBOSE] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 4,
      "method": "textDocument/hover",
      "params": {
        "textDocument": {
          "uri": "untitled:Untitled-1"
        },
        "position": {
          "line": 4,
          "character": 1
        }
      }
    }

6/14/2017 2:35:59 PM [VERBOSE] - Method "ResolveFilePath" at line 354 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: untitled:Untitled-1

6/14/2017 2:35:59 PM [VERBOSE] - Method "ExecuteCommand" at line 491 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Attempting to execute command(s):
    
        Microsoft.PowerShell.Core\Get-Command
    

6/14/2017 2:35:59 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Ready
        New state: Running
        Result: NotFinished

6/14/2017 2:35:59 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Running
        New state: Ready
        Result: Completed

6/14/2017 2:35:59 PM [VERBOSE] - Method "ExecuteCommand" at line 551 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution completed successfully.

6/14/2017 2:35:59 PM [VERBOSE] - Method "ExecuteCommand" at line 491 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Attempting to execute command(s):
    
        Microsoft.PowerShell.Core\Get-Help
    

6/14/2017 2:35:59 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Ready
        New state: Running
        Result: NotFinished

6/14/2017 2:35:59 PM [VERBOSE] - Method "OnSessionStateChanged" at line 1138 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Session state changed --
    
        Old state: Running
        New state: Ready
        Result: Completed

6/14/2017 2:35:59 PM [VERBOSE] - Method "ExecuteCommand" at line 551 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution completed successfully.

6/14/2017 2:35:59 PM [VERBOSE] - Method "WriteMessage" at line 62 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": "4",
      "result": {
        "contents": [
          {
            "language": "PowerShell",
            "value": "function foo"
          },
          {
            "language": "markdown",
            "value": "\r\nfoo \r\n"
          }
        ],
        "range": {
          "start": {
            "line": 4,
            "character": 0
          },
          "end": {
            "line": 4,
            "character": 3
          }
        }
      }
    }
```

BTW you can get another error (Debug adapter terminated unexpectedly) if you restart the PowerShell session and press F5 too soon.  I'm seeing this stack trace:
```
An error occurred while starting PowerShell Editor Services:

Exception calling "StartDebugService" with "3" argument(s): "An attempt was made to access a socket in a way f
orbidden by its access permissions"
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exc
eption exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inp
utToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.TcpSocketServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartDebugService(Int32 debugServicePort, Pr
ofilePaths profilePaths, Boolean useExistingSession)
   at CallSite.Target(Closure , CallSite , Object , Object , Object , Boolean )
```

**Comment by Liturgist** [comment]
I do not seem to have the same problem using 1.3.2. Thanks for your help.

**Comment by daviwil** [comment]
Thanks for confirming that it's improved in 1.3.2!  I'm concerned about the issues Keith found so I'll keep this issue open for now so we can investigate.

**Comment by TheIncorrigible1** [comment]
@daviwil I'm experiencing this problem on vscode 1.32.2 (also seen on insiders 1.33).  Both preview and stable extensions.  I've tried with v6.2 and v5.0.  From the editor services:

    [Error - 12:54:24 PM] Connection to server got closed. Server will not be restarted.
    [Error - 12:54:24 PM] Request codeLens/resolve failed.
    Error: Connection got disposed.
        at Object.dispose (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-languageclient\lib\client.js:71:35)
        at LanguageClient.handleConnectionClosed (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-languageclient\lib\client.js:2150:42)
        at LanguageClient.handleConnectionClosed (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-languageclient\lib\main.js:150:15)
        at closeHandler (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-languageclient\lib\client.js:2137:18)
        at CallbackList.invoke (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageWriter.fireClose (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:39:27)
        at Socket.constructor.writable.on (\vscode\data\extensions\ms-vscode.powershell-1.12.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:58:46)
        at Socket.emit (events.js:187:15)
        at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)

**Comment by TylerLeonhardt** [comment]
This has been fixed a while ago... the extension says "please wait for extension to fully start up" or something similar. Please feel free to open a new issue if you still see this problem!
